<?php

use Illuminate\Database\Seeder;

class ActivityCalendarTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('activity_calendar')->delete();
        
        \DB::table('activity_calendar')->insert(array (
            0 => 
            array (
                'id' => 1,
                'activity_id' => 1,
                'venue_id' => 1,
                'name' => 'Remo Test Listing - Remo Test Playz Headquarters',
                'auto_name' => 0,
                'disabled_dates' => '["26\\/04\\/2017"]',
                'closed_holidays' => 1,
                'created_at' => '2017-04-24 15:52:02',
                'updated_at' => '2017-04-24 15:52:34',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            1 => 
            array (
                'id' => 2,
                'activity_id' => 2,
                'venue_id' => 3,
                'name' => 'Apple Care Class - True Headquarters',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-04-24 17:30:16',
                'updated_at' => '2017-04-24 17:30:56',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            2 => 
            array (
                'id' => 3,
                'activity_id' => 3,
                'venue_id' => 3,
                'name' => 'Workz Test Waitlist - True Headquarters',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 0,
                'created_at' => '2017-04-24 18:06:35',
                'updated_at' => '2017-04-24 18:06:40',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            3 => 
            array (
                'id' => 4,
                'activity_id' => 3,
                'venue_id' => 3,
                'name' => 'Workz Test Waitlist - True Headquarters - Autumn Holidays',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 0,
                'created_at' => '2017-04-24 18:15:12',
                'updated_at' => '2017-04-24 18:15:12',
                'cloned_from' => 3,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            4 => 
            array (
                'id' => 5,
                'activity_id' => 3,
                'venue_id' => 3,
                'name' => 'Workz Test Waitlist - True Headquarters - Spring Holidays',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 0,
                'created_at' => '2017-04-24 18:49:14',
                'updated_at' => '2017-04-24 18:49:14',
                'cloned_from' => 4,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            5 => 
            array (
                'id' => 6,
                'activity_id' => 3,
                'venue_id' => 3,
                'name' => 'Workz Test Waitlist - True Headquarters - Dancing Holiday',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 0,
                'created_at' => '2017-04-24 19:01:28',
                'updated_at' => '2017-04-24 19:01:28',
                'cloned_from' => 5,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            6 => 
            array (
                'id' => 7,
                'activity_id' => 4,
                'venue_id' => 3,
                'name' => 'Dance Class - True Headquarters',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 0,
                'created_at' => '2017-04-24 19:46:17',
                'updated_at' => '2017-05-03 11:28:49',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            7 => 
            array (
                'id' => 8,
                'activity_id' => 6,
                'venue_id' => 4,
                'name' => 'Information Technology for Kids - True Agency Headquarters',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 0,
                'created_at' => '2017-04-25 11:12:25',
                'updated_at' => '2017-04-25 11:13:14',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            8 => 
            array (
                'id' => 9,
                'activity_id' => 8,
                'venue_id' => 6,
                'name' => 'Tennis lessons - Ardrie Park Tennis Club',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-04-28 09:16:19',
                'updated_at' => '2017-04-28 09:20:30',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            9 => 
            array (
                'id' => 11,
                'activity_id' => 11,
                'venue_id' => 8,
                'name' => 'Prep For Prep - Prep For Prep Headquarters',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-05-01 10:53:43',
                'updated_at' => '2017-05-01 10:59:15',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            10 => 
            array (
                'id' => 12,
                'activity_id' => 10,
                'venue_id' => 9,
                'name' => 'Craft Classes - Mornington Community Centre',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-05-01 13:43:50',
                'updated_at' => '2017-05-09 09:40:35',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            11 => 
            array (
                'id' => 13,
                'activity_id' => 8,
                'venue_id' => 6,
                'name' => 'Tennis lessons - Ardrie Park Tennis Club - Term 3 2017',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-05-02 10:03:31',
                'updated_at' => '2017-05-02 10:03:31',
                'cloned_from' => 9,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            12 => 
            array (
                'id' => 14,
                'activity_id' => 8,
                'venue_id' => 6,
                'name' => 'Tennis lessons - Ardrie Park Tennis Club - Term 4 2017',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-05-03 10:36:19',
                'updated_at' => '2017-05-03 10:36:19',
                'cloned_from' => 13,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            13 => 
            array (
                'id' => 15,
                'activity_id' => 11,
                'venue_id' => 8,
                'name' => 'Prep For Prep - Prep For Prep Headquarters',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 0,
                'created_at' => '2017-05-04 11:33:06',
                'updated_at' => '2017-05-04 11:33:23',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            14 => 
            array (
                'id' => 16,
                'activity_id' => 11,
                'venue_id' => 8,
                'name' => 'Prep For Prep - Prep For Prep Headquarters',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-05-04 11:56:25',
                'updated_at' => '2017-05-04 12:11:33',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            15 => 
            array (
                'id' => 17,
                'activity_id' => 11,
                'venue_id' => 8,
                'name' => 'Prep For Prep - Prep For Prep Headquarters - term 3',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-05-04 12:06:40',
                'updated_at' => '2017-05-04 12:06:40',
                'cloned_from' => 16,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            16 => 
            array (
                'id' => 18,
                'activity_id' => 11,
                'venue_id' => 8,
                'name' => 'Prep For Prep - Prep For Prep Headquarters - term 3',
                'auto_name' => 0,
                'disabled_dates' => '["09\\/06\\/2017"]',
                'closed_holidays' => 1,
                'created_at' => '2017-05-04 12:17:11',
                'updated_at' => '2017-05-04 12:17:11',
                'cloned_from' => 11,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            17 => 
            array (
                'id' => 19,
                'activity_id' => 11,
                'venue_id' => 8,
                'name' => 'Prep For Prep - Prep For Prep Headquarters - term 3',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-05-04 12:23:52',
                'updated_at' => '2017-05-04 12:23:52',
                'cloned_from' => 16,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            18 => 
            array (
                'id' => 20,
                'activity_id' => 12,
                'venue_id' => 10,
                'name' => 'crazy critters - New Town Community Centre',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-05-04 13:04:47',
                'updated_at' => '2017-05-04 13:06:34',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            19 => 
            array (
                'id' => 21,
                'activity_id' => 15,
                'venue_id' => 5,
                'name' => 'Dorinnia activities - Rachel\'s Kids Acitivities Headquarters',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-05-04 13:06:22',
                'updated_at' => '2017-05-04 13:06:41',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            20 => 
            array (
                'id' => 22,
                'activity_id' => 12,
                'venue_id' => 10,
                'name' => 'crazy critters - New Town Community Centre - term 3',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-05-04 13:25:52',
                'updated_at' => '2017-05-04 13:25:53',
                'cloned_from' => 20,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            21 => 
            array (
                'id' => 23,
                'activity_id' => 15,
                'venue_id' => 5,
                'name' => 'Dorinnia activities - Rachel\'s Kids Acitivities Headquarters - Term 3 2017',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-05-04 13:25:59',
                'updated_at' => '2017-05-04 13:26:00',
                'cloned_from' => 21,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            22 => 
            array (
                'id' => 25,
                'activity_id' => 8,
                'venue_id' => 5,
                'name' => 'Tennis lessons - Rachel\'s Kids Acitivities Headquarters',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-05-06 07:18:40',
                'updated_at' => '2017-05-06 07:18:54',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            23 => 
            array (
                'id' => 27,
                'activity_id' => 16,
                'venue_id' => 5,
                'name' => 'Craft Activities - Rachel\'s Kids Acitivities Headquarters',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-05-06 11:53:42',
                'updated_at' => '2017-05-06 11:54:04',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            24 => 
            array (
                'id' => 28,
                'activity_id' => 16,
                'venue_id' => 5,
                'name' => 'Craft Activities - Rachel\'s Kids Acitivities Headquarters - Term 3 2017',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-05-06 14:36:02',
                'updated_at' => '2017-05-06 14:36:03',
                'cloned_from' => 27,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            25 => 
            array (
                'id' => 29,
                'activity_id' => 16,
                'venue_id' => 5,
                'name' => 'Craft Activities - Rachel\'s Kids Acitivities Headquarters - Term 4 2017',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-05-06 14:40:24',
                'updated_at' => '2017-05-06 14:40:24',
                'cloned_from' => 28,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            26 => 
            array (
                'id' => 30,
                'activity_id' => 4,
                'venue_id' => 3,
                'name' => 'Dance Class - True Headquarters',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-05-11 09:06:21',
                'updated_at' => '2017-05-11 09:09:56',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            27 => 
            array (
                'id' => 31,
                'activity_id' => 18,
                'venue_id' => 3,
                'name' => 'T&C - True Headquarters',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 0,
                'created_at' => '2017-05-11 12:17:16',
                'updated_at' => '2017-05-11 12:17:24',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            28 => 
            array (
                'id' => 32,
                'activity_id' => 19,
                'venue_id' => 11,
                'name' => 'Testing activities - Local Gym',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 0,
                'created_at' => '2017-05-11 12:50:24',
                'updated_at' => '2017-05-11 12:50:32',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            29 => 
            array (
                'id' => 33,
                'activity_id' => 8,
                'venue_id' => 5,
                'name' => 'Tennis lessons - Rachel\'s Kids Acitivities Headquarters - Term 4 2017',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-07-21 11:19:43',
                'updated_at' => '2017-07-21 11:19:44',
                'cloned_from' => 25,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            30 => 
            array (
                'id' => 36,
                'activity_id' => 21,
                'venue_id' => 12,
                'name' => 'Kristie\'s Test Party Listing  - Kristie\'s Awesome Activities Headquarters',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 0,
                'created_at' => '2017-07-28 12:56:08',
                'updated_at' => '2017-07-28 13:01:51',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            31 => 
            array (
                'id' => 37,
                'activity_id' => 23,
                'venue_id' => 14,
                'name' => 'Piano lessons - Rachel\'s Music Business Headquarters',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-08-04 13:47:09',
                'updated_at' => '2017-08-04 13:48:05',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            32 => 
            array (
                'id' => 39,
                'activity_id' => 20,
                'venue_id' => 5,
                'name' => 'Badge Making classes - Rachel\'s Kids Acitivities Headquarters - Term 3 2017',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-08-07 10:10:28',
                'updated_at' => '2017-08-07 10:10:29',
                'cloned_from' => 38,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            33 => 
            array (
                'id' => 41,
                'activity_id' => 20,
                'venue_id' => 5,
                'name' => 'Badge Making classes - Rachel\'s Kids Acitivities Headquarters - Term 4 2017',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-08-07 10:39:12',
                'updated_at' => '2017-08-07 10:39:12',
                'cloned_from' => 39,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            34 => 
            array (
                'id' => 42,
                'activity_id' => 24,
                'venue_id' => 18,
                'name' => 'Kristie\'s Testing Activity - Kristie\'s House',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 0,
                'created_at' => '2017-08-08 10:03:37',
                'updated_at' => '2017-08-08 10:11:42',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            35 => 
            array (
                'id' => 44,
                'activity_id' => 24,
                'venue_id' => 18,
                'name' => 'Kristie\'s Testing Activity - Kristie\'s House - Term 3',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 0,
                'created_at' => '2017-08-09 11:04:13',
                'updated_at' => '2017-08-09 11:04:14',
                'cloned_from' => 42,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            36 => 
            array (
                'id' => 45,
                'activity_id' => 26,
                'venue_id' => 14,
                'name' => 'keyboard lessons - Rachel\'s Music Business Headquarters',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-08-17 14:34:42',
                'updated_at' => '2017-08-17 14:34:54',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            37 => 
            array (
                'id' => 46,
                'activity_id' => 27,
                'venue_id' => 19,
                'name' => 'Percussion Classes - Local Music Happ',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-08-22 10:55:12',
                'updated_at' => '2017-08-22 10:55:25',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            38 => 
            array (
                'id' => 47,
                'activity_id' => 28,
                'venue_id' => 20,
                'name' => 'Tennis Classes - Sporting Fun Headquarters',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-08-22 18:59:33',
                'updated_at' => '2017-08-22 19:00:12',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            39 => 
            array (
                'id' => 58,
                'activity_id' => 21,
                'venue_id' => 12,
                'name' => 'Kristie\'s Test Party Listing  - Kristie\'s Awesome Activities Headquarters - Term 2',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 0,
                'created_at' => '2017-08-23 09:13:49',
                'updated_at' => '2017-08-23 09:13:49',
                'cloned_from' => 36,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            40 => 
            array (
                'id' => 59,
                'activity_id' => 27,
                'venue_id' => 19,
                'name' => 'Percussion Classes - Local Music Hall - Term 4',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-08-23 11:46:09',
                'updated_at' => '2017-08-23 11:46:09',
                'cloned_from' => 46,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            41 => 
            array (
                'id' => 60,
                'activity_id' => 29,
                'venue_id' => 21,
                'name' => 'Cooking Classes - Jeff\'s Kids ACtivities Headquarters',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-08-24 09:12:06',
                'updated_at' => '2017-09-01 10:28:20',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            42 => 
            array (
                'id' => 61,
                'activity_id' => 30,
                'venue_id' => 12,
                'name' => 'General Fun Activity - Kristie\'s Awesome Activities Headquarters',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 0,
                'created_at' => '2017-08-24 13:40:18',
                'updated_at' => '2017-08-24 13:40:57',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            43 => 
            array (
                'id' => 63,
                'activity_id' => 29,
                'venue_id' => 21,
                'name' => 'Cooking Classes - Jeff\'s Kids ACtivities Headquarters - Term 4',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-08-31 09:31:08',
                'updated_at' => '2017-08-31 09:31:09',
                'cloned_from' => 60,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            44 => 
            array (
                'id' => 64,
                'activity_id' => 31,
                'venue_id' => 12,
                'name' => 'Testing package spots - Kristie\'s Awesome Activities Headquarters',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 0,
                'created_at' => '2017-08-31 15:10:33',
                'updated_at' => '2017-08-31 15:10:44',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            45 => 
            array (
                'id' => 65,
                'activity_id' => 32,
                'venue_id' => 12,
                'name' => 'Single sessions in package - Kristie\'s Awesome Activities Headquarters',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 0,
                'created_at' => '2017-09-01 09:38:33',
                'updated_at' => '2017-09-01 09:39:45',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            46 => 
            array (
                'id' => 66,
                'activity_id' => 34,
                'venue_id' => 23,
                'name' => 'Footy Club - Box Hill Gardens',
                'auto_name' => 0,
                'disabled_dates' => '["07\\/09\\/2017"]',
                'closed_holidays' => 1,
                'created_at' => '2017-09-04 12:00:43',
                'updated_at' => '2017-09-04 12:03:53',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            47 => 
            array (
                'id' => 67,
                'activity_id' => 36,
                'venue_id' => 23,
                'name' => 'Welcome Spring Party - Box Hill Gardens',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-09-04 14:39:15',
                'updated_at' => '2017-09-04 14:40:57',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            48 => 
            array (
                'id' => 68,
                'activity_id' => 39,
                'venue_id' => 21,
                'name' => 'Cooking Parties - Jeff\'s Kids ACtivities Headquarters',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-09-06 10:36:59',
                'updated_at' => '2017-09-06 10:37:36',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            49 => 
            array (
                'id' => 69,
                'activity_id' => 40,
                'venue_id' => 21,
                'name' => 'Cooking Holiday Program - Jeff\'s Kids ACtivities Headquarters',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 0,
                'created_at' => '2017-09-07 13:15:00',
                'updated_at' => '2017-09-07 13:15:46',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            50 => 
            array (
                'id' => 70,
                'activity_id' => 41,
                'venue_id' => 21,
                'name' => 'Masterchef Performance Day - Jeff\'s Kids ACtivities Headquarters',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 0,
                'created_at' => '2017-09-11 11:13:14',
                'updated_at' => '2017-09-11 11:13:26',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            51 => 
            array (
                'id' => 71,
                'activity_id' => 35,
                'venue_id' => 23,
                'name' => 'Photography - Box Hill Gardens',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-09-11 11:25:28',
                'updated_at' => '2017-09-11 11:26:38',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            52 => 
            array (
                'id' => 72,
                'activity_id' => 42,
                'venue_id' => 22,
                'name' => 'Year end Party  - Play Kids Headquarters',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-09-11 12:43:16',
                'updated_at' => '2017-09-11 12:43:32',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            53 => 
            array (
                'id' => 73,
                'activity_id' => 38,
                'venue_id' => 22,
                'name' => 'Cupcake Day - Play Kids Headquarters',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-09-11 13:55:25',
                'updated_at' => '2017-09-11 14:00:33',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            54 => 
            array (
                'id' => 74,
                'activity_id' => 43,
                'venue_id' => 24,
                'name' => 'Puppy Training - Wattle Park',
                'auto_name' => 0,
                'disabled_dates' => '["12\\/09\\/2017"]',
                'closed_holidays' => 1,
                'created_at' => '2017-09-11 14:19:07',
                'updated_at' => '2017-09-11 14:20:08',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            55 => 
            array (
                'id' => 75,
                'activity_id' => 44,
                'venue_id' => 28,
                'name' => 'Piano lessons - Rachel\'s Music Classes Headquarters',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-09-12 11:39:21',
                'updated_at' => '2017-09-12 11:40:45',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            56 => 
            array (
                'id' => 76,
                'activity_id' => 45,
                'venue_id' => 28,
                'name' => 'Harp lessons - Rachel\'s Music Classes Headquarters',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-09-12 12:59:13',
                'updated_at' => '2017-09-12 12:59:31',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            57 => 
            array (
                'id' => 77,
                'activity_id' => 46,
                'venue_id' => 29,
                'name' => 'Piano Party - Piano van',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-09-12 13:27:46',
                'updated_at' => '2017-09-12 13:28:05',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            58 => 
            array (
                'id' => 78,
                'activity_id' => 47,
                'venue_id' => 30,
                'name' => 'Piano Lessons - Rachel\'s Music Hall',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-09-13 10:41:44',
                'updated_at' => '2017-09-13 10:54:55',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            59 => 
            array (
                'id' => 80,
                'activity_id' => 50,
                'venue_id' => 34,
                'name' => 'Holiday Tennis Lessons - Tennis Courts',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-09-14 10:00:06',
                'updated_at' => '2017-09-14 10:01:00',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            60 => 
            array (
                'id' => 81,
                'activity_id' => 51,
                'venue_id' => 31,
                'name' => 'Cultural Dancing - Kids activity providers Headquarters',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-09-14 10:37:48',
                'updated_at' => '2017-09-14 10:37:59',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            61 => 
            array (
                'id' => 82,
                'activity_id' => 48,
                'venue_id' => 30,
                'name' => 'keyboard lessons - Rachel\'s Music Hall',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-09-14 12:22:02',
                'updated_at' => '2017-09-14 12:22:14',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            62 => 
            array (
                'id' => 83,
                'activity_id' => 52,
                'venue_id' => 30,
                'name' => 'Piano Concerts - Rachel\'s Music Hall',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-09-15 10:57:35',
                'updated_at' => '2017-09-15 10:58:06',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            63 => 
            array (
                'id' => 84,
                'activity_id' => 53,
                'venue_id' => 35,
                'name' => 'Baking Classes - Cooking Company Headquarters',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-09-15 12:24:45',
                'updated_at' => '2017-09-15 12:31:43',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            64 => 
            array (
                'id' => 85,
                'activity_id' => 53,
                'venue_id' => 35,
                'name' => 'Baking Classes - Cooking Company Headquarters - Term 1 2018',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-09-19 09:36:24',
                'updated_at' => '2017-09-19 09:36:25',
                'cloned_from' => 84,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            65 => 
            array (
                'id' => 86,
                'activity_id' => 54,
                'venue_id' => 36,
                'name' => 'Party Food - Party Food Van',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-09-19 10:08:24',
                'updated_at' => '2017-09-19 11:06:03',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            66 => 
            array (
                'id' => 87,
                'activity_id' => 55,
                'venue_id' => 37,
                'name' => 'Ballet classes - Dance Academy Headquarters',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-09-19 13:33:50',
                'updated_at' => '2017-09-19 13:34:34',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            67 => 
            array (
                'id' => 88,
                'activity_id' => 56,
                'venue_id' => 38,
                'name' => 'Berry Picking - Berry Picking Headquarters',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-09-20 10:10:48',
                'updated_at' => '2017-09-20 10:13:07',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            68 => 
            array (
                'id' => 89,
                'activity_id' => 57,
                'venue_id' => 38,
                'name' => 'Farm tours - Berry Picking Headquarters',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-09-20 10:22:06',
                'updated_at' => '2017-09-20 10:22:16',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            69 => 
            array (
                'id' => 90,
                'activity_id' => 58,
                'venue_id' => 30,
                'name' => 'Music Holiday Program - Rachel\'s Music Hall',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-09-21 09:01:43',
                'updated_at' => '2017-09-25 08:09:56',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            70 => 
            array (
                'id' => 91,
                'activity_id' => 49,
                'venue_id' => 31,
                'name' => 'Cup cake day - Kids activity providers Headquarters - 1st Week',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-09-21 09:33:24',
                'updated_at' => '2017-09-21 09:33:25',
                'cloned_from' => 79,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            71 => 
            array (
                'id' => 92,
                'activity_id' => 49,
                'venue_id' => 31,
                'name' => 'Cup cake day - Kids activity providers Headquarters - 1st Week',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-09-21 09:44:50',
                'updated_at' => '2017-09-21 09:44:50',
                'cloned_from' => 91,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            72 => 
            array (
                'id' => 93,
                'activity_id' => 60,
                'venue_id' => 31,
                'name' => 'Cup cake day - Kids activity providers Headquarters - 1st Week',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-09-21 11:13:09',
                'updated_at' => '2017-09-21 11:13:09',
                'cloned_from' => 91,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            73 => 
            array (
                'id' => 94,
                'activity_id' => 60,
                'venue_id' => 31,
                'name' => 'Cup cake day - Kids activity providers Headquarters - 1st Week',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-09-21 11:13:09',
                'updated_at' => '2017-09-21 11:13:09',
                'cloned_from' => 92,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            74 => 
            array (
                'id' => 95,
                'activity_id' => 61,
                'venue_id' => 40,
                'name' => 'School Holiday Cricket Club - Pitcher Park Alphington',
                'auto_name' => 0,
                'disabled_dates' => '["29\\/09\\/2017"]',
                'closed_holidays' => 1,
                'created_at' => '2017-09-21 11:39:17',
                'updated_at' => '2017-09-21 11:44:52',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            75 => 
            array (
                'id' => 96,
                'activity_id' => 61,
                'venue_id' => 40,
                'name' => 'School Holiday Cricket Club - Pitcher Park Alphington',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 0,
                'created_at' => '2017-09-21 15:22:38',
                'updated_at' => '2017-09-21 15:23:15',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            76 => 
            array (
                'id' => 97,
                'activity_id' => 61,
                'venue_id' => 40,
                'name' => 'School Holiday Cricket Club - Pitcher Park Alphington',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-09-21 15:34:11',
                'updated_at' => '2017-09-21 15:34:43',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            77 => 
            array (
                'id' => 99,
                'activity_id' => 62,
                'venue_id' => 36,
                'name' => 'Saturday NIght Parties - Party Food Van',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-09-24 09:36:41',
                'updated_at' => '2017-09-24 09:36:55',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            78 => 
            array (
                'id' => 100,
                'activity_id' => 63,
                'venue_id' => 36,
                'name' => 'Sunday Night Party - Private - Party Food Van',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-09-24 09:51:59',
                'updated_at' => '2017-09-24 09:52:11',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            79 => 
            array (
                'id' => 101,
                'activity_id' => 58,
                'venue_id' => 30,
                'name' => 'Music Holiday Program - Rachel\'s Music Hall - EOY holidays Jan 8-12',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-09-25 08:16:08',
                'updated_at' => '2017-09-25 08:16:08',
                'cloned_from' => 90,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            80 => 
            array (
                'id' => 102,
                'activity_id' => 61,
                'venue_id' => 40,
                'name' => 'School Holiday Cricket Club - Pitcher Park Alphington',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 0,
                'created_at' => '2017-09-25 15:30:24',
                'updated_at' => '2017-09-25 15:31:07',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            81 => 
            array (
                'id' => 103,
                'activity_id' => 61,
                'venue_id' => 40,
                'name' => 'School Holiday Cricket Club - Pitcher Park Alphington',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 0,
                'created_at' => '2017-09-26 09:52:42',
                'updated_at' => '2017-09-26 09:53:12',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            82 => 
            array (
                'id' => 104,
                'activity_id' => 66,
                'venue_id' => 43,
                'name' => 'Weekly Staurday Cheer - Victorian State cheerleaders',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 0,
                'created_at' => '2017-09-27 10:38:08',
                'updated_at' => '2017-09-27 10:42:22',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            83 => 
            array (
                'id' => 105,
                'activity_id' => 67,
                'venue_id' => 37,
                'name' => 'Tap Dance Classes - Dance Academy Headquarters',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-09-27 11:20:03',
                'updated_at' => '2017-09-27 11:20:19',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            84 => 
            array (
                'id' => 106,
                'activity_id' => 61,
                'venue_id' => 40,
                'name' => 'School Holiday Cricket Club - Pitcher Park Alphington',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 0,
                'created_at' => '2017-09-27 12:34:30',
                'updated_at' => '2017-10-02 11:29:31',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            85 => 
            array (
                'id' => 107,
                'activity_id' => 61,
                'venue_id' => 40,
                'name' => 'School Holiday Cricket Club - Pitcher Park Alphington',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 0,
                'created_at' => '2017-09-27 13:30:27',
                'updated_at' => '2017-09-27 13:32:02',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            86 => 
            array (
                'id' => 108,
                'activity_id' => 67,
                'venue_id' => 37,
                'name' => 'Tap Dance Classes - Dance Academy Headquarters - Term 1 2018',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-09-27 13:52:45',
                'updated_at' => '2017-09-27 13:52:45',
                'cloned_from' => 105,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            87 => 
            array (
                'id' => 109,
                'activity_id' => 69,
                'venue_id' => 40,
                'name' => 'Soccer Skills - Pitcher Park Alphington',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 0,
                'created_at' => '2017-09-27 14:59:06',
                'updated_at' => '2017-09-27 14:59:17',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            88 => 
            array (
                'id' => 111,
                'activity_id' => 71,
                'venue_id' => 46,
                'name' => 'Apple Holiday Activities - Apple Activities HQ',
                'auto_name' => 0,
                'disabled_dates' => '["10\\/01\\/2018"]',
                'closed_holidays' => 1,
                'created_at' => '2017-09-29 07:23:08',
                'updated_at' => '2017-09-29 07:23:34',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            89 => 
            array (
                'id' => 112,
                'activity_id' => 74,
                'venue_id' => 46,
                'name' => 'Classes - Apple Activities HQ',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-10-01 12:23:47',
                'updated_at' => '2017-10-01 12:24:01',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            90 => 
            array (
                'id' => 113,
                'activity_id' => 61,
                'venue_id' => 40,
                'name' => 'School Holiday Cricket Club - Pitcher Park Alphington',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 0,
                'created_at' => '2017-10-02 11:22:21',
                'updated_at' => '2017-10-02 11:23:20',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            91 => 
            array (
                'id' => 114,
                'activity_id' => 61,
                'venue_id' => 40,
                'name' => 'School Holiday Cricket Club - Pitcher Park Alphington',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 0,
                'created_at' => '2017-10-02 11:25:58',
                'updated_at' => '2017-10-02 11:26:42',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            92 => 
            array (
                'id' => 115,
                'activity_id' => 75,
                'venue_id' => 40,
                'name' => 'Netball Skills - Pitcher Park Alphington',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 0,
                'created_at' => '2017-10-02 11:33:27',
                'updated_at' => '2017-10-02 11:33:53',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            93 => 
            array (
                'id' => 116,
                'activity_id' => 75,
                'venue_id' => 40,
                'name' => 'Netball Skills - Pitcher Park Alphington',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 0,
                'created_at' => '2017-10-02 11:38:48',
                'updated_at' => '2017-10-02 11:39:38',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            94 => 
            array (
                'id' => 117,
                'activity_id' => 75,
                'venue_id' => 0,
                'name' => 'Netball Skills',
                'auto_name' => 0,
                'disabled_dates' => '',
                'closed_holidays' => 0,
                'created_at' => '2017-10-02 11:41:00',
                'updated_at' => '2017-10-02 11:41:00',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            95 => 
            array (
                'id' => 118,
                'activity_id' => 75,
                'venue_id' => 40,
                'name' => 'Netball Skills - Pitcher Park Alphington',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 0,
                'created_at' => '2017-10-02 11:41:04',
                'updated_at' => '2017-10-02 11:41:33',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            96 => 
            array (
                'id' => 120,
                'activity_id' => 79,
                'venue_id' => 48,
                'name' => 'Test Listing - Out Of The Box Solutions Headquarters',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-10-10 15:14:38',
                'updated_at' => '2017-10-10 15:15:13',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            97 => 
            array (
                'id' => 121,
                'activity_id' => 80,
                'venue_id' => 30,
                'name' => 'Music Theory Class - Rachel\'s Music Hall',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-10-11 09:16:38',
                'updated_at' => '2017-10-16 12:45:14',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            98 => 
            array (
                'id' => 122,
                'activity_id' => 78,
                'venue_id' => 40,
                'name' => 'Test - Pitcher Park Alphington',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 0,
                'created_at' => '2017-10-12 10:44:30',
                'updated_at' => '2017-10-12 10:44:43',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            99 => 
            array (
                'id' => 123,
                'activity_id' => 83,
                'venue_id' => 52,
                'name' => 'Test - test business Headquarters',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 0,
                'created_at' => '2017-10-17 15:33:27',
                'updated_at' => '2017-10-17 15:34:03',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            100 => 
            array (
                'id' => 124,
                'activity_id' => 47,
                'venue_id' => 30,
                'name' => 'Piano Lessons - Rachel\'s Music Hall - Term 1 2018',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-10-18 11:08:02',
                'updated_at' => '2017-10-18 11:08:03',
                'cloned_from' => 78,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            101 => 
            array (
                'id' => 125,
                'activity_id' => 80,
                'venue_id' => 30,
                'name' => 'Music Theory Class - Rachel\'s Music Hall - Term 1 2018',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-10-19 10:43:26',
                'updated_at' => '2017-10-19 10:43:27',
                'cloned_from' => 121,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            102 => 
            array (
                'id' => 127,
                'activity_id' => 84,
                'venue_id' => 53,
                'name' => 'Sonny\'s Holiday Program - Sunnytime Kids\' Classes Headquarters',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-10-19 13:11:32',
                'updated_at' => '2017-10-19 13:13:29',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            103 => 
            array (
                'id' => 128,
                'activity_id' => 84,
                'venue_id' => 53,
                'name' => 'Sonny\'s Holiday Program - Sunnytime Kids\' Classes Headquarters - April holidays 2018',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-10-19 14:21:27',
                'updated_at' => '2017-10-19 14:21:27',
                'cloned_from' => 127,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            104 => 
            array (
                'id' => 129,
                'activity_id' => 84,
                'venue_id' => 53,
                'name' => 'Sonny\'s Holiday Program - Sunnytime Kids\' Classes Headquarters - September holidays 2018',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-10-20 07:57:56',
                'updated_at' => '2017-10-20 07:57:56',
                'cloned_from' => 128,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            105 => 
            array (
                'id' => 130,
                'activity_id' => 86,
                'venue_id' => 54,
                'name' => 'Piano Lessons - Magic Music Lessons Headquarters',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-10-24 11:47:08',
                'updated_at' => '2017-10-24 11:51:30',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            106 => 
            array (
                'id' => 131,
                'activity_id' => 88,
                'venue_id' => 56,
                'name' => 'Cricket Skills - Pitcher Park',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-10-25 09:11:59',
                'updated_at' => '2017-10-25 09:12:37',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            107 => 
            array (
                'id' => 132,
                'activity_id' => 89,
                'venue_id' => 56,
                'name' => 'test - Pitcher Park',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 0,
                'created_at' => '2017-10-25 09:33:45',
                'updated_at' => '2017-10-25 09:33:58',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            108 => 
            array (
                'id' => 133,
                'activity_id' => 90,
                'venue_id' => 57,
                'name' => 'Sonny\'s Holiday Program - Sunnytime Kids\' Classes Headquarters',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-10-25 12:03:56',
                'updated_at' => '2017-10-25 12:05:00',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            109 => 
            array (
                'id' => 134,
                'activity_id' => 91,
                'venue_id' => 58,
                'name' => 'Piano Lessons - Penny\'s Piano Lessons Headquarters',
                'auto_name' => 0,
                'disabled_dates' => '["19\\/02\\/2018"]',
                'closed_holidays' => 1,
                'created_at' => '2017-10-26 10:07:02',
                'updated_at' => '2017-11-03 11:44:39',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            110 => 
            array (
                'id' => 138,
                'activity_id' => 92,
                'venue_id' => 58,
                'name' => 'Piano EOY Concert - Penny\'s Piano Lessons Headquarters',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 0,
                'created_at' => '2017-10-26 13:36:05',
                'updated_at' => '2017-10-26 13:37:41',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            111 => 
            array (
                'id' => 139,
                'activity_id' => 91,
                'venue_id' => 58,
                'name' => 'Piano Lessons - Penny\'s Piano Lessons Headquarters - Term 2 2018',
                'auto_name' => 0,
                'disabled_dates' => '["19\\/02\\/2018"]',
                'closed_holidays' => 1,
                'created_at' => '2017-10-27 09:39:56',
                'updated_at' => '2017-10-27 09:39:56',
                'cloned_from' => 134,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            112 => 
            array (
                'id' => 140,
                'activity_id' => 88,
                'venue_id' => 56,
                'name' => 'Cricket Skills - Pitcher Park - Term 1 2018',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-10-30 13:56:29',
                'updated_at' => '2017-10-30 13:56:30',
                'cloned_from' => 131,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            113 => 
            array (
                'id' => 141,
                'activity_id' => 88,
                'venue_id' => 56,
                'name' => 'Cricket Skills - Pitcher Park',
                'auto_name' => 0,
                'disabled_dates' => '',
                'closed_holidays' => 0,
                'created_at' => '2017-10-30 13:57:40',
                'updated_at' => '2017-10-30 13:57:50',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            114 => 
            array (
                'id' => 142,
                'activity_id' => 91,
                'venue_id' => 58,
                'name' => 'Piano Lessons - Penny\'s Piano Lessons Headquarters - Term 3 2018',
                'auto_name' => 0,
                'disabled_dates' => '["19\\/02\\/2018"]',
                'closed_holidays' => 1,
                'created_at' => '2017-11-01 09:24:19',
                'updated_at' => '2017-11-01 09:24:19',
                'cloned_from' => 139,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            115 => 
            array (
                'id' => 143,
                'activity_id' => 91,
                'venue_id' => 58,
                'name' => 'Piano Lessons - Penny\'s Piano Lessons Headquarters - Term 4 2018',
                'auto_name' => 0,
                'disabled_dates' => '["19\\/02\\/2018"]',
                'closed_holidays' => 1,
                'created_at' => '2017-11-02 13:29:40',
                'updated_at' => '2017-11-02 13:29:40',
                'cloned_from' => 142,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            116 => 
            array (
                'id' => 144,
                'activity_id' => 92,
                'venue_id' => 58,
                'name' => 'Piano EOY Concert - Penny\'s Piano Lessons Headquarters',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-11-02 13:55:31',
                'updated_at' => '2017-11-02 13:56:29',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            117 => 
            array (
                'id' => 145,
                'activity_id' => 92,
                'venue_id' => 58,
                'name' => 'Piano EOY Concert - Penny\'s Piano Lessons Headquarters - Term 2 2018',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-11-02 13:59:53',
                'updated_at' => '2017-11-02 13:59:53',
                'cloned_from' => 138,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            118 => 
            array (
                'id' => 147,
                'activity_id' => 92,
                'venue_id' => 58,
                'name' => 'Piano EOY Concert - Penny\'s Piano Lessons Headquarters - Term 2 2018',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-11-02 14:02:10',
                'updated_at' => '2017-11-02 14:02:10',
                'cloned_from' => 144,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            119 => 
            array (
                'id' => 148,
                'activity_id' => 94,
                'venue_id' => 60,
                'name' => 'Test - Test Headquarters',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 0,
                'created_at' => '2017-11-02 14:56:33',
                'updated_at' => '2017-11-03 09:58:05',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
            120 => 
            array (
                'id' => 149,
                'activity_id' => 95,
                'venue_id' => 62,
                'name' => 'Ceramic Classes - Crafty Critters Headquarters',
                'auto_name' => 0,
                'disabled_dates' => '[]',
                'closed_holidays' => 1,
                'created_at' => '2017-11-03 12:37:57',
                'updated_at' => '2017-11-03 12:39:24',
                'cloned_from' => 0,
                'reenrolled' => 0,
                'is_cloning' => 0,
            ),
        ));
        
        
    }
}