<?php

use Illuminate\Database\Seeder;

class ActivitiesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('activities')->delete();
        
        \DB::table('activities')->insert(array (
            0 => 
            array (
                'id' => 86,
                'sub_cat_id' => 3,
                'name' => 'Piano Lessons',
                'slug' => 'piano-lessons',
                'user_id' => 60,
                'venue_id' => 54,
                'description' => '<p>Our piano teachers are qualified teachers, experienced in teaching both technique and enjoyment to your child. Lessons are either 45 minutes or 60 minutes long.</p>',
                'excerpt' => 'Piano is a great first instrument for your child to learn.  Within a handful of lessons your child will be able to play simple and delightful melodies.  Before long they will be entrancing their family and friends.',
                'rating' => '0.00',
                'type' => 'BOOKING',
                'gender' => 'B',
                'start_age' => 6,
                'end_age' => 18,
                'supervision' => '',
                'review_count' => 0,
                'status' => 'ENABLED',
                'wizard_progress' => '{"current_step":5,"current_sub_step":3,"current_wizard":"finalise","completed_wizards":["listing-details","timetable-booking"]}',
                'last_wizard_page' => NULL,
                'price' => '0.00',
                'extended_hours_available' => 0,
                'search_count' => 0,
                'created_at' => '2017-10-24 10:59:23',
                'updated_at' => '2017-10-24 12:12:13',
                'search_priority' => 0,
                'active_events' => 5,
                'total_events' => 10,
                'has_active_events' => 1,
            ),
            1 => 
            array (
                'id' => 87,
                'sub_cat_id' => 24,
                'name' => 'Test Partner listing',
                'slug' => 'test-partner-listing',
                'user_id' => 60,
                'venue_id' => 54,
                'description' => '<p>bla bla</p>',
                'excerpt' => 'bla bla',
                'rating' => '0.00',
                'type' => 'BOOKING',
                'gender' => 'B',
                'start_age' => 6,
                'end_age' => 18,
                'supervision' => '',
                'review_count' => 0,
                'status' => 'DRAFT_WIZARD',
                'wizard_progress' => '{"current_step":1,"current_sub_step":1,"current_wizard":"timetable-booking","completed_wizards":["listing-details"]}',
                'last_wizard_page' => NULL,
                'price' => '0.00',
                'extended_hours_available' => 0,
                'search_count' => 0,
                'created_at' => '2017-10-24 12:39:44',
                'updated_at' => '2017-10-25 09:39:08',
                'search_priority' => 0,
                'active_events' => 1,
                'total_events' => 1,
                'has_active_events' => 1,
            ),
            2 => 
            array (
                'id' => 88,
                'sub_cat_id' => 1,
                'name' => 'Cricket Skills',
                'slug' => 'cricket-skills',
                'user_id' => 61,
                'venue_id' => 56,
                'description' => '<p>We have beginner, intermediate and advanced sessions.</p>
<p>We will also be running school holiday programs each term.</p>',
                'excerpt' => 'This is cricket skill sessions',
                'rating' => '0.00',
                'type' => 'BOOKING',
                'gender' => 'B',
                'start_age' => 6,
                'end_age' => 15,
                'supervision' => '',
                'review_count' => 0,
                'status' => 'ENABLED',
                'wizard_progress' => '{"current_step":5,"current_sub_step":3,"current_wizard":"finalise","completed_wizards":["listing-details","timetable-booking"]}',
                'last_wizard_page' => NULL,
                'price' => '0.00',
                'extended_hours_available' => 0,
                'search_count' => 0,
                'created_at' => '2017-10-25 09:08:49',
                'updated_at' => '2017-10-25 09:21:47',
                'search_priority' => 0,
                'active_events' => 28,
                'total_events' => 30,
                'has_active_events' => 1,
            ),
            3 => 
            array (
                'id' => 89,
                'sub_cat_id' => 12,
                'name' => 'test',
                'slug' => 'test',
                'user_id' => 61,
                'venue_id' => 56,
                'description' => '<p>test</p>',
                'excerpt' => 'test',
                'rating' => '0.00',
                'type' => 'BOOKING',
                'gender' => 'B',
                'start_age' => 6,
                'end_age' => 18,
                'supervision' => '',
                'review_count' => 0,
                'status' => 'ENABLED',
                'wizard_progress' => '{"current_step":5,"current_sub_step":3,"current_wizard":"finalise","completed_wizards":["listing-details","timetable-booking"]}',
                'last_wizard_page' => NULL,
                'price' => '150.00',
                'extended_hours_available' => 0,
                'search_count' => 0,
                'created_at' => '2017-10-25 09:32:18',
                'updated_at' => '2017-10-25 09:36:35',
                'search_priority' => 0,
                'active_events' => 1,
                'total_events' => 1,
                'has_active_events' => 1,
            ),
            4 => 
            array (
                'id' => 90,
                'sub_cat_id' => 5,
                'name' => 'Sonny\'s Holiday Program',
                'slug' => 'sonnys-holiday-program',
                'user_id' => 64,
                'venue_id' => 57,
                'description' => '<p>bla bla</p>',
                'excerpt' => 'bla bla',
                'rating' => '0.00',
                'type' => 'BOOKING',
                'gender' => 'B',
                'start_age' => 6,
                'end_age' => 18,
                'supervision' => '',
                'review_count' => 0,
                'status' => 'ENABLED',
                'wizard_progress' => '{"current_step":5,"current_sub_step":3,"current_wizard":"finalise","completed_wizards":["listing-details","timetable-booking"]}',
                'last_wizard_page' => NULL,
                'price' => '75.00',
                'extended_hours_available' => 0,
                'search_count' => 0,
                'created_at' => '2017-10-25 12:01:18',
                'updated_at' => '2017-10-25 12:08:31',
                'search_priority' => 0,
                'active_events' => 20,
                'total_events' => 20,
                'has_active_events' => 1,
            ),
            5 => 
            array (
                'id' => 91,
                'sub_cat_id' => 3,
                'name' => 'Piano Lessons',
                'slug' => 'piano-lessons',
                'user_id' => 65,
                'venue_id' => 58,
                'description' => '<p>Join Penny for weekly lessons to learn how to play the piano.  Penny teachers theory, finger techniques and follows the AMEB curriculum to support your child to both enjoy and progress with their lessons.</p>',
                'excerpt' => 'Fun weekly lessons and regular practice will transform all students into great piano players who love creating beautiful music.',
                'rating' => '0.00',
                'type' => 'BOOKING',
                'gender' => 'B',
                'start_age' => 6,
                'end_age' => 18,
                'supervision' => '',
                'review_count' => 0,
                'status' => 'ENABLED',
                'wizard_progress' => '{"current_step":5,"current_sub_step":3,"current_wizard":"finalise","completed_wizards":["listing-details","timetable-booking"]}',
                'last_wizard_page' => NULL,
                'price' => '0.00',
                'extended_hours_available' => 0,
                'search_count' => 0,
                'created_at' => '2017-10-26 10:02:59',
                'updated_at' => '2017-10-31 09:33:04',
                'search_priority' => 0,
                'active_events' => 102,
                'total_events' => 102,
                'has_active_events' => 1,
            ),
            6 => 
            array (
                'id' => 92,
                'sub_cat_id' => 3,
                'name' => 'Piano EOY Concert',
                'slug' => 'piano-eoy-concert',
                'user_id' => 65,
                'venue_id' => 58,
                'description' => '<p>see kids playing piano</p>',
                'excerpt' => 'piano concert',
                'rating' => '0.00',
                'type' => 'BOOKING',
                'gender' => 'B',
                'start_age' => 6,
                'end_age' => 18,
                'supervision' => '',
                'review_count' => 0,
                'status' => 'ENABLED',
                'wizard_progress' => '{"current_step":5,"current_sub_step":3,"current_wizard":"finalise","completed_wizards":["listing-details","timetable-booking"]}',
                'last_wizard_page' => NULL,
                'price' => '10.00',
                'extended_hours_available' => 0,
                'search_count' => 0,
                'created_at' => '2017-10-26 13:33:09',
                'updated_at' => '2017-10-26 13:39:28',
                'search_priority' => 0,
                'active_events' => 84,
                'total_events' => 85,
                'has_active_events' => 1,
            ),
            7 => 
            array (
                'id' => 93,
                'sub_cat_id' => 5,
                'name' => 'Test partner listing',
                'slug' => 'test-partner-listing',
                'user_id' => 61,
                'venue_id' => 56,
                'description' => '<p>test</p>',
                'excerpt' => 'test',
                'rating' => '0.00',
                'type' => 'LISTING',
                'gender' => 'B',
                'start_age' => 6,
                'end_age' => 18,
                'supervision' => '',
                'review_count' => 0,
                'status' => 'ENABLED',
                'wizard_progress' => '{"current_step":5,"current_sub_step":3,"current_wizard":"finalise","completed_wizards":["listing-details"]}',
                'last_wizard_page' => 'Finalise and Publish - Test partner listing / Optional Add-On Service',
                'price' => '0.00',
                'extended_hours_available' => 0,
                'search_count' => 0,
                'created_at' => '2017-10-30 14:16:17',
                'updated_at' => '2017-10-30 14:18:13',
                'search_priority' => 0,
                'active_events' => 1,
                'total_events' => 1,
                'has_active_events' => 1,
            ),
            8 => 
            array (
                'id' => 94,
                'sub_cat_id' => 22,
                'name' => 'Test',
                'slug' => 'test',
                'user_id' => 71,
                'venue_id' => 60,
                'description' => '<p>test</p>',
                'excerpt' => 'test',
                'rating' => '0.00',
                'type' => 'BOOKING',
                'gender' => 'B',
                'start_age' => 6,
                'end_age' => 18,
                'supervision' => '',
                'review_count' => 0,
                'status' => 'ENABLED',
                'wizard_progress' => '{"current_step":5,"current_sub_step":3,"current_wizard":"finalise","completed_wizards":["listing-details","timetable-booking"]}',
                'last_wizard_page' => 'Finalise and Publish - Test / Payments',
                'price' => '0.00',
                'extended_hours_available' => 0,
                'search_count' => 0,
                'created_at' => '2017-11-02 14:55:50',
                'updated_at' => '2017-11-03 09:59:14',
                'search_priority' => 0,
                'active_events' => 10,
                'total_events' => 10,
                'has_active_events' => 1,
            ),
            9 => 
            array (
                'id' => 95,
                'sub_cat_id' => 2,
                'name' => 'Ceramic Classes',
                'slug' => 'ceramic-classes',
                'user_id' => 75,
                'venue_id' => 62,
                'description' => '<p>Learn how to creat ceramic and clay creations using a range of methods.  You then paint and fire them.  Great for kids over 6 years old.</p>',
                'excerpt' => 'Ceramic classes are fun - sculpt paint and fire unique creations',
                'rating' => '0.00',
                'type' => 'Workz',
                'gender' => 'B',
                'start_age' => 6,
                'end_age' => 18,
                'supervision' => '',
                'review_count' => 0,
                'status' => 'ENABLED',
                'wizard_progress' => '{"current_step":5,"current_sub_step":3,"current_wizard":"finalise","completed_wizards":["listing-details","timetable-booking"]}',
                'last_wizard_page' => 'Finalise and Publish - Ceramic Classes / Complete',
                'price' => '1.00',
                'extended_hours_available' => 0,
                'search_count' => 0,
                'created_at' => '2017-11-03 12:34:43',
                'updated_at' => '2017-11-03 12:58:08',
                'search_priority' => 0,
                'active_events' => 99,
                'total_events' => 99,
                'has_active_events' => 1,
            ),
            10 => 
            array (
                'id' => 96,
                'sub_cat_id' => 2,
                'name' => 'Crafty Fun Test Partner Add',
                'slug' => 'crafty-fun-test-partner-add',
                'user_id' => 75,
                'venue_id' => 62,
                'description' => '<p>lots and lots of fun</p>',
                'excerpt' => 'All sorts of crafty fun',
                'rating' => '0.00',
                'type' => 'LISTING',
                'gender' => 'B',
                'start_age' => 6,
                'end_age' => 18,
                'supervision' => '',
                'review_count' => 0,
                'status' => 'ENABLED',
                'wizard_progress' => '{"current_step":5,"current_sub_step":3,"current_wizard":"finalise","completed_wizards":["listing-details"]}',
                'last_wizard_page' => 'Finalise and Publish - Crafty Fun Test / Optional Add-On Service',
                'price' => '0.00',
                'extended_hours_available' => 0,
                'search_count' => 0,
                'created_at' => '2017-11-03 12:53:49',
                'updated_at' => '2017-11-03 13:58:19',
                'search_priority' => 0,
                'active_events' => 2,
                'total_events' => 2,
                'has_active_events' => 1,
            ),
        ));
        
        
    }
}