<?php

use Illuminate\Database\Seeder;

class ActivityPackageTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('activity_package')->delete();
        
        \DB::table('activity_package')->insert(array (
            0 => 
            array (
                'id' => 105,
                'activity_id' => 47,
                'name' => 'Monday 5-6pm private | Rachel\'s Music Hall | Term 4',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '2',
                'created_at' => '2017-09-13 10:43:14',
                'updated_at' => '2017-09-13 10:43:14',
                'deleted_at' => NULL,
                'is_pro_rata' => 1,
                'pro_rata_price' => '0.00',
                'calendar_id' => 78,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            1 => 
            array (
                'id' => 106,
                'activity_id' => 47,
                'name' => 'Tuesday 5-6pm private | Rachel\'s Music Hall | Term 4',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '1',
                'created_at' => '2017-09-13 10:45:03',
                'updated_at' => '2017-09-13 10:45:03',
                'deleted_at' => NULL,
                'is_pro_rata' => 1,
                'pro_rata_price' => '0.00',
                'calendar_id' => 78,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            2 => 
            array (
                'id' => 107,
                'activity_id' => 47,
                'name' => 'Wednesday Duet classes | Rachel\'s Music Hall | Term 4',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '1',
                'created_at' => '2017-09-13 13:27:10',
                'updated_at' => '2017-09-13 13:27:10',
                'deleted_at' => NULL,
                'is_pro_rata' => 0,
                'pro_rata_price' => '0.00',
                'calendar_id' => 78,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            3 => 
            array (
                'id' => 108,
                'activity_id' => 49,
                'name' => 'Monday | Kids activity providers Headquarters | 1st Week',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '2',
                'created_at' => '2017-09-14 09:32:24',
                'updated_at' => '2017-09-14 09:37:10',
                'deleted_at' => '2017-09-14 09:37:10',
                'is_pro_rata' => 1,
                'pro_rata_price' => '0.00',
                'calendar_id' => 79,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            4 => 
            array (
                'id' => 109,
                'activity_id' => 49,
                'name' => 'Monday | Kids activity providers Headquarters | Week one',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '1',
                'created_at' => '2017-09-14 09:38:46',
                'updated_at' => '2017-09-14 09:38:46',
                'deleted_at' => NULL,
                'is_pro_rata' => 1,
                'pro_rata_price' => '0.00',
                'calendar_id' => 79,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            5 => 
            array (
                'id' => 110,
                'activity_id' => 50,
                'name' => 'Newbies | Tennis Courts | Term 3 Holidays',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '2',
                'created_at' => '2017-09-14 10:02:35',
                'updated_at' => '2017-09-14 10:02:35',
                'deleted_at' => NULL,
                'is_pro_rata' => 0,
                'pro_rata_price' => '0.00',
                'calendar_id' => 80,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            6 => 
            array (
                'id' => 111,
                'activity_id' => 50,
                'name' => 'Beginners | Tennis Courts | Term 3 Holidays',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '1',
                'created_at' => '2017-09-14 10:03:24',
                'updated_at' => '2017-09-14 10:03:24',
                'deleted_at' => NULL,
                'is_pro_rata' => 0,
                'pro_rata_price' => '0.00',
                'calendar_id' => 80,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            7 => 
            array (
                'id' => 112,
                'activity_id' => 50,
                'name' => 'Advanced | Tennis Courts | Term 3 Holidays',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '1',
                'created_at' => '2017-09-14 10:04:01',
                'updated_at' => '2017-09-14 10:04:01',
                'deleted_at' => NULL,
                'is_pro_rata' => 1,
                'pro_rata_price' => '0.00',
                'calendar_id' => 80,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            8 => 
            array (
                'id' => 113,
                'activity_id' => 50,
                'name' => 'Super Advanced | Tennis Courts | Term 3 Holidays',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '1',
                'created_at' => '2017-09-14 10:04:34',
                'updated_at' => '2017-09-14 10:04:34',
                'deleted_at' => NULL,
                'is_pro_rata' => 0,
                'pro_rata_price' => '0.00',
                'calendar_id' => 80,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            9 => 
            array (
                'id' => 114,
                'activity_id' => 51,
                'name' => 'One | Kids activity providers Headquarters | 1st Week',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '2',
                'created_at' => '2017-09-14 10:38:23',
                'updated_at' => '2017-09-14 10:38:23',
                'deleted_at' => NULL,
                'is_pro_rata' => 1,
                'pro_rata_price' => '0.00',
                'calendar_id' => 81,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            10 => 
            array (
                'id' => 115,
                'activity_id' => 47,
                'name' => 'Friday toddler class | Rachel\'s Music Hall | Term 4',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '1',
                'created_at' => '2017-09-14 12:17:52',
                'updated_at' => '2017-09-14 12:17:52',
                'deleted_at' => NULL,
                'is_pro_rata' => 1,
                'pro_rata_price' => '0.00',
                'calendar_id' => 78,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            11 => 
            array (
                'id' => 116,
                'activity_id' => 48,
                'name' => 'Keyboard beginners Monday 9-10 | Rachel\'s Music Hall | Term 4',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '2',
                'created_at' => '2017-09-14 12:23:10',
                'updated_at' => '2017-09-14 12:23:10',
                'deleted_at' => NULL,
                'is_pro_rata' => 1,
                'pro_rata_price' => '0.00',
                'calendar_id' => 82,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            12 => 
            array (
                'id' => 117,
                'activity_id' => 53,
                'name' => 'Baking cakes | Cooking Company Headquarters | Term 4',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '2',
                'created_at' => '2017-09-15 12:26:28',
                'updated_at' => '2017-09-15 12:26:28',
                'deleted_at' => NULL,
                'is_pro_rata' => 1,
                'pro_rata_price' => '0.00',
                'calendar_id' => 84,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            13 => 
            array (
                'id' => 118,
                'activity_id' => 53,
                'name' => 'Delicious Roasts | Cooking Company Headquarters | Term 4',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '1',
                'created_at' => '2017-09-15 12:26:58',
                'updated_at' => '2017-09-15 12:26:58',
                'deleted_at' => NULL,
                'is_pro_rata' => 1,
                'pro_rata_price' => '0.00',
                'calendar_id' => 84,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            14 => 
            array (
                'id' => 119,
                'activity_id' => 53,
                'name' => 'private lesson | Cooking Company Headquarters | Term 4',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '1',
                'created_at' => '2017-09-19 08:46:12',
                'updated_at' => '2017-09-19 08:46:12',
                'deleted_at' => NULL,
                'is_pro_rata' => 1,
                'pro_rata_price' => '0.00',
                'calendar_id' => 84,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            15 => 
            array (
                'id' => 120,
                'activity_id' => 53,
                'name' => 'Baking cakes | Cooking Company Headquarters | Term 1 2018',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '2',
                'created_at' => '2017-09-19 09:36:24',
                'updated_at' => '2017-09-19 09:36:24',
                'deleted_at' => NULL,
                'is_pro_rata' => 1,
                'pro_rata_price' => '0.00',
                'calendar_id' => 85,
                'price_id' => 0,
                'cloned_from' => 117,
            ),
            16 => 
            array (
                'id' => 121,
                'activity_id' => 53,
                'name' => 'Delicious Roasts | Cooking Company Headquarters | Term 1 2018',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '1',
                'created_at' => '2017-09-19 09:36:24',
                'updated_at' => '2017-09-19 09:36:24',
                'deleted_at' => NULL,
                'is_pro_rata' => 1,
                'pro_rata_price' => '0.00',
                'calendar_id' => 85,
                'price_id' => 0,
                'cloned_from' => 118,
            ),
            17 => 
            array (
                'id' => 122,
                'activity_id' => 53,
                'name' => 'private lesson | Cooking Company Headquarters | Term 1 2018',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '1',
                'created_at' => '2017-09-19 09:36:25',
                'updated_at' => '2017-09-19 09:36:25',
                'deleted_at' => NULL,
                'is_pro_rata' => 1,
                'pro_rata_price' => '0.00',
                'calendar_id' => 85,
                'price_id' => 0,
                'cloned_from' => 119,
            ),
            18 => 
            array (
                'id' => 123,
                'activity_id' => 55,
                'name' => 'Junior ballet | Dance Academy Headquarters | Term 4 2018',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '2',
                'created_at' => '2017-09-19 13:35:16',
                'updated_at' => '2017-09-19 13:35:16',
                'deleted_at' => NULL,
                'is_pro_rata' => 1,
                'pro_rata_price' => '0.00',
                'calendar_id' => 87,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            19 => 
            array (
                'id' => 124,
                'activity_id' => 55,
                'name' => 'private jazz tuition | Dance Academy Headquarters | Term 4 2018',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '1',
                'created_at' => '2017-09-19 13:35:52',
                'updated_at' => '2017-09-19 13:35:52',
                'deleted_at' => NULL,
                'is_pro_rata' => 1,
                'pro_rata_price' => '0.00',
                'calendar_id' => 87,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            20 => 
            array (
                'id' => 126,
                'activity_id' => 49,
                'name' => 'Monday | Kids activity providers Headquarters | 1st Week',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '1',
                'created_at' => '2017-09-21 09:33:24',
                'updated_at' => '2017-09-21 09:33:24',
                'deleted_at' => NULL,
                'is_pro_rata' => 1,
                'pro_rata_price' => '0.00',
                'calendar_id' => 91,
                'price_id' => 0,
                'cloned_from' => 109,
            ),
            21 => 
            array (
                'id' => 127,
                'activity_id' => 49,
                'name' => 'Monday | Kids activity providers Headquarters | 1st Week',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '1',
                'created_at' => '2017-09-21 09:44:50',
                'updated_at' => '2017-09-21 09:44:50',
                'deleted_at' => NULL,
                'is_pro_rata' => 1,
                'pro_rata_price' => '0.00',
                'calendar_id' => 92,
                'price_id' => 0,
                'cloned_from' => 126,
            ),
            22 => 
            array (
                'id' => 128,
                'activity_id' => 49,
                'name' => 'Monday | Kids activity providers Headquarters | 1st Week',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '1',
                'created_at' => '2017-09-21 11:13:09',
                'updated_at' => '2017-09-21 11:13:09',
                'deleted_at' => NULL,
                'is_pro_rata' => 1,
                'pro_rata_price' => '0.00',
                'calendar_id' => 93,
                'price_id' => 0,
                'cloned_from' => 126,
            ),
            23 => 
            array (
                'id' => 129,
                'activity_id' => 49,
                'name' => 'Monday | Kids activity providers Headquarters | 1st Week',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '1',
                'created_at' => '2017-09-21 11:13:09',
                'updated_at' => '2017-09-21 11:13:09',
                'deleted_at' => NULL,
                'is_pro_rata' => 1,
                'pro_rata_price' => '0.00',
                'calendar_id' => 94,
                'price_id' => 0,
                'cloned_from' => 127,
            ),
            24 => 
            array (
                'id' => 134,
                'activity_id' => 61,
                'name' => 'Cricket Camp Week 2 | Pitcher Park Alphington | Term 3 School Holidays Week 2',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '1',
                'created_at' => '2017-09-21 15:24:00',
                'updated_at' => '2017-09-21 15:24:00',
                'deleted_at' => NULL,
                'is_pro_rata' => 0,
                'pro_rata_price' => '0.00',
                'calendar_id' => 96,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            25 => 
            array (
                'id' => 135,
                'activity_id' => 61,
                'name' => 'Cricket Camp Week 1 | Pitcher Park Alphington | Term 3 Holidays Week 1',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '1',
                'created_at' => '2017-09-21 15:30:47',
                'updated_at' => '2017-09-21 15:30:47',
                'deleted_at' => NULL,
                'is_pro_rata' => 0,
                'pro_rata_price' => '0.00',
                'calendar_id' => 95,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            26 => 
            array (
                'id' => 136,
                'activity_id' => 61,
                'name' => 'Cricket Skills Clinic | Pitcher Park Alphington | Term 3',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '1',
                'created_at' => '2017-09-21 15:35:16',
                'updated_at' => '2017-09-21 15:35:16',
                'deleted_at' => NULL,
                'is_pro_rata' => 0,
                'pro_rata_price' => '0.00',
                'calendar_id' => 97,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            27 => 
            array (
                'id' => 138,
                'activity_id' => 58,
                'name' => 'Music Day Program | Rachel\'s Music Hall | Week 1 EOY holidays',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '1',
                'created_at' => '2017-09-25 08:10:49',
                'updated_at' => '2017-09-25 08:10:49',
                'deleted_at' => NULL,
                'is_pro_rata' => 0,
                'pro_rata_price' => '0.00',
                'calendar_id' => 90,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            28 => 
            array (
                'id' => 139,
                'activity_id' => 58,
                'name' => 'Music Day Program | Rachel\'s Music Hall | EOY holidays Jan 8-12',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '1',
                'created_at' => '2017-09-25 08:16:08',
                'updated_at' => '2017-09-25 08:16:08',
                'deleted_at' => NULL,
                'is_pro_rata' => 0,
                'pro_rata_price' => '0.00',
                'calendar_id' => 101,
                'price_id' => 0,
                'cloned_from' => 138,
            ),
            29 => 
            array (
                'id' => 140,
                'activity_id' => 61,
                'name' => 'Another camp for week 2 | Pitcher Park Alphington | Term 3 School Holidays Week 2',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '1',
                'created_at' => '2017-09-25 15:32:23',
                'updated_at' => '2017-09-25 15:32:23',
                'deleted_at' => NULL,
                'is_pro_rata' => 0,
                'pro_rata_price' => '0.00',
                'calendar_id' => 102,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            30 => 
            array (
                'id' => 141,
                'activity_id' => 61,
                'name' => 'Advanced Cricket Skills | Pitcher Park Alphington | Term 3',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '1',
                'created_at' => '2017-09-26 09:54:02',
                'updated_at' => '2017-09-26 09:54:02',
                'deleted_at' => NULL,
                'is_pro_rata' => 0,
                'pro_rata_price' => '0.00',
                'calendar_id' => 103,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            31 => 
            array (
                'id' => 143,
                'activity_id' => 66,
                'name' => 'dsjhei | Victorian State cheerleaders | Saturday Training',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '1',
                'created_at' => '2017-09-27 10:57:59',
                'updated_at' => '2017-09-27 10:57:59',
                'deleted_at' => NULL,
                'is_pro_rata' => 0,
                'pro_rata_price' => '0.00',
                'calendar_id' => 104,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            32 => 
            array (
                'id' => 144,
                'activity_id' => 66,
                'name' => 'weekly cheer saturday | Victorian State cheerleaders | Saturday Training',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '1',
                'created_at' => '2017-09-27 10:58:50',
                'updated_at' => '2017-09-27 10:58:50',
                'deleted_at' => NULL,
                'is_pro_rata' => 0,
                'pro_rata_price' => '0.00',
                'calendar_id' => 104,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            33 => 
            array (
                'id' => 145,
                'activity_id' => 67,
                'name' => 'Junior Tap | Dance Academy Headquarters | Term 4 2018',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '2',
                'created_at' => '2017-09-27 11:21:00',
                'updated_at' => '2017-09-27 11:21:00',
                'deleted_at' => NULL,
                'is_pro_rata' => 0,
                'pro_rata_price' => '0.00',
                'calendar_id' => 105,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            34 => 
            array (
                'id' => 146,
                'activity_id' => 67,
                'name' => 'Mixed Tap | Dance Academy Headquarters | Term 4 2018',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '1',
                'created_at' => '2017-09-27 11:21:40',
                'updated_at' => '2017-09-27 11:21:40',
                'deleted_at' => NULL,
                'is_pro_rata' => 0,
                'pro_rata_price' => '0.00',
                'calendar_id' => 105,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            35 => 
            array (
                'id' => 147,
                'activity_id' => 67,
                'name' => 'Private Tap Tuition | Dance Academy Headquarters | Term 4 2018',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '1',
                'created_at' => '2017-09-27 11:22:11',
                'updated_at' => '2017-09-27 11:22:11',
                'deleted_at' => NULL,
                'is_pro_rata' => 0,
                'pro_rata_price' => '0.00',
                'calendar_id' => 105,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            36 => 
            array (
                'id' => 148,
                'activity_id' => 67,
                'name' => 'Tap Practice Sessions | Dance Academy Headquarters | Term 4 2018',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '1',
                'created_at' => '2017-09-27 11:22:47',
                'updated_at' => '2017-09-27 11:22:47',
                'deleted_at' => NULL,
                'is_pro_rata' => 1,
                'pro_rata_price' => '0.00',
                'calendar_id' => 105,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            37 => 
            array (
                'id' => 149,
                'activity_id' => 61,
                'name' => 'Beginners cricket skills | Pitcher Park Alphington | Term 3',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '1',
                'created_at' => '2017-09-27 13:29:37',
                'updated_at' => '2017-09-27 13:29:37',
                'deleted_at' => NULL,
                'is_pro_rata' => 0,
                'pro_rata_price' => '0.00',
                'calendar_id' => 103,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            38 => 
            array (
                'id' => 150,
                'activity_id' => 61,
                'name' => 'Christmas Cricket Camp Week 2 | Pitcher Park Alphington | Christmas  Holidays',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '1',
                'created_at' => '2017-09-27 13:32:57',
                'updated_at' => '2017-09-27 13:32:57',
                'deleted_at' => NULL,
                'is_pro_rata' => 0,
                'pro_rata_price' => '0.00',
                'calendar_id' => 107,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            39 => 
            array (
                'id' => 151,
                'activity_id' => 67,
                'name' => 'Junior Tap | Dance Academy Headquarters | Term 1 2018',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '2',
                'created_at' => '2017-09-27 13:52:45',
                'updated_at' => '2017-09-27 13:52:45',
                'deleted_at' => NULL,
                'is_pro_rata' => 0,
                'pro_rata_price' => '0.00',
                'calendar_id' => 108,
                'price_id' => 0,
                'cloned_from' => 145,
            ),
            40 => 
            array (
                'id' => 152,
                'activity_id' => 67,
                'name' => 'Mixed Tap | Dance Academy Headquarters | Term 1 2018',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '1',
                'created_at' => '2017-09-27 13:52:45',
                'updated_at' => '2017-09-27 13:52:45',
                'deleted_at' => NULL,
                'is_pro_rata' => 0,
                'pro_rata_price' => '0.00',
                'calendar_id' => 108,
                'price_id' => 0,
                'cloned_from' => 146,
            ),
            41 => 
            array (
                'id' => 153,
                'activity_id' => 67,
                'name' => 'Private Tap Tuition | Dance Academy Headquarters | Term 1 2018',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '1',
                'created_at' => '2017-09-27 13:52:45',
                'updated_at' => '2017-09-27 13:52:45',
                'deleted_at' => NULL,
                'is_pro_rata' => 0,
                'pro_rata_price' => '0.00',
                'calendar_id' => 108,
                'price_id' => 0,
                'cloned_from' => 147,
            ),
            42 => 
            array (
                'id' => 160,
                'activity_id' => 71,
                'name' => 'Daily holiday programme 1 | Apple Activities HQ | Summer Holiday Programme',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '2',
                'created_at' => '2017-09-29 07:24:15',
                'updated_at' => '2017-09-29 07:24:15',
                'deleted_at' => NULL,
                'is_pro_rata' => 1,
                'pro_rata_price' => '0.00',
                'calendar_id' => 111,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            43 => 
            array (
                'id' => 161,
                'activity_id' => 48,
                'name' => 'Keyboard for beginners | Rachel\'s Music Hall | Term 4',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '1',
                'created_at' => '2017-09-29 08:08:37',
                'updated_at' => '2017-09-29 08:08:37',
                'deleted_at' => NULL,
                'is_pro_rata' => 0,
                'pro_rata_price' => '0.00',
                'calendar_id' => 82,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            44 => 
            array (
                'id' => 162,
                'activity_id' => 71,
                'name' => 'Weekly Classes | Apple Activities HQ | Summer Holiday Programme',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '1',
                'created_at' => '2017-10-01 12:17:11',
                'updated_at' => '2017-10-01 12:17:11',
                'deleted_at' => NULL,
                'is_pro_rata' => 1,
                'pro_rata_price' => '0.00',
                'calendar_id' => 111,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            45 => 
            array (
                'id' => 163,
                'activity_id' => 74,
                'name' => 'Daily classes | Apple Activities HQ | Summer Holiday Programme',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '2',
                'created_at' => '2017-10-01 12:24:48',
                'updated_at' => '2017-10-01 12:24:48',
                'deleted_at' => NULL,
                'is_pro_rata' => 1,
                'pro_rata_price' => '0.00',
                'calendar_id' => 112,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            46 => 
            array (
                'id' => 164,
                'activity_id' => 61,
                'name' => 'Intermediate Cricket skills | Pitcher Park Alphington | Term 4 2018',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '1',
                'created_at' => '2017-10-02 11:24:04',
                'updated_at' => '2017-10-02 11:24:04',
                'deleted_at' => NULL,
                'is_pro_rata' => 0,
                'pro_rata_price' => '0.00',
                'calendar_id' => 113,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            47 => 
            array (
                'id' => 165,
                'activity_id' => 61,
                'name' => 'Intermediate Cricket skills | Pitcher Park Alphington | Term 1 - 2018',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '1',
                'created_at' => '2017-10-02 11:27:14',
                'updated_at' => '2017-10-02 11:27:14',
                'deleted_at' => NULL,
                'is_pro_rata' => 0,
                'pro_rata_price' => '0.00',
                'calendar_id' => 114,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            48 => 
            array (
                'id' => 166,
                'activity_id' => 61,
                'name' => 'Intermediate Cricket Skills | Pitcher Park Alphington | Term 3',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '1',
                'created_at' => '2017-10-02 11:28:53',
                'updated_at' => '2017-10-02 11:28:53',
                'deleted_at' => NULL,
                'is_pro_rata' => 0,
                'pro_rata_price' => '0.00',
                'calendar_id' => 106,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            49 => 
            array (
                'id' => 167,
                'activity_id' => 75,
                'name' => 'Beginner Netball skills | Pitcher Park Alphington | Term 4 2018',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '2',
                'created_at' => '2017-10-02 11:34:20',
                'updated_at' => '2017-10-02 11:34:20',
                'deleted_at' => NULL,
                'is_pro_rata' => 0,
                'pro_rata_price' => '0.00',
                'calendar_id' => 115,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            50 => 
            array (
                'id' => 169,
                'activity_id' => 75,
                'name' => 'Netball beginner skills | Pitcher Park Alphington | Term 3',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '1',
                'created_at' => '2017-10-02 11:42:08',
                'updated_at' => '2017-10-02 11:42:08',
                'deleted_at' => NULL,
                'is_pro_rata' => 0,
                'pro_rata_price' => '0.00',
                'calendar_id' => 118,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            51 => 
            array (
                'id' => 170,
                'activity_id' => 75,
                'name' => 'Netball Advanced SKills | Pitcher Park Alphington | Term 4',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '1',
                'created_at' => '2017-10-02 11:42:45',
                'updated_at' => '2017-10-02 11:42:45',
                'deleted_at' => NULL,
                'is_pro_rata' => 0,
                'pro_rata_price' => '0.00',
                'calendar_id' => 118,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            52 => 
            array (
                'id' => 172,
                'activity_id' => 69,
                'name' => 'Extra Christmas Holiday Soccer camp | Pitcher Park Alphington | Christmas  Holidays ',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '2',
                'created_at' => '2017-10-06 13:13:22',
                'updated_at' => '2017-10-06 13:13:22',
                'deleted_at' => NULL,
                'is_pro_rata' => 0,
                'pro_rata_price' => '0.00',
                'calendar_id' => 109,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            53 => 
            array (
                'id' => 173,
                'activity_id' => 69,
                'name' => 'Extra New Christmas Holiday Soccer camp | Pitcher Park Alphington | Christmas  Holidays',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '2',
                'created_at' => '2017-10-06 13:16:48',
                'updated_at' => '2017-10-06 13:16:48',
                'deleted_at' => NULL,
                'is_pro_rata' => 0,
                'pro_rata_price' => '0.00',
                'calendar_id' => 109,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            54 => 
            array (
                'id' => 174,
                'activity_id' => 69,
                'name' => 'Super Duper soccer Skills clinic | Pitcher Park Alphington | Christmas  Holidays',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '1',
                'created_at' => '2017-10-06 13:18:51',
                'updated_at' => '2017-10-06 13:18:51',
                'deleted_at' => NULL,
                'is_pro_rata' => 0,
                'pro_rata_price' => '0.00',
                'calendar_id' => 109,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            55 => 
            array (
                'id' => 175,
                'activity_id' => 69,
                'name' => 'Special Soccer Camp | Pitcher Park Alphington',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '1',
                'created_at' => '2017-10-06 13:23:21',
                'updated_at' => '2017-10-06 13:23:21',
                'deleted_at' => NULL,
                'is_pro_rata' => 0,
                'pro_rata_price' => '0.00',
                'calendar_id' => 109,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            56 => 
            array (
                'id' => 176,
                'activity_id' => 69,
                'name' => 'I don\'t know | Pitcher Park Alphington | Christmas  Holidays',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '1',
                'created_at' => '2017-10-06 13:29:25',
                'updated_at' => '2017-10-06 13:29:25',
                'deleted_at' => NULL,
                'is_pro_rata' => 0,
                'pro_rata_price' => '0.00',
                'calendar_id' => 109,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            57 => 
            array (
                'id' => 177,
                'activity_id' => 48,
                'name' => 'Keyboard for beginners | Rachel\'s Music Hall | Term 4 - CLONE - CHANGE ME',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '1',
                'created_at' => '2017-10-10 08:45:45',
                'updated_at' => '2017-10-10 08:45:45',
                'deleted_at' => NULL,
                'is_pro_rata' => 0,
                'pro_rata_price' => '0.00',
                'calendar_id' => 82,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            58 => 
            array (
                'id' => 178,
                'activity_id' => 48,
                'name' => 'Private keyboard class - Monday | Rachel\'s Music Hall | Term 4',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '1',
                'created_at' => '2017-10-10 08:53:07',
                'updated_at' => '2017-10-10 08:53:07',
                'deleted_at' => NULL,
                'is_pro_rata' => 1,
                'pro_rata_price' => '0.00',
                'calendar_id' => 82,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            59 => 
            array (
                'id' => 182,
                'activity_id' => 75,
                'name' => 'Netball Beginner Skills | Pitcher Park Alphington | Term 3 - 2018 - CLONE - CHANGE ME',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '1',
                'created_at' => '2017-10-10 13:44:55',
                'updated_at' => '2017-10-10 13:44:55',
                'deleted_at' => NULL,
                'is_pro_rata' => 0,
                'pro_rata_price' => '0.00',
                'calendar_id' => 116,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            60 => 
            array (
                'id' => 184,
                'activity_id' => 69,
                'name' => 'Test | Pitcher Park Alphington | Christmas  Holidays',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '1',
                'created_at' => '2017-10-10 13:51:27',
                'updated_at' => '2017-10-10 13:51:27',
                'deleted_at' => NULL,
                'is_pro_rata' => 0,
                'pro_rata_price' => '0.00',
                'calendar_id' => 109,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            61 => 
            array (
                'id' => 185,
                'activity_id' => 80,
                'name' => 'Monday theory class | Rachel\'s Music Hall | Term 4',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '2',
                'created_at' => '2017-10-11 09:20:19',
                'updated_at' => '2017-10-11 09:20:19',
                'deleted_at' => NULL,
                'is_pro_rata' => 1,
                'pro_rata_price' => '0.00',
                'calendar_id' => 121,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            62 => 
            array (
                'id' => 186,
                'activity_id' => 80,
                'name' => 'Tuesday Theory Class | Rachel\'s Music Hall | Term 4',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '1',
                'created_at' => '2017-10-11 09:28:29',
                'updated_at' => '2017-10-11 09:28:29',
                'deleted_at' => NULL,
                'is_pro_rata' => 1,
                'pro_rata_price' => '0.00',
                'calendar_id' => 121,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            63 => 
            array (
                'id' => 187,
                'activity_id' => 78,
                'name' => 'New timeslot | Pitcher Park Alphington | Term 1 - 2018',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '2',
                'created_at' => '2017-10-12 10:45:16',
                'updated_at' => '2017-10-12 10:45:16',
                'deleted_at' => NULL,
                'is_pro_rata' => 0,
                'pro_rata_price' => '0.00',
                'calendar_id' => 122,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            64 => 
            array (
                'id' => 188,
                'activity_id' => 78,
                'name' => 'New timeslot | Pitcher Park Alphington | Term 1 - 2018 - CLONE - CHANGE ME',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '2',
                'created_at' => '2017-10-12 13:42:56',
                'updated_at' => '2017-10-12 13:42:56',
                'deleted_at' => NULL,
                'is_pro_rata' => 0,
                'pro_rata_price' => '0.00',
                'calendar_id' => 122,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            65 => 
            array (
                'id' => 189,
                'activity_id' => 80,
                'name' => 'New Package name Required',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '1',
                'created_at' => '2017-10-16 07:58:52',
                'updated_at' => '2017-10-16 07:58:52',
                'deleted_at' => NULL,
                'is_pro_rata' => 1,
                'pro_rata_price' => '0.00',
                'calendar_id' => 121,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            66 => 
            array (
                'id' => 190,
                'activity_id' => 47,
                'name' => 'Monday 5-6pm private | Rachel\'s Music Hall | Term 1 2018',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '2',
                'created_at' => '2017-10-18 11:08:03',
                'updated_at' => '2017-10-18 11:08:03',
                'deleted_at' => NULL,
                'is_pro_rata' => 1,
                'pro_rata_price' => '0.00',
                'calendar_id' => 124,
                'price_id' => 0,
                'cloned_from' => 105,
            ),
            67 => 
            array (
                'id' => 191,
                'activity_id' => 47,
                'name' => 'Tuesday 5-6pm private | Rachel\'s Music Hall | Term 1 2018',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '1',
                'created_at' => '2017-10-18 11:08:03',
                'updated_at' => '2017-10-18 11:08:03',
                'deleted_at' => NULL,
                'is_pro_rata' => 1,
                'pro_rata_price' => '0.00',
                'calendar_id' => 124,
                'price_id' => 0,
                'cloned_from' => 106,
            ),
            68 => 
            array (
                'id' => 192,
                'activity_id' => 47,
                'name' => 'Wednesday Duet classes | Rachel\'s Music Hall | Term 1 2018',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '1',
                'created_at' => '2017-10-18 11:08:03',
                'updated_at' => '2017-10-18 11:08:03',
                'deleted_at' => NULL,
                'is_pro_rata' => 0,
                'pro_rata_price' => '0.00',
                'calendar_id' => 124,
                'price_id' => 0,
                'cloned_from' => 107,
            ),
            69 => 
            array (
                'id' => 193,
                'activity_id' => 47,
                'name' => 'Friday toddler class | Rachel\'s Music Hall | Term 1 2018',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '1',
                'created_at' => '2017-10-18 11:08:03',
                'updated_at' => '2017-10-18 11:08:03',
                'deleted_at' => NULL,
                'is_pro_rata' => 1,
                'pro_rata_price' => '0.00',
                'calendar_id' => 124,
                'price_id' => 0,
                'cloned_from' => 115,
            ),
            70 => 
            array (
                'id' => 194,
                'activity_id' => 80,
                'name' => 'Monday theory class | Rachel\'s Music Hall | Term 1 2018',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '2',
                'created_at' => '2017-10-19 10:43:26',
                'updated_at' => '2017-10-19 10:43:26',
                'deleted_at' => NULL,
                'is_pro_rata' => 1,
                'pro_rata_price' => '0.00',
                'calendar_id' => 125,
                'price_id' => 0,
                'cloned_from' => 185,
            ),
            71 => 
            array (
                'id' => 195,
                'activity_id' => 80,
                'name' => 'Tuesday Theory Class | Rachel\'s Music Hall | Term 1 2018',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '1',
                'created_at' => '2017-10-19 10:43:26',
                'updated_at' => '2017-10-19 10:43:26',
                'deleted_at' => NULL,
                'is_pro_rata' => 1,
                'pro_rata_price' => '0.00',
                'calendar_id' => 125,
                'price_id' => 0,
                'cloned_from' => 186,
            ),
            72 => 
            array (
                'id' => 196,
                'activity_id' => 80,
                'name' => 'New Package name Required',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '1',
                'created_at' => '2017-10-19 10:43:26',
                'updated_at' => '2017-10-19 10:43:26',
                'deleted_at' => NULL,
                'is_pro_rata' => 1,
                'pro_rata_price' => '0.00',
                'calendar_id' => 125,
                'price_id' => 0,
                'cloned_from' => 189,
            ),
            73 => 
            array (
                'id' => 197,
                'activity_id' => 58,
                'name' => 'Music Day Program | Rachel\'s Music Hall | Summer Holidays 2018',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '1',
                'created_at' => '2017-10-19 11:05:14',
                'updated_at' => '2017-10-19 11:05:14',
                'deleted_at' => NULL,
                'is_pro_rata' => 0,
                'pro_rata_price' => '0.00',
                'calendar_id' => 126,
                'price_id' => 0,
                'cloned_from' => 138,
            ),
            74 => 
            array (
                'id' => 198,
                'activity_id' => 69,
                'name' => 'New Package name Required',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '2',
                'created_at' => '2017-10-19 11:21:40',
                'updated_at' => '2017-10-19 11:21:40',
                'deleted_at' => NULL,
                'is_pro_rata' => 0,
                'pro_rata_price' => '0.00',
                'calendar_id' => 109,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            75 => 
            array (
                'id' => 199,
                'activity_id' => 80,
                'name' => 'test | Rachel\'s Music Hall | Term 4',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '1',
                'created_at' => '2017-10-19 11:52:13',
                'updated_at' => '2017-10-19 11:52:13',
                'deleted_at' => NULL,
                'is_pro_rata' => 0,
                'pro_rata_price' => '0.00',
                'calendar_id' => 121,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            76 => 
            array (
                'id' => 200,
                'activity_id' => 80,
                'name' => 'test 2 | Rachel\'s Music Hall | Term 4',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '1',
                'created_at' => '2017-10-19 11:52:39',
                'updated_at' => '2017-10-19 11:52:39',
                'deleted_at' => NULL,
                'is_pro_rata' => 0,
                'pro_rata_price' => '0.00',
                'calendar_id' => 121,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            77 => 
            array (
                'id' => 202,
                'activity_id' => 86,
                'name' => 'Monday Private Class | Magic Music Lessons Headquarters | Term 4 2017',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '2',
                'created_at' => '2017-10-24 11:58:45',
                'updated_at' => '2017-10-24 11:58:45',
                'deleted_at' => NULL,
                'is_pro_rata' => 0,
                'pro_rata_price' => '0.00',
                'calendar_id' => 130,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            78 => 
            array (
                'id' => 203,
                'activity_id' => 88,
                'name' => 'Beginners Cricket Skills | Pitcher Park | Term 1 2018',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '2',
                'created_at' => '2017-10-25 09:13:06',
                'updated_at' => '2017-10-25 09:13:06',
                'deleted_at' => NULL,
                'is_pro_rata' => 0,
                'pro_rata_price' => '0.00',
                'calendar_id' => 131,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            79 => 
            array (
                'id' => 204,
                'activity_id' => 91,
                'name' => 'Monday 5 - 6pm | Penny\'s Piano Lessons Headquarters | Term 1 2018',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '2',
                'created_at' => '2017-10-26 12:48:15',
                'updated_at' => '2017-10-26 12:48:15',
                'deleted_at' => NULL,
                'is_pro_rata' => 0,
                'pro_rata_price' => '0.00',
                'calendar_id' => 134,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            80 => 
            array (
                'id' => 205,
                'activity_id' => 91,
                'name' => 'Friday 5-6pm | Penny\'s Piano Lessons Headquarters | Term 1 2018',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '1',
                'created_at' => '2017-10-26 12:54:42',
                'updated_at' => '2017-10-26 12:54:42',
                'deleted_at' => NULL,
                'is_pro_rata' => 0,
                'pro_rata_price' => '0.00',
                'calendar_id' => 134,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            81 => 
            array (
                'id' => 206,
                'activity_id' => 91,
                'name' => 'Monday 5 - 6pm | Penny\'s Piano Lessons Headquarters | Term 2 2018',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '2',
                'created_at' => '2017-10-26 13:05:54',
                'updated_at' => '2017-10-26 13:05:54',
                'deleted_at' => NULL,
                'is_pro_rata' => 0,
                'pro_rata_price' => '0.00',
                'calendar_id' => 135,
                'price_id' => 0,
                'cloned_from' => 204,
            ),
            82 => 
            array (
                'id' => 207,
                'activity_id' => 91,
                'name' => 'Friday 5-6pm | Penny\'s Piano Lessons Headquarters | Term 2 2018',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '1',
                'created_at' => '2017-10-26 13:05:54',
                'updated_at' => '2017-10-26 13:05:54',
                'deleted_at' => NULL,
                'is_pro_rata' => 0,
                'pro_rata_price' => '0.00',
                'calendar_id' => 135,
                'price_id' => 0,
                'cloned_from' => 205,
            ),
            83 => 
            array (
                'id' => 208,
                'activity_id' => 91,
                'name' => 'Monday 5 - 6pm | Penny\'s Piano Lessons Headquarters | Term 2 2018',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '2',
                'created_at' => '2017-10-26 13:09:17',
                'updated_at' => '2017-10-26 13:09:17',
                'deleted_at' => NULL,
                'is_pro_rata' => 0,
                'pro_rata_price' => '0.00',
                'calendar_id' => 136,
                'price_id' => 0,
                'cloned_from' => 204,
            ),
            84 => 
            array (
                'id' => 209,
                'activity_id' => 91,
                'name' => 'Friday 5-6pm | Penny\'s Piano Lessons Headquarters | Term 2 2018',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '1',
                'created_at' => '2017-10-26 13:09:17',
                'updated_at' => '2017-10-26 13:09:17',
                'deleted_at' => NULL,
                'is_pro_rata' => 0,
                'pro_rata_price' => '0.00',
                'calendar_id' => 136,
                'price_id' => 0,
                'cloned_from' => 205,
            ),
            85 => 
            array (
                'id' => 210,
                'activity_id' => 91,
                'name' => 'Wednesday piano lesson | Penny\'s Piano Lessons Headquarters | Term 2 2018',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '1',
                'created_at' => '2017-10-26 13:29:41',
                'updated_at' => '2017-10-26 13:29:41',
                'deleted_at' => NULL,
                'is_pro_rata' => 0,
                'pro_rata_price' => '0.00',
                'calendar_id' => 137,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            86 => 
            array (
                'id' => 211,
                'activity_id' => 91,
                'name' => 'Monday 5 - 6pm | Penny\'s Piano Lessons Headquarters | Term 2 2018',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '2',
                'created_at' => '2017-10-27 09:39:56',
                'updated_at' => '2017-10-27 09:39:56',
                'deleted_at' => NULL,
                'is_pro_rata' => 0,
                'pro_rata_price' => '0.00',
                'calendar_id' => 139,
                'price_id' => 0,
                'cloned_from' => 204,
            ),
            87 => 
            array (
                'id' => 212,
                'activity_id' => 91,
                'name' => 'Friday 5-6pm | Penny\'s Piano Lessons Headquarters | Term 2 2018',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '1',
                'created_at' => '2017-10-27 09:39:56',
                'updated_at' => '2017-10-27 09:39:56',
                'deleted_at' => NULL,
                'is_pro_rata' => 0,
                'pro_rata_price' => '0.00',
                'calendar_id' => 139,
                'price_id' => 0,
                'cloned_from' => 205,
            ),
            88 => 
            array (
                'id' => 214,
                'activity_id' => 88,
                'name' => 'New Timeslot name | Pitcher Park | Term 1 2018',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '2',
                'created_at' => '2017-11-01 09:04:14',
                'updated_at' => '2017-11-01 09:04:14',
                'deleted_at' => NULL,
                'is_pro_rata' => 0,
                'pro_rata_price' => '0.00',
                'calendar_id' => 131,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            89 => 
            array (
                'id' => 215,
                'activity_id' => 88,
                'name' => 'Friday session | Pitcher Park | Term 1 2018',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '1',
                'created_at' => '2017-11-01 09:05:42',
                'updated_at' => '2017-11-01 09:05:42',
                'deleted_at' => NULL,
                'is_pro_rata' => 0,
                'pro_rata_price' => '0.00',
                'calendar_id' => 131,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            90 => 
            array (
                'id' => 216,
                'activity_id' => 91,
                'name' => 'Monday 5 - 6pm | Penny\'s Piano Lessons Headquarters | Term 3 2018',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '2',
                'created_at' => '2017-11-01 09:24:19',
                'updated_at' => '2017-11-01 09:24:19',
                'deleted_at' => NULL,
                'is_pro_rata' => 0,
                'pro_rata_price' => '0.00',
                'calendar_id' => 142,
                'price_id' => 0,
                'cloned_from' => 211,
            ),
            91 => 
            array (
                'id' => 217,
                'activity_id' => 91,
                'name' => 'Friday 5-6pm | Penny\'s Piano Lessons Headquarters | Term 3 2018',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '1',
                'created_at' => '2017-11-01 09:24:19',
                'updated_at' => '2017-11-01 09:24:19',
                'deleted_at' => NULL,
                'is_pro_rata' => 0,
                'pro_rata_price' => '0.00',
                'calendar_id' => 142,
                'price_id' => 0,
                'cloned_from' => 212,
            ),
            92 => 
            array (
                'id' => 218,
                'activity_id' => 91,
                'name' => 'Tuesday 5-6pm | Penny\'s Piano Lessons Headquarters | Term 2 2018',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '2',
                'created_at' => '2017-11-02 11:43:41',
                'updated_at' => '2017-11-02 11:43:41',
                'deleted_at' => NULL,
                'is_pro_rata' => 0,
                'pro_rata_price' => '0.00',
                'calendar_id' => 139,
                'price_id' => 0,
                'cloned_from' => 204,
            ),
            93 => 
            array (
                'id' => 219,
                'activity_id' => 91,
                'name' => 'Monday 5 - 6pm | Penny\'s Piano Lessons Headquarters | Term 4 2018',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '2',
                'created_at' => '2017-11-02 13:29:40',
                'updated_at' => '2017-11-02 13:29:40',
                'deleted_at' => NULL,
                'is_pro_rata' => 0,
                'pro_rata_price' => '0.00',
                'calendar_id' => 143,
                'price_id' => 0,
                'cloned_from' => 216,
            ),
            94 => 
            array (
                'id' => 220,
                'activity_id' => 91,
                'name' => 'Friday 5-6pm | Penny\'s Piano Lessons Headquarters | Term 4 2018',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '1',
                'created_at' => '2017-11-02 13:29:40',
                'updated_at' => '2017-11-02 13:29:40',
                'deleted_at' => NULL,
                'is_pro_rata' => 0,
                'pro_rata_price' => '0.00',
                'calendar_id' => 143,
                'price_id' => 0,
                'cloned_from' => 217,
            ),
            95 => 
            array (
                'id' => 221,
                'activity_id' => 94,
                'name' => 'Test | Test Headquarters | Term 1 2018',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '2',
                'created_at' => '2017-11-02 14:57:21',
                'updated_at' => '2017-11-02 14:57:21',
                'deleted_at' => NULL,
                'is_pro_rata' => 0,
                'pro_rata_price' => '0.00',
                'calendar_id' => 148,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
            96 => 
            array (
                'id' => 223,
                'activity_id' => 91,
                'name' => 'Wednesday Duet Classes 1 | Penny\'s Piano Lessons Headquarters | Term 1 2018',
                'package_per' => 'Package',
                'cost' => '0.00',
                'color' => '1',
                'created_at' => '2017-11-03 11:45:10',
                'updated_at' => '2017-11-03 11:45:10',
                'deleted_at' => NULL,
                'is_pro_rata' => 0,
                'pro_rata_price' => '0.00',
                'calendar_id' => 134,
                'price_id' => 0,
                'cloned_from' => NULL,
            ),
        ));
        
        
    }
}