<?php

use Illuminate\Database\Seeder;

class EnrolmentFieldTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('enrolment_field')->delete();
        
        \DB::table('enrolment_field')->insert(array (
            0 => 
            array (
                'id' => 1,
                'order' => 47,
                'is_default' => 1,
                'legacy' => 0,
                'name' => 'First Name',
                'meta' => '',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'text',
                'group_id' => 1,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'order' => 48,
                'is_default' => 1,
                'legacy' => 0,
                'name' => 'Last Name',
                'meta' => '',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'text',
                'group_id' => 1,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'order' => 58,
                'is_default' => 1,
                'legacy' => 0,
                'name' => 'Preferred Name',
                'meta' => '',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'text',
                'group_id' => 1,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'order' => 4,
                'is_default' => 1,
                'legacy' => 0,
                'name' => 'Date of Birth',
                'meta' => '',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'dob',
                'group_id' => 1,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'order' => 55,
                'is_default' => 1,
                'legacy' => 0,
                'name' => 'Gender',
                'meta' => '{"0":"Male","1":"Female"}',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'select',
                'group_id' => 1,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'order' => 49,
                'is_default' => 1,
                'legacy' => 0,
                'name' => 'Home Address',
                'meta' => '',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'address',
                'group_id' => 1,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'order' => 51,
                'is_default' => 1,
                'legacy' => 0,
            'name' => 'Telephone (Home)',
                'meta' => '',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'phone',
                'group_id' => 1,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'order' => 20,
                'is_default' => NULL,
                'legacy' => 0,
                'name' => 'Is the family a single parent family?',
                'meta' => '',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'yesno',
                'group_id' => 2,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'order' => 15,
                'is_default' => NULL,
                'legacy' => 0,
                'name' => 'Child\'s Sibling 1 - Name',
                'meta' => '',
                'comment' => 'Only select this if you are a registered CCB/CCR provider',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'text',
                'group_id' => 2,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'order' => 13,
                'is_default' => NULL,
                'legacy' => 0,
                'name' => 'Child\'s Sibling 1 - D.O.B.',
                'meta' => '',
                'comment' => 'Only select this if you are a registered CCB/CCR provider',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'dob',
                'group_id' => 2,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'order' => 14,
                'is_default' => NULL,
                'legacy' => 0,
                'name' => 'Child\'s Sibling 1 - Gender',
                'meta' => '{"0":"Male","1":"Female"}',
                'comment' => 'Only select this if you are a registered CCB/CCR provider',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'select',
                'group_id' => 2,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'order' => 19,
                'is_default' => NULL,
                'legacy' => 0,
                'name' => 'Have any custody or court orders been made regarding your child?',
                'meta' => '{"options":{"0":"Yes","1":"No"},"prompt":{"0":"Yes"}}',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'details_prompt',
                'group_id' => 2,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'order' => 9,
                'is_default' => NULL,
                'legacy' => 0,
                'name' => 'Is your child of Aboriginal, Torres Strait Island or Australian South Sea Island Origin?',
                'meta' => '',
                'comment' => 'Only select this if you are a registered CCB/CCR provider',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'yesno',
                'group_id' => 3,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'order' => 8,
                'is_default' => NULL,
                'legacy' => 0,
                'name' => 'Country of Birth',
                'meta' => '',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'text',
                'group_id' => 3,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'order' => 12,
                'is_default' => NULL,
                'legacy' => 0,
                'name' => 'Languages Spoken at Home',
                'meta' => '',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'text',
                'group_id' => 3,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'order' => 11,
                'is_default' => NULL,
                'legacy' => 0,
                'name' => 'Religious Background',
                'meta' => '"religions"',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'dropdown',
                'group_id' => 3,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'order' => NULL,
                'is_default' => NULL,
                'legacy' => 1,
                'name' => 'Please provide details of the festivals/cultural celebrations your family recognises and those which you do not wish your child to participate in.',
                'meta' => '',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'textarea',
                'group_id' => 3,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'order' => 62,
                'is_default' => NULL,
                'legacy' => 0,
                'name' => 'At the time of the activity, what school is the participant enrolled in?',
                'meta' => '',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'text',
                'group_id' => 4,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'order' => 63,
                'is_default' => NULL,
                'legacy' => 0,
                'name' => 'At the time of the activity, what year level is the participant in.',
                'meta' => '',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'text',
                'group_id' => 4,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'order' => 29,
                'is_default' => NULL,
                'legacy' => 0,
                'name' => 'Maternal and Child Health Centre',
                'meta' => '',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'text',
                'group_id' => 5,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'order' => 32,
                'is_default' => NULL,
                'legacy' => 0,
                'name' => 'Medical Practitioner\'s Name',
                'meta' => '',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'text',
                'group_id' => 5,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'order' => 31,
                'is_default' => NULL,
                'legacy' => 0,
                'name' => 'Medical Practitioner\'s Address',
                'meta' => '',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'textarea',
                'group_id' => 5,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'order' => 33,
                'is_default' => NULL,
                'legacy' => 0,
                'name' => 'Medical Practitioner\'s Telephone',
                'meta' => '',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'phone',
                'group_id' => 5,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'order' => 21,
                'is_default' => NULL,
                'legacy' => 0,
                'name' => 'Ambulance Subscription Number',
                'meta' => '',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'text',
                'group_id' => 5,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'order' => 35,
                'is_default' => NULL,
                'legacy' => 0,
                'name' => 'Medicare Number',
                'meta' => '',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'medicare_no',
                'group_id' => 5,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'order' => 30,
                'is_default' => NULL,
                'legacy' => 0,
                'name' => 'Medical or other condition that may impact the childs participation in the activity',
                'meta' => '{"options":["Yes","No"],"prompt":["Yes"]}',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'details_prompt',
                'group_id' => 5,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-06-29 13:22:12',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'order' => 28,
                'is_default' => NULL,
                'legacy' => 0,
                'name' => 'Has your child received all the recommended immunisations according to the NHMR?',
                'meta' => '{"options":{"0":"Yes","1":"No","2":"Exempt"},"prompt":{"0":"No","1":"Exempt"}}',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'details_prompt',
                'group_id' => 5,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'order' => 25,
                'is_default' => NULL,
                'legacy' => 0,
                'name' => 'Does your child require regular medication to be administered at the activity?',
                'meta' => '{"options":{"0":"Yes","1":"No"},"prompt":{"0":"Yes"}}',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'details_prompt',
                'group_id' => 5,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'order' => 23,
                'is_default' => 1,
                'legacy' => 0,
                'name' => 'Does your child have known allergies or sensitivity?',
                'meta' => '{"options":{"0":"Yes","1":"No"},"prompt":{"0":"Yes"}}',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'details_prompt',
                'group_id' => 5,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'order' => 26,
                'is_default' => NULL,
                'legacy' => 0,
                'name' => 'Has your child been diagnosed as at risk of Anaphylaxis?',
                'meta' => '{"options":{"0":"Yes","1":"No"},"prompt":{"0":"Yes"}}',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'details_prompt',
                'group_id' => 5,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'order' => 27,
                'is_default' => NULL,
                'legacy' => 0,
                'name' => 'Has your child been diagnosed with Asthma?',
                'meta' => '{"options":{"0":"Yes","1":"No"},"prompt":{"0":"Yes"}}',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'details_prompt',
                'group_id' => 5,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'order' => 24,
                'is_default' => NULL,
                'legacy' => 0,
                'name' => 'Does your child have specific dietary requirements or restrictions?',
                'meta' => '{"options":{"0":"Yes","1":"No"},"prompt":{"0":"Yes"}}',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'details_prompt',
                'group_id' => 5,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'order' => 22,
                'is_default' => NULL,
                'legacy' => 0,
                'name' => 'Does the participant have any additional or special needs?',
                'meta' => '{"options":{"0":"Yes","1":"No"},"prompt":{"0":"Yes"}}',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'details_prompt',
                'group_id' => 5,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'order' => NULL,
                'is_default' => NULL,
                'legacy' => 1,
                'name' => 'Is there any other information regarding your child’s health or cultural background that the staff should be aware of?',
                'meta' => '',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'textarea',
                'group_id' => 6,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'order' => 39,
                'is_default' => NULL,
                'legacy' => 0,
                'name' => 'I give permission for the participant to be photographed for the purpose of planning, observations and portfolios and for display purposes.',
                'meta' => '',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'yesno',
                'group_id' => 6,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'order' => 40,
                'is_default' => NULL,
                'legacy' => 0,
                'name' => 'I give permission for the participant to be photographed or filmed for the purpose of publicity and/or promotions.',
                'meta' => '',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'yesno',
                'group_id' => 6,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'order' => 41,
                'is_default' => NULL,
                'legacy' => 0,
                'name' => 'I give permission for staff to apply sunscreen to the participant.',
                'meta' => '',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'yesno',
                'group_id' => 6,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'order' => 44,
                'is_default' => NULL,
                'legacy' => 0,
            'name' => 'Centrelink Customer Reference Number (CRN) for CCB/CCR purposes',
                'meta' => '{"length":10}',
                'comment' => 'Only select this if you are a registered CCB/CCR provider',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'number',
                'group_id' => 6,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'order' => NULL,
                'is_default' => NULL,
                'legacy' => 1,
                'name' => 'My child enjoys eating',
                'meta' => '',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'textarea',
                'group_id' => 6,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'order' => NULL,
                'is_default' => NULL,
                'legacy' => 1,
                'name' => 'My child does not eat',
                'meta' => '',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'textarea',
                'group_id' => 6,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'order' => 38,
                'is_default' => NULL,
                'legacy' => 0,
                'name' => 'Favourite game or activity:',
                'meta' => '',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'textarea',
                'group_id' => 6,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'order' => 42,
                'is_default' => NULL,
                'legacy' => 0,
                'name' => 'Specific interests of the participant or anything else you would like to tell us.',
                'meta' => '',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'textarea',
                'group_id' => 6,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'order' => 43,
                'is_default' => NULL,
                'legacy' => 0,
                'name' => 'Upload recent photo of the participant',
                'meta' => '',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'file_upload',
                'group_id' => 6,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'order' => NULL,
                'is_default' => NULL,
                'legacy' => 0,
                'name' => 'Declaration - the above is true and correct',
                'meta' => '',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'checkbox',
                'group_id' => 6,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'order' => 37,
                'is_default' => NULL,
                'legacy' => 0,
                'name' => 'Comments',
                'meta' => '',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'textarea',
                'group_id' => 6,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'order' => 55,
                'is_default' => 1,
                'legacy' => 0,
                'name' => 'First Name',
                'meta' => '',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'text',
                'group_id' => 7,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'order' => 56,
                'is_default' => 1,
                'legacy' => 0,
                'name' => 'Last Name',
                'meta' => '',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'text',
                'group_id' => 7,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'order' => 36,
                'is_default' => NULL,
                'legacy' => 0,
            'name' => 'Centrelink Customer Reference Number (CRN) for CCB/CCR purposes',
                'meta' => '{"length":10}',
                'comment' => 'Only select this if you are a registered CCB/CCR provider',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'number',
                'group_id' => 7,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'order' => 54,
                'is_default' => 0,
                'legacy' => 0,
                'name' => 'Date of Birth',
                'meta' => '',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'date',
                'group_id' => 7,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'order' => 56,
                'is_default' => 0,
                'legacy' => 0,
                'name' => 'Gender',
                'meta' => '["Male","Female"]',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'select',
                'group_id' => 7,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'order' => 57,
                'is_default' => 0,
                'legacy' => 0,
                'name' => 'Home Address',
                'meta' => '',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'address',
                'group_id' => 7,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'order' => 59,
                'is_default' => 1,
                'legacy' => 0,
            'name' => 'Telephone (Home)',
                'meta' => '',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'phone',
                'group_id' => 7,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'order' => 52,
                'is_default' => 1,
                'legacy' => 0,
            'name' => 'Telephone (Mobile)',
                'meta' => '',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'phone',
                'group_id' => 7,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'order' => 53,
                'is_default' => 1,
                'legacy' => 0,
            'name' => 'Telephone (Work)',
                'meta' => '',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'phone',
                'group_id' => 7,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'order' => 46,
                'is_default' => 0,
                'legacy' => 0,
                'name' => 'Email',
                'meta' => '',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'email',
                'group_id' => 7,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'order' => 53,
                'is_default' => 1,
                'legacy' => 1,
                'name' => 'Occupation',
                'meta' => '',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'text',
                'group_id' => 7,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'order' => NULL,
                'is_default' => NULL,
                'legacy' => 1,
                'name' => 'Country of Birth',
                'meta' => '',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'text',
                'group_id' => 7,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'order' => NULL,
                'is_default' => NULL,
                'legacy' => 1,
                'name' => 'Main Language Spoken at Home',
                'meta' => '',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'text',
                'group_id' => 7,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'order' => 45,
                'is_default' => NULL,
                'legacy' => 0,
                'name' => 'Does the participant live with this parent / guardian',
                'meta' => '',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'yesno',
                'group_id' => 7,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'order' => 50,
                'is_default' => 1,
                'legacy' => 0,
                'name' => 'Relationship to participant',
                'meta' => '',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'text',
                'group_id' => 7,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'order' => NULL,
                'is_default' => NULL,
                'legacy' => 1,
                'name' => 'Comments',
                'meta' => '',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'textarea',
                'group_id' => 7,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'order' => 65,
                'is_default' => 1,
                'legacy' => 0,
                'name' => 'Emergency Contact Firstname',
                'meta' => '',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'text',
                'group_id' => 8,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'order' => 66,
                'is_default' => 1,
                'legacy' => 0,
                'name' => 'Emergency Contact Lastname',
                'meta' => '',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'text',
                'group_id' => 8,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            63 => 
            array (
                'id' => 64,
                'order' => 69,
                'is_default' => 1,
                'legacy' => 0,
                'name' => 'Emergency Contact Relationship to Participant',
                'meta' => '',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'text',
                'group_id' => 8,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            64 => 
            array (
                'id' => 65,
                'order' => 67,
                'is_default' => 1,
                'legacy' => 0,
                'name' => 'Emergency Contact Home / Work Phone',
                'meta' => '',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'phone',
                'group_id' => 8,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            65 => 
            array (
                'id' => 66,
                'order' => 68,
                'is_default' => 1,
                'legacy' => 0,
                'name' => 'Emergency Contact Mobile Phone',
                'meta' => '',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'phone',
                'group_id' => 8,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            66 => 
            array (
                'id' => 67,
                'order' => 64,
                'is_default' => NULL,
                'legacy' => 0,
                'name' => 'Emergency Contact Address',
                'meta' => '',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'address',
                'group_id' => 8,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            67 => 
            array (
                'id' => 68,
                'order' => 71,
                'is_default' => NULL,
                'legacy' => 0,
                'name' => 'Expected number of attendees',
                'meta' => '',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'number',
                'group_id' => 9,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            68 => 
            array (
                'id' => 69,
                'order' => 70,
                'is_default' => NULL,
                'legacy' => 0,
                'name' => 'Participant\'s interests and special requests',
                'meta' => '',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'textarea',
                'group_id' => 9,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            69 => 
            array (
                'id' => 70,
                'order' => 74,
                'is_default' => NULL,
                'legacy' => 0,
                'name' => 'Party Location',
                'meta' => '["Home","Out of Home"]',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'select',
                'group_id' => 10,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            70 => 
            array (
                'id' => 71,
                'order' => 72,
                'is_default' => NULL,
                'legacy' => 0,
                'name' => 'Address of Party',
                'meta' => '',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'address',
                'group_id' => 10,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            71 => 
            array (
                'id' => 72,
                'order' => 73,
                'is_default' => NULL,
                'legacy' => 0,
                'name' => 'Indoor or Outdoor Party',
                'meta' => '["Indoor","Outdoor"]',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'select',
                'group_id' => 10,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            72 => 
            array (
                'id' => 73,
                'order' => 76,
                'is_default' => NULL,
                'legacy' => 0,
                'name' => 'Provider Requirements',
                'meta' => '',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'textarea',
                'group_id' => 10,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            73 => 
            array (
                'id' => 74,
                'order' => 16,
                'is_default' => NULL,
                'legacy' => 0,
                'name' => 'Child\'s Sibling 2 - D.O.B.',
                'meta' => '',
                'comment' => 'Only select this if you are a registered CCB/CCR provider',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'dob',
                'group_id' => 2,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            74 => 
            array (
                'id' => 75,
                'order' => 17,
                'is_default' => NULL,
                'legacy' => 0,
                'name' => 'Child\'s Sibling 2 - Gender',
                'meta' => '{"0":"Male","1":"Female"}',
                'comment' => 'Only select this if you are a registered CCB/CCR provider',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'select',
                'group_id' => 2,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            75 => 
            array (
                'id' => 76,
                'order' => 18,
                'is_default' => NULL,
                'legacy' => 0,
                'name' => 'Child\'s Sibling 2 - Name',
                'meta' => '',
                'comment' => 'Only select this if you are a registered CCB/CCR provider',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'text',
                'group_id' => 2,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            76 => 
            array (
                'id' => 77,
                'order' => 34,
                'is_default' => 0,
                'legacy' => 0,
                'name' => 'Where the facilitator in charge of the activity is unable to contact me, or it is otherwise impracticable to contact me, I: <br>* authorise the facilitator in charge to administer such first-aid as s/he may judge to be reasonably necessary. <br>* consent to my child receiving such medical or surgical treatment as may be deemed necessary by a medical practitioner. I will bear the cost of this treatment. <br>* consent to my child being transported to medical assistance in a private vehicle driven by a member of staff. <br>',
                'meta' => '',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'yesno',
                'group_id' => 5,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
                'deleted_at' => NULL,
            ),
            77 => 
            array (
                'id' => 78,
                'order' => 60,
                'is_default' => 1,
                'legacy' => 0,
            'name' => 'Telephone (Mobile)',
                'meta' => '',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'phone',
                'group_id' => 1,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            78 => 
            array (
                'id' => 80,
                'order' => 76,
                'is_default' => NULL,
                'legacy' => 0,
                'name' => 'Type of Party Booked',
                'meta' => '',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'textarea',
                'group_id' => 10,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            79 => 
            array (
                'id' => 81,
                'order' => 76,
                'is_default' => NULL,
                'legacy' => 0,
                'name' => 'Catering Information',
                'meta' => '',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'textarea',
                'group_id' => 11,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            80 => 
            array (
                'id' => 82,
                'order' => 77,
                'is_default' => NULL,
                'legacy' => 1,
                'name' => 'Other Information',
                'meta' => '',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'textarea',
                'group_id' => 6,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
            81 => 
            array (
                'id' => 83,
                'order' => 46,
                'is_default' => 1,
                'legacy' => 0,
                'name' => 'Email',
                'meta' => '',
                'comment' => '',
                'autocomplete' => 1,
                'autofill' => 1,
                'allow_prefill' => 1,
                'type' => 'email',
                'group_id' => 1,
                'created_at' => '2016-05-05 13:41:21',
                'updated_at' => '2016-05-05 13:41:21',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}