<?php

use Illuminate\Database\Seeder;

class EnrolmentFormTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('enrolment_form')->delete();
        
        \DB::table('enrolment_form')->insert(array (
            0 => 
            array (
                'id' => 1,
                'user_id' => 10,
                'name' => 'Basic Enrollment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-01-12 10:07:23',
                'updated_at' => '2017-01-12 10:07:23',
                'deleted_at' => NULL,
                'is_default' => 1,
            ),
            1 => 
            array (
                'id' => 2,
                'user_id' => 24,
                'name' => 'Basic Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-01-12 11:59:02',
                'updated_at' => '2017-01-12 11:59:02',
                'deleted_at' => NULL,
                'is_default' => 1,
            ),
            2 => 
            array (
                'id' => 3,
                'user_id' => 54,
                'name' => 'Basic Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-01-13 09:55:44',
                'updated_at' => '2017-01-13 09:55:44',
                'deleted_at' => NULL,
                'is_default' => 1,
            ),
            3 => 
            array (
                'id' => 4,
                'user_id' => 54,
                'name' => 'New Holiday Program Playz workz Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-01-13 13:29:54',
                'updated_at' => '2017-01-13 13:29:54',
                'deleted_at' => NULL,
                'is_default' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'user_id' => 24,
                'name' => 'Mercia\'s Test Workz listing 12012017 Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-02-01 17:04:12',
                'updated_at' => '2017-02-01 17:04:12',
                'deleted_at' => NULL,
                'is_default' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'user_id' => 24,
                'name' => 'Mercia\'s Test Workz listing 12012017 Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-02-23 15:22:44',
                'updated_at' => '2017-02-23 15:22:44',
                'deleted_at' => NULL,
                'is_default' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'user_id' => 60,
                'name' => 'Basic Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-02-24 13:53:10',
                'updated_at' => '2017-02-24 13:53:10',
                'deleted_at' => NULL,
                'is_default' => 1,
            ),
            7 => 
            array (
                'id' => 8,
                'user_id' => 60,
                'name' => 'Term Activity - Playz Workz Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-02-24 13:53:36',
                'updated_at' => '2017-02-24 13:53:36',
                'deleted_at' => NULL,
                'is_default' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'user_id' => 60,
                'name' => 'Term Activity - Playz Workz Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-02-24 13:56:34',
                'updated_at' => '2017-02-24 13:56:34',
                'deleted_at' => NULL,
                'is_default' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'user_id' => 60,
                'name' => 'Party time Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-02-27 10:12:13',
                'updated_at' => '2017-02-27 10:12:13',
                'deleted_at' => NULL,
                'is_default' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'user_id' => 60,
                'name' => 'Party time Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-02-27 10:14:28',
                'updated_at' => '2017-02-27 10:14:28',
                'deleted_at' => NULL,
                'is_default' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'user_id' => 24,
                'name' => 'Mercia\'s Test Workz listing 12012017 Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-02-27 12:58:15',
                'updated_at' => '2017-02-27 12:58:15',
                'deleted_at' => NULL,
                'is_default' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'user_id' => 60,
                'name' => 'Holiday Program - Playz Workz Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-02-27 13:18:09',
                'updated_at' => '2017-02-27 13:18:09',
                'deleted_at' => NULL,
                'is_default' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'user_id' => 24,
                'name' => 'Playz Workz Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-03-09 18:02:48',
                'updated_at' => '2017-03-09 18:02:48',
                'deleted_at' => NULL,
                'is_default' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'user_id' => 60,
                'name' => 'Great Holiday Program - Playz Partner Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-03-14 09:59:44',
                'updated_at' => '2017-03-14 09:59:44',
                'deleted_at' => NULL,
                'is_default' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'user_id' => 62,
                'name' => 'Basic Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-03-29 09:24:11',
                'updated_at' => '2017-03-29 09:24:11',
                'deleted_at' => NULL,
                'is_default' => 1,
            ),
            16 => 
            array (
                'id' => 17,
                'user_id' => 24,
                'name' => '20 April Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-04-20 22:26:20',
                'updated_at' => '2017-04-20 22:26:20',
                'deleted_at' => NULL,
                'is_default' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'user_id' => 24,
                'name' => 'Information Technology for Kids Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-04-21 12:04:56',
                'updated_at' => '2017-04-21 12:04:56',
                'deleted_at' => NULL,
                'is_default' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'user_id' => 24,
                'name' => 'Information Technology for Kids Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-04-21 12:53:51',
                'updated_at' => '2017-04-21 12:53:51',
                'deleted_at' => NULL,
                'is_default' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'user_id' => 24,
                'name' => 'Information Technology for Kids Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-04-21 13:04:07',
                'updated_at' => '2017-04-21 13:04:07',
                'deleted_at' => NULL,
                'is_default' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'user_id' => 67,
                'name' => 'Basic Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-04-21 13:16:04',
                'updated_at' => '2017-04-21 13:16:04',
                'deleted_at' => NULL,
                'is_default' => 1,
            ),
            21 => 
            array (
                'id' => 22,
                'user_id' => 67,
                'name' => '20170421 Test 10 Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-04-21 14:54:26',
                'updated_at' => '2017-04-21 14:54:26',
                'deleted_at' => NULL,
                'is_default' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'user_id' => 67,
                'name' => '20170421 Test 11 Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-04-21 15:03:45',
                'updated_at' => '2017-04-21 15:03:45',
                'deleted_at' => NULL,
                'is_default' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'user_id' => 73,
                'name' => 'Basic Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-04-23 11:00:29',
                'updated_at' => '2017-04-23 11:00:29',
                'deleted_at' => NULL,
                'is_default' => 1,
            ),
            24 => 
            array (
                'id' => 25,
                'user_id' => 73,
                'name' => 'Branding Design Workshop Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-04-23 11:00:42',
                'updated_at' => '2017-04-23 11:00:42',
                'deleted_at' => NULL,
                'is_default' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'user_id' => 67,
                'name' => '20170423 Test 1 Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-04-23 11:42:40',
                'updated_at' => '2017-04-23 11:42:40',
                'deleted_at' => NULL,
                'is_default' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'user_id' => 67,
                'name' => 'Test Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-04-23 14:58:44',
                'updated_at' => '2017-04-23 14:58:44',
                'deleted_at' => NULL,
                'is_default' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'user_id' => 73,
                'name' => 'Branding Design Workshop Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-04-23 15:32:58',
                'updated_at' => '2017-04-23 15:32:58',
                'deleted_at' => NULL,
                'is_default' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'user_id' => 73,
                'name' => 'playz Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-04-24 06:39:30',
                'updated_at' => '2017-04-24 06:39:30',
                'deleted_at' => NULL,
                'is_default' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'user_id' => 73,
                'name' => 'playz Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-04-24 06:55:16',
                'updated_at' => '2017-04-24 06:55:16',
                'deleted_at' => NULL,
                'is_default' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'user_id' => 66,
                'name' => 'Basic Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-04-24 07:37:16',
                'updated_at' => '2017-04-24 07:37:16',
                'deleted_at' => NULL,
                'is_default' => 1,
            ),
            31 => 
            array (
                'id' => 32,
                'user_id' => 66,
                'name' => 'Kids Swimming Lesson Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-04-24 07:37:36',
                'updated_at' => '2017-04-24 07:37:36',
                'deleted_at' => NULL,
                'is_default' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'user_id' => 78,
                'name' => 'Basic Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-04-24 14:15:59',
                'updated_at' => '2017-04-24 14:15:59',
                'deleted_at' => NULL,
                'is_default' => 1,
            ),
            33 => 
            array (
                'id' => 34,
                'user_id' => 79,
                'name' => 'Basic Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-04-24 14:21:28',
                'updated_at' => '2017-04-24 14:21:28',
                'deleted_at' => NULL,
                'is_default' => 1,
            ),
            34 => 
            array (
                'id' => 35,
                'user_id' => 80,
                'name' => 'Basic Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-04-24 15:39:04',
                'updated_at' => '2017-04-24 15:39:04',
                'deleted_at' => NULL,
                'is_default' => 1,
            ),
            35 => 
            array (
                'id' => 36,
                'user_id' => 80,
                'name' => 'Remo Test Listing 2 Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-04-24 15:39:15',
                'updated_at' => '2017-04-24 15:39:15',
                'deleted_at' => NULL,
                'is_default' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'user_id' => 1,
                'name' => 'Basic Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-04-24 15:54:14',
                'updated_at' => '2017-04-24 15:54:14',
                'deleted_at' => NULL,
                'is_default' => 1,
            ),
            37 => 
            array (
                'id' => 38,
                'user_id' => 1,
                'name' => 'Remo Test Listing Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-04-24 15:54:21',
                'updated_at' => '2017-04-24 15:54:21',
                'deleted_at' => NULL,
                'is_default' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'user_id' => 2,
                'name' => 'Basic Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-04-24 17:32:25',
                'updated_at' => '2017-04-24 17:32:25',
                'deleted_at' => NULL,
                'is_default' => 1,
            ),
            39 => 
            array (
                'id' => 40,
                'user_id' => 5,
                'name' => 'Basic Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-04-25 11:15:34',
                'updated_at' => '2017-04-25 11:15:34',
                'deleted_at' => NULL,
                'is_default' => 1,
            ),
            40 => 
            array (
                'id' => 41,
                'user_id' => 6,
                'name' => 'Basic Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-04-28 09:27:42',
                'updated_at' => '2017-04-28 09:27:42',
                'deleted_at' => NULL,
                'is_default' => 1,
            ),
            41 => 
            array (
                'id' => 42,
                'user_id' => 6,
                'name' => 'Tennis Lessons Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-04-28 09:28:05',
                'updated_at' => '2017-04-28 09:28:05',
                'deleted_at' => NULL,
                'is_default' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'user_id' => 8,
                'name' => 'Basic Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-05-01 11:21:53',
                'updated_at' => '2017-05-01 11:21:53',
                'deleted_at' => NULL,
                'is_default' => 1,
            ),
            43 => 
            array (
                'id' => 44,
                'user_id' => 8,
                'name' => 'Prep For Prep Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-05-01 11:25:22',
                'updated_at' => '2017-05-01 11:25:22',
                'deleted_at' => NULL,
                'is_default' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'user_id' => 7,
                'name' => 'Basic Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-05-01 13:48:09',
                'updated_at' => '2017-05-01 13:48:09',
                'deleted_at' => NULL,
                'is_default' => 1,
            ),
            45 => 
            array (
                'id' => 46,
                'user_id' => 7,
                'name' => 'Craft Classes Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-05-09 09:47:04',
                'updated_at' => '2017-05-09 09:47:04',
                'deleted_at' => NULL,
                'is_default' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'user_id' => 7,
                'name' => 'Craft Classes Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-05-09 09:52:22',
                'updated_at' => '2017-05-09 09:52:22',
                'deleted_at' => NULL,
                'is_default' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'user_id' => 6,
                'name' => 'Badge Making classes Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-07-25 10:43:00',
                'updated_at' => '2017-07-25 10:43:00',
                'deleted_at' => NULL,
                'is_default' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'user_id' => 21,
                'name' => 'Basic Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-07-28 13:03:57',
                'updated_at' => '2017-07-28 13:03:57',
                'deleted_at' => NULL,
                'is_default' => 1,
            ),
            49 => 
            array (
                'id' => 50,
                'user_id' => 26,
                'name' => 'Basic Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-08-04 13:52:08',
                'updated_at' => '2017-08-04 13:52:08',
                'deleted_at' => NULL,
                'is_default' => 1,
            ),
            50 => 
            array (
                'id' => 51,
                'user_id' => 26,
                'name' => 'Piano lessons Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-08-04 13:52:29',
                'updated_at' => '2017-08-04 13:52:29',
                'deleted_at' => NULL,
                'is_default' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'user_id' => 26,
                'name' => 'Piano lessons Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-08-04 14:17:31',
                'updated_at' => '2017-08-04 14:17:31',
                'deleted_at' => NULL,
                'is_default' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'user_id' => 27,
                'name' => 'Basic Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-08-07 10:38:48',
                'updated_at' => '2017-08-07 10:38:48',
                'deleted_at' => NULL,
                'is_default' => 1,
            ),
            53 => 
            array (
                'id' => 54,
                'user_id' => 27,
                'name' => 'Kristie\'s Test Party Listing Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-08-08 09:48:50',
                'updated_at' => '2017-08-08 09:48:50',
                'deleted_at' => NULL,
                'is_default' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'user_id' => 27,
                'name' => 'Kristie\'s Testing Activity Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-08-08 10:12:01',
                'updated_at' => '2017-08-08 10:12:01',
                'deleted_at' => NULL,
                'is_default' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'user_id' => 26,
                'name' => 'Percussion Classes Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-08-22 10:57:47',
                'updated_at' => '2017-08-22 10:57:47',
                'deleted_at' => NULL,
                'is_default' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'user_id' => 28,
                'name' => 'Basic Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-08-22 19:01:42',
                'updated_at' => '2017-08-22 19:01:42',
                'deleted_at' => NULL,
                'is_default' => 1,
            ),
            57 => 
            array (
                'id' => 58,
                'user_id' => 28,
                'name' => 'Tennis Classes Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-08-22 19:01:58',
                'updated_at' => '2017-08-22 19:01:58',
                'deleted_at' => NULL,
                'is_default' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'user_id' => 29,
                'name' => 'Basic Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-08-24 09:42:34',
                'updated_at' => '2017-08-24 09:42:34',
                'deleted_at' => NULL,
                'is_default' => 1,
            ),
            59 => 
            array (
                'id' => 60,
                'user_id' => 29,
                'name' => 'Cooking Classes Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-08-24 09:42:49',
                'updated_at' => '2017-08-24 09:42:49',
                'deleted_at' => NULL,
                'is_default' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'user_id' => 30,
                'name' => 'Basic Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-09-04 12:25:03',
                'updated_at' => '2017-09-04 12:25:03',
                'deleted_at' => NULL,
                'is_default' => 1,
            ),
            61 => 
            array (
                'id' => 62,
                'user_id' => 30,
                'name' => 'Footy Club Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-09-04 12:26:52',
                'updated_at' => '2017-09-04 12:26:52',
                'deleted_at' => NULL,
                'is_default' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'user_id' => 29,
                'name' => 'Cooking Holiday Program Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-09-07 13:22:06',
                'updated_at' => '2017-09-07 13:22:06',
                'deleted_at' => NULL,
                'is_default' => NULL,
            ),
            63 => 
            array (
                'id' => 64,
                'user_id' => 33,
                'name' => 'Basic Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-09-12 11:49:59',
                'updated_at' => '2017-09-12 11:49:59',
                'deleted_at' => NULL,
                'is_default' => 1,
            ),
            64 => 
            array (
                'id' => 65,
                'user_id' => 33,
                'name' => 'Piano lessons Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-09-12 11:50:11',
                'updated_at' => '2017-09-12 11:50:11',
                'deleted_at' => NULL,
                'is_default' => NULL,
            ),
            65 => 
            array (
                'id' => 66,
                'user_id' => 33,
                'name' => 'Harp lessons Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-09-12 13:01:27',
                'updated_at' => '2017-09-12 13:01:27',
                'deleted_at' => NULL,
                'is_default' => NULL,
            ),
            66 => 
            array (
                'id' => 67,
                'user_id' => 33,
                'name' => 'Party Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-09-12 13:29:48',
                'updated_at' => '2017-09-12 13:29:48',
                'deleted_at' => NULL,
                'is_default' => NULL,
            ),
            67 => 
            array (
                'id' => 68,
                'user_id' => 33,
                'name' => 'Piano Lessons Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-09-13 10:49:32',
                'updated_at' => '2017-09-13 10:49:32',
                'deleted_at' => NULL,
                'is_default' => NULL,
            ),
            68 => 
            array (
                'id' => 69,
                'user_id' => 33,
                'name' => 'Piano Lessons Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-09-13 10:56:28',
                'updated_at' => '2017-09-13 10:56:28',
                'deleted_at' => NULL,
                'is_default' => NULL,
            ),
            69 => 
            array (
                'id' => 70,
                'user_id' => 37,
                'name' => 'Basic Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-09-14 09:39:21',
                'updated_at' => '2017-09-14 09:39:21',
                'deleted_at' => NULL,
                'is_default' => 1,
            ),
            70 => 
            array (
                'id' => 71,
                'user_id' => 38,
                'name' => 'Basic Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-09-14 10:11:52',
                'updated_at' => '2017-09-14 10:11:52',
                'deleted_at' => NULL,
                'is_default' => 1,
            ),
            71 => 
            array (
                'id' => 72,
                'user_id' => 40,
                'name' => 'Basic Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-09-15 12:28:41',
                'updated_at' => '2017-09-15 12:28:41',
                'deleted_at' => NULL,
                'is_default' => 1,
            ),
            72 => 
            array (
                'id' => 73,
                'user_id' => 40,
                'name' => 'Baking Classes Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-09-15 12:29:04',
                'updated_at' => '2017-09-15 12:29:04',
                'deleted_at' => NULL,
                'is_default' => NULL,
            ),
            73 => 
            array (
                'id' => 74,
                'user_id' => 40,
                'name' => 'Baking Classes Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-09-15 12:32:29',
                'updated_at' => '2017-09-15 12:32:29',
                'deleted_at' => NULL,
                'is_default' => NULL,
            ),
            74 => 
            array (
                'id' => 75,
                'user_id' => 40,
                'name' => 'Party Food Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-09-19 10:20:53',
                'updated_at' => '2017-09-19 10:20:53',
                'deleted_at' => NULL,
                'is_default' => NULL,
            ),
            75 => 
            array (
                'id' => 76,
                'user_id' => 41,
                'name' => 'Basic Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-09-19 13:38:13',
                'updated_at' => '2017-09-19 13:38:13',
                'deleted_at' => NULL,
                'is_default' => 1,
            ),
            76 => 
            array (
                'id' => 77,
                'user_id' => 41,
                'name' => 'Dance classes Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-09-19 13:38:53',
                'updated_at' => '2017-09-19 13:38:53',
                'deleted_at' => NULL,
                'is_default' => NULL,
            ),
            77 => 
            array (
                'id' => 78,
                'user_id' => 42,
                'name' => 'Basic Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-09-20 10:14:46',
                'updated_at' => '2017-09-20 10:14:46',
                'deleted_at' => NULL,
                'is_default' => 1,
            ),
            78 => 
            array (
                'id' => 79,
                'user_id' => 45,
                'name' => 'Basic Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-09-21 11:51:55',
                'updated_at' => '2017-09-21 11:51:55',
                'deleted_at' => NULL,
                'is_default' => 1,
            ),
            79 => 
            array (
                'id' => 80,
                'user_id' => 51,
                'name' => 'Basic Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-10-01 12:27:53',
                'updated_at' => '2017-10-01 12:27:53',
                'deleted_at' => NULL,
                'is_default' => 1,
            ),
            80 => 
            array (
                'id' => 81,
                'user_id' => 51,
                'name' => 'Classes Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-10-01 12:29:08',
                'updated_at' => '2017-10-01 12:29:08',
                'deleted_at' => NULL,
                'is_default' => NULL,
            ),
            81 => 
            array (
                'id' => 82,
                'user_id' => 58,
                'name' => 'Basic Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-10-17 15:35:05',
                'updated_at' => '2017-10-17 15:35:05',
                'deleted_at' => NULL,
                'is_default' => 1,
            ),
            82 => 
            array (
                'id' => 83,
                'user_id' => 59,
                'name' => 'Basic Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-10-19 13:23:54',
                'updated_at' => '2017-10-19 13:23:54',
                'deleted_at' => NULL,
                'is_default' => 1,
            ),
            83 => 
            array (
                'id' => 84,
                'user_id' => 59,
                'name' => 'Sonny\'s Holiday Program Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-10-19 13:24:06',
                'updated_at' => '2017-10-19 13:24:06',
                'deleted_at' => NULL,
                'is_default' => NULL,
            ),
            84 => 
            array (
                'id' => 85,
                'user_id' => 60,
                'name' => 'Piano Lessons Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-10-24 12:09:17',
                'updated_at' => '2017-10-24 12:09:17',
                'deleted_at' => NULL,
                'is_default' => NULL,
            ),
            85 => 
            array (
                'id' => 86,
                'user_id' => 61,
                'name' => 'Basic Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-10-25 09:17:24',
                'updated_at' => '2017-10-25 09:17:24',
                'deleted_at' => NULL,
                'is_default' => 1,
            ),
            86 => 
            array (
                'id' => 87,
                'user_id' => 64,
                'name' => 'Basic Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-10-25 12:07:08',
                'updated_at' => '2017-10-25 12:07:08',
                'deleted_at' => NULL,
                'is_default' => 1,
            ),
            87 => 
            array (
                'id' => 88,
                'user_id' => 64,
                'name' => 'Sonny\'s Holiday Program Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-10-25 12:07:19',
                'updated_at' => '2017-10-25 12:07:19',
                'deleted_at' => NULL,
                'is_default' => NULL,
            ),
            88 => 
            array (
                'id' => 89,
                'user_id' => 65,
                'name' => 'Basic Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-10-26 12:49:13',
                'updated_at' => '2017-10-26 12:49:13',
                'deleted_at' => NULL,
                'is_default' => 1,
            ),
            89 => 
            array (
                'id' => 90,
                'user_id' => 65,
                'name' => 'Piano Lessons Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-10-26 12:49:26',
                'updated_at' => '2017-10-26 12:49:26',
                'deleted_at' => NULL,
                'is_default' => NULL,
            ),
            90 => 
            array (
                'id' => 91,
                'user_id' => 65,
                'name' => 'Piano Lessons Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-10-26 12:55:32',
                'updated_at' => '2017-10-26 12:55:32',
                'deleted_at' => NULL,
                'is_default' => NULL,
            ),
            91 => 
            array (
                'id' => 92,
                'user_id' => 71,
                'name' => 'Basic Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-11-02 15:00:28',
                'updated_at' => '2017-11-02 15:00:28',
                'deleted_at' => NULL,
                'is_default' => 1,
            ),
            92 => 
            array (
                'id' => 93,
                'user_id' => 75,
                'name' => 'Basic Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-11-03 12:41:37',
                'updated_at' => '2017-11-03 12:41:37',
                'deleted_at' => NULL,
                'is_default' => 1,
            ),
            93 => 
            array (
                'id' => 94,
                'user_id' => 75,
                'name' => 'Ceramic Classes Enrolment Form',
                'type' => '',
                'for_holidays' => 0,
                'for_classes' => 0,
                'for_fun' => 0,
                'for_parties' => 0,
                'created_at' => '2017-11-03 12:41:49',
                'updated_at' => '2017-11-03 12:41:49',
                'deleted_at' => NULL,
                'is_default' => NULL,
            ),
        ));
        
        
    }
}