<?php

use Illuminate\Database\Seeder;

class OrdersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('orders')->delete();
        
        \DB::table('orders')->insert(array (
            0 => 
            array (
                'id' => 87,
                'sub_total' => '30.00',
                'discounts' => '0.00',
                'total' => '30.00',
                'coupon_id' => 0,
                'type' => 'BOOKING',
                'user_id' => 34,
                'activity_id' => 47,
                'activity_name' => 'Piano Lessons',
                'enrolment_form_id' => 69,
                'invite_id' => 0,
                'status' => 'COMPLETED',
                'cart_id' => 'dd0f803b669b6ca514c52c00b39d55c7',
                'pay_key' => 'ch_1B1RZPFDw6nmSmJdNnOuw9p3',
                'completed_at' => '2017-09-13 12:59:46',
                'created_at' => '2017-09-13 12:08:17',
                'updated_at' => '2017-09-13 12:59:49',
                'comments' => '',
                'provider_amount' => '30.00',
                'playz_amount' => '0.00',
                'gst_amount' => '0.00',
                'includes_gst' => 0,
                'selected_objects' => '{"events":["1723","1723"],"packages":[]}',
            ),
            1 => 
            array (
                'id' => 90,
                'sub_total' => '15.00',
                'discounts' => '0.00',
                'total' => '15.00',
                'coupon_id' => 0,
                'type' => 'BOOKING',
                'user_id' => 36,
                'activity_id' => 47,
                'activity_name' => 'Piano Lessons',
                'enrolment_form_id' => 69,
                'invite_id' => 0,
                'status' => 'COMPLETED',
                'cart_id' => 'dd0f803b669b6ca514c52c00b39d55c7',
                'pay_key' => 'ch_1B1ST3FDw6nmSmJdKY9HnSy2',
                'completed_at' => '2017-09-13 13:57:15',
                'created_at' => '2017-09-13 13:54:23',
                'updated_at' => '2017-09-13 13:57:18',
                'comments' => '',
                'provider_amount' => '15.00',
                'playz_amount' => '0.00',
                'gst_amount' => '0.00',
                'includes_gst' => 0,
                'selected_objects' => '{"events":["1723"],"packages":[]}',
            ),
            2 => 
            array (
                'id' => 92,
                'sub_total' => '200.00',
                'discounts' => '0.00',
                'total' => '200.00',
                'coupon_id' => 0,
                'type' => 'BOOKING',
                'user_id' => 39,
                'activity_id' => 47,
                'activity_name' => 'Piano Lessons',
                'enrolment_form_id' => 69,
                'invite_id' => 0,
                'status' => 'COMPLETED',
                'cart_id' => '224174b2562fea1960ae2ec606056543',
                'pay_key' => 'ch_1B1lOOFDw6nmSmJdkvyJaHjL',
                'completed_at' => '2017-09-14 10:09:44',
                'created_at' => '2017-09-14 09:59:01',
                'updated_at' => '2017-09-14 10:09:47',
                'comments' => '',
                'provider_amount' => '200.00',
                'playz_amount' => '0.00',
                'gst_amount' => '0.00',
                'includes_gst' => 0,
                'selected_objects' => '{"events":["1713"],"packages":[]}',
            ),
            3 => 
            array (
                'id' => 97,
                'sub_total' => '270.00',
                'discounts' => '0.00',
                'total' => '270.00',
                'coupon_id' => 0,
                'type' => 'BOOKING',
                'user_id' => 36,
                'activity_id' => 53,
                'activity_name' => 'Baking Classes',
                'enrolment_form_id' => 74,
                'invite_id' => 0,
                'status' => 'COMPLETED',
                'cart_id' => 'dd0f803b669b6ca514c52c00b39d55c7',
                'pay_key' => 'ch_1B2BREFDw6nmSmJdjJPCo6qe',
                'completed_at' => '2017-09-15 13:58:24',
                'created_at' => '2017-09-15 13:14:33',
                'updated_at' => '2017-09-15 13:58:29',
                'comments' => '',
                'provider_amount' => '270.00',
                'playz_amount' => '0.00',
                'gst_amount' => '0.00',
                'includes_gst' => 0,
                'selected_objects' => '{"events":["1895"],"packages":["118"]}',
            ),
            4 => 
            array (
                'id' => 102,
                'sub_total' => '250.00',
                'discounts' => '0.00',
                'total' => '250.00',
                'coupon_id' => 0,
                'type' => 'BOOKING',
                'user_id' => 33,
                'activity_id' => 53,
                'activity_name' => 'Baking Classes',
                'enrolment_form_id' => 74,
                'invite_id' => 0,
                'status' => 'COMPLETED',
                'cart_id' => '194c5a0c7d6d65f57dd8fa6101d93e20',
                'pay_key' => 'ch_1B3Z6FFDw6nmSmJdskLU9kca',
                'completed_at' => '2017-09-19 09:26:27',
                'created_at' => '2017-09-19 09:25:34',
                'updated_at' => '2017-09-19 09:26:32',
                'comments' => '',
                'provider_amount' => '250.00',
                'playz_amount' => '0.00',
                'gst_amount' => '0.00',
                'includes_gst' => 0,
                'selected_objects' => '{"events":[],"packages":["118"]}',
            ),
            5 => 
            array (
                'id' => 113,
                'sub_total' => '140.00',
                'discounts' => '0.00',
                'total' => '140.00',
                'coupon_id' => 0,
                'type' => 'BOOKING',
                'user_id' => 43,
                'activity_id' => 61,
                'activity_name' => 'School Holiday Cricket Club',
                'enrolment_form_id' => 79,
                'invite_id' => 0,
                'status' => 'COMPLETED',
                'cart_id' => '7aafd9ed8cde84a2579e6c54547f942c',
                'pay_key' => 'ch_1B4KmzFDw6nmSmJdy4BRg5ZE',
                'completed_at' => '2017-09-21 12:21:46',
                'created_at' => '2017-09-21 11:09:18',
                'updated_at' => '2017-09-21 12:21:52',
                'comments' => '',
                'provider_amount' => '140.00',
                'playz_amount' => '0.00',
                'gst_amount' => '0.00',
                'includes_gst' => 0,
                'selected_objects' => '{"events":["2688","2688"],"packages":[]}',
            ),
            6 => 
            array (
                'id' => 118,
                'sub_total' => '260.00',
                'discounts' => '0.00',
                'total' => '260.00',
                'coupon_id' => 0,
                'type' => 'BOOKING',
                'user_id' => 43,
                'activity_id' => 61,
                'activity_name' => 'School Holiday Cricket Club',
                'enrolment_form_id' => 79,
                'invite_id' => 0,
                'status' => 'COMPLETED',
                'cart_id' => '7aafd9ed8cde84a2579e6c54547f942c',
                'pay_key' => 'ch_1B4Kr6FDw6nmSmJdpLfhgBLq',
                'completed_at' => '2017-09-21 12:26:00',
                'created_at' => '2017-09-21 12:21:51',
                'updated_at' => '2017-09-21 12:26:02',
                'comments' => '',
                'provider_amount' => '260.00',
                'playz_amount' => '0.00',
                'gst_amount' => '0.00',
                'includes_gst' => 0,
                'selected_objects' => '{"events":["2693","2693","2693"],"packages":[]}',
            ),
            7 => 
            array (
                'id' => 119,
                'sub_total' => '10.00',
                'discounts' => '0.00',
                'total' => '10.00',
                'coupon_id' => 0,
                'type' => 'BOOKING',
                'user_id' => 43,
                'activity_id' => 57,
                'activity_name' => 'Farm tours',
                'enrolment_form_id' => 0,
                'invite_id' => 0,
                'status' => 'COMPLETED',
                'cart_id' => '7aafd9ed8cde84a2579e6c54547f942c',
                'pay_key' => 'ch_1B4KtAFDw6nmSmJdjgUmGXdS',
                'completed_at' => '2017-09-21 12:28:08',
                'created_at' => '2017-09-21 12:26:00',
                'updated_at' => '2017-09-21 12:28:10',
                'comments' => '',
                'provider_amount' => '10.00',
                'playz_amount' => '0.00',
                'gst_amount' => '0.00',
                'includes_gst' => 0,
                'selected_objects' => '{"events":["2665"],"packages":[]}',
            ),
            8 => 
            array (
                'id' => 120,
                'sub_total' => '10.00',
                'discounts' => '0.00',
                'total' => '10.00',
                'coupon_id' => 0,
                'type' => 'BOOKING',
                'user_id' => 43,
                'activity_id' => 56,
                'activity_name' => 'Berry Picking',
                'enrolment_form_id' => 0,
                'invite_id' => 0,
                'status' => 'COMPLETED',
                'cart_id' => '7aafd9ed8cde84a2579e6c54547f942c',
                'pay_key' => 'ch_1B4KutFDw6nmSmJdkOO0u2uj',
                'completed_at' => '2017-09-21 12:29:55',
                'created_at' => '2017-09-21 12:28:08',
                'updated_at' => '2017-09-21 12:29:57',
                'comments' => '',
                'provider_amount' => '10.00',
                'playz_amount' => '0.00',
                'gst_amount' => '0.00',
                'includes_gst' => 0,
                'selected_objects' => '{"events":["2423"],"packages":[]}',
            ),
            9 => 
            array (
                'id' => 125,
                'sub_total' => '10.00',
                'discounts' => '0.00',
                'total' => '10.00',
                'coupon_id' => 0,
                'type' => 'BOOKING',
                'user_id' => 34,
                'activity_id' => 57,
                'activity_name' => 'Farm tours',
                'enrolment_form_id' => 0,
                'invite_id' => 0,
                'status' => 'COMPLETED',
                'cart_id' => '80ade101cbd283846aabfc9614e5d275',
                'pay_key' => 'ch_1B4dcJFDw6nmSmJdoizZgIDT',
                'completed_at' => '2017-09-22 08:27:59',
                'created_at' => '2017-09-22 08:24:58',
                'updated_at' => '2017-09-22 08:28:08',
                'comments' => '',
                'provider_amount' => '10.00',
                'playz_amount' => '0.00',
                'gst_amount' => '0.00',
                'includes_gst' => 0,
                'selected_objects' => '{"events":["2665"],"packages":[]}',
            ),
            10 => 
            array (
                'id' => 128,
                'sub_total' => '1950.00',
                'discounts' => '0.00',
                'total' => '1950.00',
                'coupon_id' => 0,
                'type' => 'BOOKING',
                'user_id' => 43,
                'activity_id' => 61,
                'activity_name' => 'School Holiday Cricket Club',
                'enrolment_form_id' => 79,
                'invite_id' => 0,
                'status' => 'COMPLETED',
                'cart_id' => '7aafd9ed8cde84a2579e6c54547f942c',
                'pay_key' => 'ch_1B4gQfFDw6nmSmJdfEMe5j3a',
                'completed_at' => '2017-09-22 11:28:08',
                'created_at' => '2017-09-22 10:49:05',
                'updated_at' => '2017-09-22 11:28:14',
                'comments' => '',
                'provider_amount' => '1950.00',
                'playz_amount' => '0.00',
                'gst_amount' => '0.00',
                'includes_gst' => 0,
                'selected_objects' => '{"events":[],"packages":["135","135","135","136"]}',
            ),
            11 => 
            array (
                'id' => 129,
                'sub_total' => '450.00',
                'discounts' => '0.00',
                'total' => '450.00',
                'coupon_id' => 0,
                'type' => 'BOOKING',
                'user_id' => 43,
                'activity_id' => 61,
                'activity_name' => 'School Holiday Cricket Club',
                'enrolment_form_id' => 79,
                'invite_id' => 0,
                'status' => 'COMPLETED',
                'cart_id' => '7aafd9ed8cde84a2579e6c54547f942c',
                'pay_key' => 'ch_1B4goCFDw6nmSmJduqGKAGcg',
                'completed_at' => '2017-09-22 11:52:27',
                'created_at' => '2017-09-22 11:28:11',
                'updated_at' => '2017-09-22 11:52:32',
                'comments' => '',
                'provider_amount' => '450.00',
                'playz_amount' => '0.00',
                'gst_amount' => '0.00',
                'includes_gst' => 0,
                'selected_objects' => '{"events":[],"packages":["136","136"]}',
            ),
            12 => 
            array (
                'id' => 131,
                'sub_total' => '50.00',
                'discounts' => '0.00',
                'total' => '50.00',
                'coupon_id' => 0,
                'type' => 'BOOKING',
                'user_id' => 43,
                'activity_id' => 56,
                'activity_name' => 'Berry Picking',
                'enrolment_form_id' => 0,
                'invite_id' => 0,
                'status' => 'COMPLETED',
                'cart_id' => '7aafd9ed8cde84a2579e6c54547f942c',
                'pay_key' => 'ch_1B4gsWFDw6nmSmJdIU1NWNIa',
                'completed_at' => '2017-09-22 11:56:55',
                'created_at' => '2017-09-22 11:52:29',
                'updated_at' => '2017-09-22 11:56:58',
                'comments' => '',
                'provider_amount' => '50.00',
                'playz_amount' => '0.00',
                'gst_amount' => '0.00',
                'includes_gst' => 0,
                'selected_objects' => '{"events":["2515","2515","2515","2515","2515"],"packages":[]}',
            ),
            13 => 
            array (
                'id' => 137,
                'sub_total' => '300.00',
                'discounts' => '0.00',
                'total' => '300.00',
                'coupon_id' => 0,
                'type' => 'BOOKING',
                'user_id' => 34,
                'activity_id' => 63,
                'activity_name' => 'Sunday Night Party - Private',
                'enrolment_form_id' => 0,
                'invite_id' => 0,
                'status' => 'COMPLETED',
                'cart_id' => '51fc34c6b5f4a6d637a74181dbbbcc9c',
                'pay_key' => 'ch_1B5OTRFDw6nmSmJdpJYoNyVL',
                'completed_at' => '2017-09-24 10:29:57',
                'created_at' => '2017-09-24 10:27:43',
                'updated_at' => '2017-09-24 10:30:00',
                'comments' => '',
                'provider_amount' => '300.00',
                'playz_amount' => '0.00',
                'gst_amount' => '0.00',
                'includes_gst' => 0,
                'selected_objects' => '{"events":["2874"],"packages":[]}',
            ),
            14 => 
            array (
                'id' => 142,
                'sub_total' => '400.00',
                'discounts' => '0.00',
                'total' => '400.00',
                'coupon_id' => 0,
                'type' => 'BOOKING',
                'user_id' => 43,
                'activity_id' => 61,
                'activity_name' => 'School Holiday Cricket Club',
                'enrolment_form_id' => 79,
                'invite_id' => 0,
                'status' => 'COMPLETED',
                'cart_id' => '7aafd9ed8cde84a2579e6c54547f942c',
                'pay_key' => 'ch_1B5oKUFDw6nmSmJdNNJim96m',
                'completed_at' => '2017-09-25 14:06:26',
                'created_at' => '2017-09-25 14:04:36',
                'updated_at' => '2017-09-25 14:06:29',
                'comments' => '',
                'provider_amount' => '400.00',
                'playz_amount' => '0.00',
                'gst_amount' => '0.00',
                'includes_gst' => 0,
                'selected_objects' => '{"events":[],"packages":["134","134"]}',
            ),
            15 => 
            array (
                'id' => 143,
                'sub_total' => '400.00',
                'discounts' => '0.00',
                'total' => '400.00',
                'coupon_id' => 0,
                'type' => 'BOOKING',
                'user_id' => 43,
                'activity_id' => 61,
                'activity_name' => 'School Holiday Cricket Club',
                'enrolment_form_id' => 79,
                'invite_id' => 0,
                'status' => 'COMPLETED',
                'cart_id' => '7aafd9ed8cde84a2579e6c54547f942c',
                'pay_key' => 'ch_1B5pbLFDw6nmSmJdpu4QOWlX',
                'completed_at' => '2017-09-25 15:27:54',
                'created_at' => '2017-09-25 14:06:26',
                'updated_at' => '2017-09-25 15:27:57',
                'comments' => '',
                'provider_amount' => '400.00',
                'playz_amount' => '0.00',
                'gst_amount' => '0.00',
                'includes_gst' => 0,
                'selected_objects' => '{"events":[],"packages":["134"]}',
            ),
            16 => 
            array (
                'id' => 144,
                'sub_total' => '400.00',
                'discounts' => '0.00',
                'total' => '400.00',
                'coupon_id' => 0,
                'type' => 'BOOKING',
                'user_id' => 47,
                'activity_id' => 61,
                'activity_name' => 'School Holiday Cricket Club',
                'enrolment_form_id' => 79,
                'invite_id' => 0,
                'status' => 'COMPLETED',
                'cart_id' => '7aafd9ed8cde84a2579e6c54547f942c',
                'pay_key' => 'ch_1B5oYxFDw6nmSmJdYNZQgOq2',
                'completed_at' => '2017-09-25 14:21:22',
                'created_at' => '2017-09-25 14:19:54',
                'updated_at' => '2017-09-25 14:21:26',
                'comments' => '',
                'provider_amount' => '400.00',
                'playz_amount' => '0.00',
                'gst_amount' => '0.00',
                'includes_gst' => 0,
                'selected_objects' => '{"events":[],"packages":["134"]}',
            ),
            17 => 
            array (
                'id' => 149,
                'sub_total' => '150.00',
                'discounts' => '0.00',
                'total' => '150.00',
                'coupon_id' => 0,
                'type' => 'BOOKING',
                'user_id' => 43,
                'activity_id' => 61,
                'activity_name' => 'School Holiday Cricket Club',
                'enrolment_form_id' => 0,
                'invite_id' => 0,
                'status' => 'COMPLETED',
                'cart_id' => '7aafd9ed8cde84a2579e6c54547f942c',
                'pay_key' => 'ch_1B67MnFDw6nmSmJd36WB3lSj',
                'completed_at' => '2017-09-26 10:26:04',
                'created_at' => '2017-09-26 10:24:54',
                'updated_at' => '2017-09-26 10:26:09',
                'comments' => '',
                'provider_amount' => '150.00',
                'playz_amount' => '0.00',
                'gst_amount' => '0.00',
                'includes_gst' => 0,
                'selected_objects' => '{"events":[],"packages":["141"]}',
            ),
            18 => 
            array (
                'id' => 152,
                'sub_total' => '280.00',
                'discounts' => '0.00',
                'total' => '280.00',
                'coupon_id' => 0,
                'type' => 'BOOKING',
                'user_id' => 34,
                'activity_id' => 67,
                'activity_name' => 'Tap Dance Classes',
                'enrolment_form_id' => 0,
                'invite_id' => 0,
                'status' => 'COMPLETED',
                'cart_id' => 'ed0681063258885be508d29828ec1a0c',
                'pay_key' => 'ch_1B6WCNFDw6nmSmJdON4TIo1H',
                'completed_at' => '2017-09-27 12:56:58',
                'created_at' => '2017-09-27 11:32:39',
                'updated_at' => '2017-09-27 12:57:03',
                'comments' => '',
                'provider_amount' => '280.00',
                'playz_amount' => '0.00',
                'gst_amount' => '0.00',
                'includes_gst' => 0,
                'selected_objects' => '{"events":["2934"],"packages":["145"]}',
            ),
            19 => 
            array (
                'id' => 153,
                'sub_total' => '150.00',
                'discounts' => '0.00',
                'total' => '150.00',
                'coupon_id' => 0,
                'type' => 'BOOKING',
                'user_id' => 43,
                'activity_id' => 61,
                'activity_name' => 'School Holiday Cricket Club',
                'enrolment_form_id' => 79,
                'invite_id' => 0,
                'status' => 'COMPLETED',
                'cart_id' => '7aafd9ed8cde84a2579e6c54547f942c',
                'pay_key' => 'ch_1B6XjhFDw6nmSmJdgGFKWGIU',
                'completed_at' => '2017-09-27 14:35:28',
                'created_at' => '2017-09-27 12:18:07',
                'updated_at' => '2017-09-27 14:35:33',
                'comments' => '',
                'provider_amount' => '150.00',
                'playz_amount' => '0.00',
                'gst_amount' => '0.00',
                'includes_gst' => 0,
                'selected_objects' => '{"events":[],"packages":["149"]}',
            ),
            20 => 
            array (
                'id' => 157,
                'sub_total' => '800.00',
                'discounts' => '0.00',
                'total' => '800.00',
                'coupon_id' => 0,
                'type' => 'BOOKING',
                'user_id' => 43,
                'activity_id' => 61,
                'activity_name' => 'School Holiday Cricket Club',
                'enrolment_form_id' => 79,
                'invite_id' => 0,
                'status' => 'COMPLETED',
                'cart_id' => '7aafd9ed8cde84a2579e6c54547f942c',
                'pay_key' => 'ch_1B6XsNFDw6nmSmJdfozC56oB',
                'completed_at' => '2017-09-27 14:44:26',
                'created_at' => '2017-09-27 14:35:30',
                'updated_at' => '2017-09-27 14:44:30',
                'comments' => '',
                'provider_amount' => '800.00',
                'playz_amount' => '0.00',
                'gst_amount' => '0.00',
                'includes_gst' => 0,
                'selected_objects' => '{"events":["3009"],"packages":["150"]}',
            ),
            21 => 
            array (
                'id' => 160,
                'sub_total' => '250.00',
                'discounts' => '0.00',
                'total' => '250.00',
                'coupon_id' => 0,
                'type' => 'BOOKING',
                'user_id' => 34,
                'activity_id' => 67,
                'activity_name' => 'Tap Dance Classes',
                'enrolment_form_id' => 0,
                'invite_id' => 0,
                'status' => 'COMPLETED',
                'cart_id' => 'ed0681063258885be508d29828ec1a0c',
                'pay_key' => 'ch_1B6ooUFDw6nmSmJdxRWpvCvJ',
                'completed_at' => '2017-09-28 08:49:34',
                'created_at' => '2017-09-28 08:42:17',
                'updated_at' => '2017-09-28 08:49:42',
                'comments' => '',
                'provider_amount' => '250.00',
                'playz_amount' => '0.00',
                'gst_amount' => '0.00',
                'includes_gst' => 0,
                'selected_objects' => '{"events":[],"packages":["145"]}',
            ),
            22 => 
            array (
                'id' => 162,
                'sub_total' => '70.00',
                'discounts' => '0.00',
                'total' => '70.00',
                'coupon_id' => 0,
                'type' => 'BOOKING',
                'user_id' => 43,
                'activity_id' => 69,
                'activity_name' => 'Soccer Skills',
                'enrolment_form_id' => 79,
                'invite_id' => 0,
                'status' => 'COMPLETED',
                'cart_id' => '7aafd9ed8cde84a2579e6c54547f942c',
                'pay_key' => 'ch_1B6q68FDw6nmSmJdvIRnjVs8',
                'completed_at' => '2017-09-28 10:11:51',
                'created_at' => '2017-09-28 10:09:52',
                'updated_at' => '2017-09-28 10:11:57',
                'comments' => '',
                'provider_amount' => '70.00',
                'playz_amount' => '0.00',
                'gst_amount' => '0.00',
                'includes_gst' => 0,
                'selected_objects' => '{"events":["3218"],"packages":[]}',
            ),
            23 => 
            array (
                'id' => 170,
                'sub_total' => '150.00',
                'discounts' => '0.00',
                'total' => '150.00',
                'coupon_id' => 0,
                'type' => 'BOOKING',
                'user_id' => 43,
                'activity_id' => 61,
                'activity_name' => 'School Holiday Cricket Club',
                'enrolment_form_id' => 79,
                'invite_id' => 0,
                'status' => 'COMPLETED',
                'cart_id' => '7aafd9ed8cde84a2579e6c54547f942c',
                'pay_key' => 'ch_1B8I0XFDw6nmSmJd8Huskmm2',
                'completed_at' => '2017-10-02 11:12:04',
                'created_at' => '2017-10-02 11:07:23',
                'updated_at' => '2017-10-02 11:12:07',
                'comments' => '',
                'provider_amount' => '150.00',
                'playz_amount' => '0.00',
                'gst_amount' => '0.00',
                'includes_gst' => 0,
                'selected_objects' => '{"events":[],"packages":["141"]}',
            ),
            24 => 
            array (
                'id' => 174,
                'sub_total' => '300.00',
                'discounts' => '0.00',
                'total' => '300.00',
                'coupon_id' => 0,
                'type' => 'BOOKING',
                'user_id' => 70,
                'activity_id' => 91,
                'activity_name' => 'Piano Lessons',
                'enrolment_form_id' => 91,
                'invite_id' => 0,
                'status' => 'COMPLETED',
                'cart_id' => '30e322aa6a7e9f4d6f275778bd8d6338',
                'pay_key' => 'ch_1BJZ3iFDw6nmSmJdBe0x5Cpg',
                'completed_at' => '2017-11-02 13:37:58',
                'created_at' => '2017-11-02 13:36:00',
                'updated_at' => '2017-11-02 13:38:00',
                'comments' => '',
                'provider_amount' => '300.00',
                'playz_amount' => '0.00',
                'gst_amount' => '0.00',
                'includes_gst' => 0,
                'selected_objects' => '{"events":[],"packages":["204"]}',
            ),
            25 => 
            array (
                'id' => 182,
                'sub_total' => '1.00',
                'discounts' => '0.00',
                'total' => '1.00',
                'coupon_id' => 0,
                'type' => 'BOOKING',
                'user_id' => 62,
                'activity_id' => 94,
                'activity_name' => 'Test',
                'enrolment_form_id' => 0,
                'invite_id' => 0,
                'status' => 'COMPLETED',
                'cart_id' => '00c64996a59f479d1fb8e91ddf7e7160',
                'pay_key' => 'ch_1BJs8fFDw6nmSmJdOYQzkOP2',
                'completed_at' => '2017-11-03 10:00:22',
                'created_at' => '2017-11-03 08:49:03',
                'updated_at' => '2017-11-03 10:00:23',
                'comments' => '',
                'provider_amount' => '1.00',
                'playz_amount' => '0.00',
                'gst_amount' => '0.00',
                'includes_gst' => 0,
                'selected_objects' => '{"events":["4395"],"packages":[]}',
            ),
            26 => 
            array (
                'id' => 185,
                'sub_total' => '3.00',
                'discounts' => '0.00',
                'total' => '3.00',
                'coupon_id' => 0,
                'type' => 'BOOKING',
                'user_id' => 70,
                'activity_id' => 95,
                'activity_name' => 'Ceramic Classes',
                'enrolment_form_id' => 94,
                'invite_id' => 0,
                'status' => 'COMPLETED',
                'cart_id' => 'ed84b115e5e22346583137b5876445fb',
                'pay_key' => 'ch_1BJvKKFDw6nmSmJd2qYH2L0L',
                'completed_at' => '2017-11-03 13:24:37',
                'created_at' => '2017-11-03 12:03:47',
                'updated_at' => '2017-11-03 13:24:38',
                'comments' => '',
                'provider_amount' => '3.00',
                'playz_amount' => '0.00',
                'gst_amount' => '0.00',
                'includes_gst' => 0,
                'selected_objects' => '{"events":["4458","4458"],"packages":[]}',
            ),
            27 => 
            array (
                'id' => 190,
                'sub_total' => '3.00',
                'discounts' => '0.00',
                'total' => '3.00',
                'coupon_id' => 0,
                'type' => 'BOOKING',
                'user_id' => 70,
                'activity_id' => 95,
                'activity_name' => 'Ceramic Classes',
                'enrolment_form_id' => 94,
                'invite_id' => 0,
                'status' => 'COMPLETED',
                'cart_id' => '30e322aa6a7e9f4d6f275778bd8d6338',
                'pay_key' => 'ch_1BKwO3FDw6nmSmJdux5XCyer',
                'completed_at' => '2017-11-06 08:44:40',
                'created_at' => '2017-11-06 08:43:18',
                'updated_at' => '2017-11-06 08:49:08',
                'comments' => '',
                'provider_amount' => '3.00',
                'playz_amount' => '0.00',
                'gst_amount' => '0.00',
                'includes_gst' => 0,
                'selected_objects' => '{"events":["4409","4409"],"packages":[]}',
            ),
            28 => 
            array (
                'id' => 192,
                'sub_total' => '1.00',
                'discounts' => '0.00',
                'total' => '1.00',
                'coupon_id' => 0,
                'type' => 'BOOKING',
                'user_id' => 70,
                'activity_id' => 95,
                'activity_name' => 'Ceramic Classes',
                'enrolment_form_id' => 94,
                'invite_id' => 0,
                'status' => 'ACTIVE',
                'cart_id' => 'ed84b115e5e22346583137b5876445fb',
                'pay_key' => 'ch_1BL00DFDw6nmSmJdFOEnyRRH',
                'completed_at' => '2017-11-06 12:36:18',
                'created_at' => '2017-11-06 12:34:59',
                'updated_at' => '2017-11-06 12:36:20',
                'comments' => '',
                'provider_amount' => '1.00',
                'playz_amount' => '0.00',
                'gst_amount' => '0.00',
                'includes_gst' => 0,
                'selected_objects' => '{"events":["4458"],"packages":[]}',
            ),
        ));
        
        
    }
}