<?php

use Illuminate\Database\Seeder;

class PeopleTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('people')->delete();
        
        \DB::table('people')->insert(array (
            0 => 
            array (
                'id' => 379,
                'user_id' => 62,
                'firstname' => 'Ella',
                'lastname' => 'Payne',
                'type' => 'CHILD',
                'dob' => '2005-01-24 09:54:35',
                'parent_id' => 0,
                'order_id' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
                'deleted_at' => NULL,
                'email' => 'kristie+customer@alliancesoftware.com.au',
                'provider_id' => '',
            ),
            1 => 
            array (
                'id' => 380,
                'user_id' => 63,
                'firstname' => 'Ben',
                'lastname' => 'Payne',
                'type' => 'CHILD',
                'dob' => '2007-03-20 09:54:35',
                'parent_id' => 0,
                'order_id' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
                'deleted_at' => NULL,
                'email' => 'kristie+customer@allianceosoftware.com.au',
                'provider_id' => '',
            ),
            2 => 
            array (
                'id' => 381,
                'user_id' => 62,
                'firstname' => 'Nathan',
                'lastname' => 'Payne',
                'type' => 'CHILD',
                'dob' => '2005-02-10 09:57:45',
                'parent_id' => 0,
                'order_id' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
                'deleted_at' => NULL,
                'email' => 'kristie+customer@alliancesoftware.com.au',
                'provider_id' => '',
            ),
            3 => 
            array (
                'id' => 382,
                'user_id' => 62,
                'firstname' => 'Leigh',
                'lastname' => 'Payne',
                'type' => 'CHILD',
                'dob' => '2006-06-28 09:57:45',
                'parent_id' => 0,
                'order_id' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
                'deleted_at' => NULL,
                'email' => 'kristie+customer@alliancesoftware.com.au',
                'provider_id' => '',
            ),
            4 => 
            array (
                'id' => 383,
                'user_id' => 66,
                'firstname' => 'Bart',
                'lastname' => 'Simpson',
                'type' => 'CHILD',
                'dob' => '2004-06-15 11:56:17',
                'parent_id' => 0,
                'order_id' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
                'deleted_at' => NULL,
                'email' => 'r.rmorley71@outlook.com',
                'provider_id' => '',
            ),
            5 => 
            array (
                'id' => 384,
                'user_id' => 68,
                'firstname' => 'Ben',
                'lastname' => 'Payne',
                'type' => 'CHILD',
                'dob' => '2007-05-30 09:39:53',
                'parent_id' => 0,
                'order_id' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
                'deleted_at' => NULL,
                'email' => 'kristie@alliancesoftware.com.au',
                'provider_id' => '',
            ),
            6 => 
            array (
                'id' => 385,
                'user_id' => 62,
                'firstname' => 'Another Child',
                'lastname' => 'Payne',
                'type' => 'CHILD',
                'dob' => '2005-11-16 09:39:53',
                'parent_id' => 0,
                'order_id' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
                'deleted_at' => NULL,
                'email' => 'kristie+customer@alliancesoftware.com.au',
                'provider_id' => '',
            ),
            7 => 
            array (
                'id' => 386,
                'user_id' => 69,
                'firstname' => 'Nathan',
                'lastname' => 'Smith',
                'type' => 'CHILD',
                'dob' => '2008-05-07 09:39:53',
                'parent_id' => 0,
                'order_id' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
                'deleted_at' => NULL,
                'email' => 'kristie+test1@alliancesoftware.com.au',
                'provider_id' => '',
            ),
            8 => 
            array (
                'id' => 387,
                'user_id' => 69,
                'firstname' => 'Leigh',
                'lastname' => 'Smith',
                'type' => 'CHILD',
                'dob' => '2009-02-03 09:39:53',
                'parent_id' => 0,
                'order_id' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
                'deleted_at' => NULL,
                'email' => 'kristie+test1@alliancesoftware.com.au',
                'provider_id' => '',
            ),
            9 => 
            array (
                'id' => 388,
                'user_id' => 70,
                'firstname' => 'Nathan',
                'lastname' => 'Sharp',
                'type' => 'CHILD',
                'dob' => '2001-08-29 00:00:00',
                'parent_id' => 0,
                'order_id' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '2017-11-06 12:35:20',
                'deleted_at' => NULL,
                'email' => 'r.morley71@outlook.com',
                'provider_id' => '',
            ),
            10 => 
            array (
                'id' => 389,
                'user_id' => 70,
                'firstname' => 'Domi',
                'lastname' => 'Sharp',
                'type' => 'CHILD',
                'dob' => '2008-05-19 00:00:00',
                'parent_id' => 0,
                'order_id' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '2017-11-06 08:44:13',
                'deleted_at' => NULL,
                'email' => 'r.morley71@outlook.com',
                'provider_id' => '',
            ),
            11 => 
            array (
                'id' => 390,
                'user_id' => 70,
                'firstname' => 'Lucy',
                'lastname' => 'Sharp',
                'type' => 'CHILD',
                'dob' => '2008-05-19 00:00:00',
                'parent_id' => 0,
                'order_id' => 0,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '2017-11-06 08:44:04',
                'deleted_at' => NULL,
                'email' => 'r.morley71@outlook.com',
                'provider_id' => '',
            ),
            12 => 
            array (
                'id' => 391,
                'user_id' => 70,
                'firstname' => 'Nathan',
                'lastname' => 'Sharp',
                'type' => 'CHILD',
                'dob' => '2001-08-29 09:49:45',
                'parent_id' => 388,
                'order_id' => 174,
                'created_at' => '2017-11-02 13:36:09',
                'updated_at' => '2017-11-02 13:36:09',
                'deleted_at' => NULL,
                'email' => 'r.morley71@outlook.com',
                'provider_id' => '65',
            ),
            13 => 
            array (
                'id' => 392,
                'user_id' => 71,
                'firstname' => 'Ben',
                'lastname' => 'Payne',
                'type' => 'CHILD',
                'dob' => '2007-03-20 00:00:00',
                'parent_id' => 0,
                'order_id' => 0,
                'created_at' => '2017-11-02 15:18:46',
                'updated_at' => '2017-11-02 15:18:46',
                'deleted_at' => NULL,
                'email' => 'kristie+stripe@alliancesoftware.com.au',
                'provider_id' => '',
            ),
            14 => 
            array (
                'id' => 397,
                'user_id' => 61,
                'firstname' => 'te',
                'lastname' => 'st',
                'type' => 'ADULT',
                'dob' => '1980-02-13 00:00:00',
                'parent_id' => 0,
                'order_id' => 0,
                'created_at' => '2017-11-02 15:37:36',
                'updated_at' => '2017-11-02 15:37:36',
                'deleted_at' => NULL,
                'email' => 'kristie+provider@alliancesoftware.com.au',
                'provider_id' => '',
            ),
            15 => 
            array (
                'id' => 400,
                'user_id' => 72,
                'firstname' => 'Child',
                'lastname' => 'Payne',
                'type' => 'CHILD',
                'dob' => '2009-07-01 00:00:00',
                'parent_id' => 0,
                'order_id' => 0,
                'created_at' => '2017-11-02 16:39:00',
                'updated_at' => '2017-11-02 16:39:00',
                'deleted_at' => NULL,
                'email' => 'kristie+customer2@alliancesoftware.com.au',
                'provider_id' => '',
            ),
            16 => 
            array (
                'id' => 402,
                'user_id' => 73,
                'firstname' => '1af',
                'lastname' => 'afew',
                'type' => 'ADULT',
                'dob' => '1990-03-01 00:00:00',
                'parent_id' => 0,
                'order_id' => 0,
                'created_at' => '2017-11-02 16:39:07',
                'updated_at' => '2017-11-02 16:39:07',
                'deleted_at' => NULL,
                'email' => 'fwefw@tempr.email',
                'provider_id' => '',
            ),
            17 => 
            array (
                'id' => 405,
                'user_id' => 62,
                'firstname' => 'Ella',
                'lastname' => 'Payne',
                'type' => 'CHILD',
                'dob' => '2005-01-24 09:54:35',
                'parent_id' => 379,
                'order_id' => 182,
                'created_at' => '2017-11-03 09:59:59',
                'updated_at' => '2017-11-03 09:59:59',
                'deleted_at' => NULL,
                'email' => 'kristie+customer@alliancesoftware.com.au',
                'provider_id' => '71',
            ),
            18 => 
            array (
                'id' => 408,
                'user_id' => 70,
                'firstname' => 'Nathan',
                'lastname' => 'Sharp',
                'type' => 'CHILD',
                'dob' => '2001-08-29 00:00:00',
                'parent_id' => 388,
                'order_id' => 185,
                'created_at' => '2017-11-03 13:22:46',
                'updated_at' => '2017-11-03 13:23:15',
                'deleted_at' => NULL,
                'email' => 'r.morley71@outlook.com',
                'provider_id' => '75',
            ),
            19 => 
            array (
                'id' => 409,
                'user_id' => 70,
                'firstname' => 'Domi',
                'lastname' => 'Sharp',
                'type' => 'CHILD',
                'dob' => '2008-05-19 00:00:00',
                'parent_id' => 389,
                'order_id' => 185,
                'created_at' => '2017-11-03 13:23:23',
                'updated_at' => '2017-11-03 13:23:26',
                'deleted_at' => NULL,
                'email' => 'r.morley71@outlook.com',
                'provider_id' => '75',
            ),
            20 => 
            array (
                'id' => 410,
                'user_id' => 70,
                'firstname' => 'Lucy',
                'lastname' => 'Sharp',
                'type' => 'CHILD',
                'dob' => '2008-05-19 00:00:00',
                'parent_id' => 390,
                'order_id' => 190,
                'created_at' => '2017-11-06 08:43:57',
                'updated_at' => '2017-11-06 08:44:04',
                'deleted_at' => NULL,
                'email' => 'r.morley71@outlook.com',
                'provider_id' => '75',
            ),
            21 => 
            array (
                'id' => 411,
                'user_id' => 70,
                'firstname' => 'Domi',
                'lastname' => 'Sharp',
                'type' => 'CHILD',
                'dob' => '2008-05-19 00:00:00',
                'parent_id' => 389,
                'order_id' => 190,
                'created_at' => '2017-11-06 08:44:10',
                'updated_at' => '2017-11-06 08:44:13',
                'deleted_at' => NULL,
                'email' => 'r.morley71@outlook.com',
                'provider_id' => '75',
            ),
            22 => 
            array (
                'id' => 412,
                'user_id' => 70,
                'firstname' => 'Nathan',
                'lastname' => 'Sharp',
                'type' => 'CHILD',
                'dob' => '2001-08-29 00:00:00',
                'parent_id' => 388,
                'order_id' => 192,
                'created_at' => '2017-11-06 12:35:16',
                'updated_at' => '2017-11-06 12:35:20',
                'deleted_at' => NULL,
                'email' => 'r.morley71@outlook.com',
                'provider_id' => '75',
            ),
        ));
        
        
    }
}