<?php

use Illuminate\Database\Seeder;

class ProviderProcessingEnrollmentsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('provider_processing_enrollments')->delete();
        
        \DB::table('provider_processing_enrollments')->insert(array (
            0 => 
            array (
                'id' => 2,
                'provider_id' => 1,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => NULL,
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-04-24 16:49:13',
                'updated_at' => '2017-04-24 16:49:13',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            1 => 
            array (
                'id' => 8,
                'provider_id' => 2,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => '[]',
                'enrol_to_sessions' => '[16]',
                'enrol_method' => 'EXISTING',
                'invite_process' => 'RESERVATION',
                'invite_message' => '',
                'invite_expiry' => NULL,
                'created_at' => '2017-04-24 20:22:52',
                'updated_at' => '2017-04-24 20:23:15',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            2 => 
            array (
                'id' => 10,
                'provider_id' => 2,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => '[]',
                'enrol_to_sessions' => '[57]',
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-04-24 20:43:28',
                'updated_at' => '2017-04-24 20:43:42',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            3 => 
            array (
                'id' => 15,
                'provider_id' => 5,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-04-25 11:52:53',
                'updated_at' => '2017-04-25 11:52:59',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            4 => 
            array (
                'id' => 16,
                'provider_id' => 5,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => '[3]',
                'enrol_to_sessions' => '[]',
                'enrol_method' => 'EXISTING',
                'invite_process' => 'WAITLIST',
                'invite_message' => '',
                'invite_expiry' => NULL,
                'created_at' => '2017-04-25 12:02:37',
                'updated_at' => '2017-04-25 12:06:38',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            5 => 
            array (
                'id' => 17,
                'provider_id' => 2,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-04-25 12:13:20',
                'updated_at' => '2017-04-25 12:13:24',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            6 => 
            array (
                'id' => 18,
                'provider_id' => 5,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => '[]',
                'enrol_to_sessions' => '[79,80]',
                'enrol_method' => 'EXISTING',
                'invite_process' => 'WAITLIST',
                'invite_message' => '',
                'invite_expiry' => NULL,
                'created_at' => '2017-04-25 12:14:37',
                'updated_at' => '2017-04-25 12:19:31',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            7 => 
            array (
                'id' => 19,
                'provider_id' => 2,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-04-25 12:16:19',
                'updated_at' => '2017-04-25 12:16:24',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            8 => 
            array (
                'id' => 20,
                'provider_id' => 5,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => '[]',
                'enrol_to_sessions' => '[79,80,81]',
                'enrol_method' => 'EXISTING',
                'invite_process' => 'RESERVATION',
                'invite_message' => '',
                'invite_expiry' => NULL,
                'created_at' => '2017-04-25 12:21:40',
                'updated_at' => '2017-04-25 12:22:50',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            9 => 
            array (
                'id' => 21,
                'provider_id' => 5,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-04-25 12:24:37',
                'updated_at' => '2017-04-25 12:24:42',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            10 => 
            array (
                'id' => 22,
                'provider_id' => 5,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => '[4]',
                'enrol_to_sessions' => '[]',
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-04-25 22:23:28',
                'updated_at' => '2017-04-25 22:24:00',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            11 => 
            array (
                'id' => 23,
                'provider_id' => 5,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-04-25 22:24:45',
                'updated_at' => '2017-04-25 22:24:49',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            12 => 
            array (
                'id' => 24,
                'provider_id' => 5,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-04-25 22:25:31',
                'updated_at' => '2017-04-25 22:25:34',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            13 => 
            array (
                'id' => 25,
                'provider_id' => 5,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-04-25 22:27:29',
                'updated_at' => '2017-04-25 22:27:34',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            14 => 
            array (
                'id' => 26,
                'provider_id' => 6,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => '[10]',
                'enrol_to_sessions' => '[]',
                'enrol_method' => 'CREATE',
                'invite_process' => 'RESERVATION',
                'invite_message' => '<listing_provider> has reserved some sessions for you. Here are the summary of the sessions reserved:<br><br>
<summary> <br><br>
To secure this place, please visit the link below to pay.',
                'invite_expiry' => '2017-04-30 00:00:00',
                'created_at' => '2017-04-28 13:12:15',
                'updated_at' => '2017-04-28 13:13:36',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => 8,
            ),
            15 => 
            array (
                'id' => 31,
                'provider_id' => 7,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'CREATE',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-05-01 14:21:28',
                'updated_at' => '2017-05-01 14:21:37',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => 10,
            ),
            16 => 
            array (
                'id' => 32,
                'provider_id' => 7,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => NULL,
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-05-01 14:26:27',
                'updated_at' => '2017-05-01 14:26:27',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            17 => 
            array (
                'id' => 36,
                'provider_id' => 6,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-05-02 10:44:54',
                'updated_at' => '2017-05-02 10:45:03',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            18 => 
            array (
                'id' => 37,
                'provider_id' => 6,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-05-02 10:45:50',
                'updated_at' => '2017-05-02 10:45:57',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            19 => 
            array (
                'id' => 38,
                'provider_id' => 6,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-05-02 10:49:04',
                'updated_at' => '2017-05-02 10:49:08',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            20 => 
            array (
                'id' => 39,
                'provider_id' => 6,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-05-02 10:52:31',
                'updated_at' => '2017-05-02 10:52:37',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            21 => 
            array (
                'id' => 40,
                'provider_id' => 6,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-05-02 10:54:48',
                'updated_at' => '2017-05-02 10:54:53',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            22 => 
            array (
                'id' => 41,
                'provider_id' => 6,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-05-03 10:35:45',
                'updated_at' => '2017-05-03 10:35:48',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            23 => 
            array (
                'id' => 43,
                'provider_id' => 6,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-05-03 10:42:37',
                'updated_at' => '2017-05-03 10:42:41',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            24 => 
            array (
                'id' => 44,
                'provider_id' => 6,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-05-03 10:47:36',
                'updated_at' => '2017-05-03 10:47:39',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            25 => 
            array (
                'id' => 45,
                'provider_id' => 6,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-05-03 10:50:47',
                'updated_at' => '2017-05-03 10:50:51',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            26 => 
            array (
                'id' => 47,
                'provider_id' => 6,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-05-03 10:57:36',
                'updated_at' => '2017-05-03 10:57:36',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            27 => 
            array (
                'id' => 56,
                'provider_id' => 6,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => '[35]',
                'enrol_to_sessions' => '[]',
                'enrol_method' => 'EXISTING',
                'invite_process' => 'WAITLIST',
                'invite_message' => 'You have been waitlisted by <listing_provider> for the following sessions:<br>
<summary><br>
You will be notified when sessions become available.',
                'invite_expiry' => '2017-05-04 00:00:00',
                'created_at' => '2017-05-04 13:48:29',
                'updated_at' => '2017-05-04 13:52:51',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => 15,
            ),
            28 => 
            array (
                'id' => 58,
                'provider_id' => 6,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => NULL,
                'invite_process' => 'MANUAL',
                'invite_message' => '<participant_name> has been manually added to events below. For more details please contact <listing_contact_name> on <listing_contact_phone_number>.<br><br><summary>',
                'invite_expiry' => '1970-01-01 10:00:00',
                'created_at' => '2017-05-04 13:56:04',
                'updated_at' => '2017-05-04 13:56:28',
                'enrol_from_calendar' => 23,
                'enrol_from_listing' => NULL,
            ),
            29 => 
            array (
                'id' => 59,
                'provider_id' => 8,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-05-04 13:58:39',
                'updated_at' => '2017-05-04 13:59:03',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            30 => 
            array (
                'id' => 61,
                'provider_id' => 8,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => '[34,41]',
                'enrol_to_sessions' => '[]',
                'enrol_method' => 'CREATE',
                'invite_process' => 'WAITLIST',
                'invite_message' => 'You have been waitlisted by <listing_provider> for the following sessions:<br>
<summary><br>
You will be notified when sessions become available.',
                'invite_expiry' => '2017-06-03 00:00:00',
                'created_at' => '2017-05-05 13:09:40',
                'updated_at' => '2017-05-05 13:40:01',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            31 => 
            array (
                'id' => 71,
                'provider_id' => 6,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-05-06 07:40:14',
                'updated_at' => '2017-05-06 07:40:18',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            32 => 
            array (
                'id' => 72,
                'provider_id' => 6,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-05-06 07:45:00',
                'updated_at' => '2017-05-06 07:45:00',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            33 => 
            array (
                'id' => 73,
                'provider_id' => 6,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-05-06 07:46:28',
                'updated_at' => '2017-05-06 07:46:32',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            34 => 
            array (
                'id' => 74,
                'provider_id' => 6,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-05-06 07:47:56',
                'updated_at' => '2017-05-06 07:48:00',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            35 => 
            array (
                'id' => 76,
                'provider_id' => 6,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-05-06 07:51:08',
                'updated_at' => '2017-05-06 07:51:13',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            36 => 
            array (
                'id' => 77,
                'provider_id' => 6,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'CREATE',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-05-06 11:56:30',
                'updated_at' => '2017-05-06 11:56:39',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            37 => 
            array (
                'id' => 94,
                'provider_id' => 2,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => NULL,
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-05-11 10:12:26',
                'updated_at' => '2017-05-11 10:12:26',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            38 => 
            array (
                'id' => 95,
                'provider_id' => 2,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => NULL,
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-05-11 11:28:32',
                'updated_at' => '2017-05-11 11:28:32',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            39 => 
            array (
                'id' => 96,
                'provider_id' => 2,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-05-11 11:28:46',
                'updated_at' => '2017-05-11 11:28:50',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            40 => 
            array (
                'id' => 97,
                'provider_id' => 2,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => NULL,
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-05-11 11:33:05',
                'updated_at' => '2017-05-11 11:33:05',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            41 => 
            array (
                'id' => 98,
                'provider_id' => 2,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => NULL,
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-05-11 11:34:55',
                'updated_at' => '2017-05-11 11:34:55',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            42 => 
            array (
                'id' => 99,
                'provider_id' => 2,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-05-11 11:35:40',
                'updated_at' => '2017-05-11 11:47:04',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            43 => 
            array (
                'id' => 100,
                'provider_id' => 2,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-05-11 12:36:33',
                'updated_at' => '2017-05-11 12:36:50',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            44 => 
            array (
                'id' => 101,
                'provider_id' => 2,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => NULL,
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-05-11 12:41:47',
                'updated_at' => '2017-05-11 12:41:47',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            45 => 
            array (
                'id' => 102,
                'provider_id' => 6,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => NULL,
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-05-11 13:37:16',
                'updated_at' => '2017-05-11 13:37:16',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            46 => 
            array (
                'id' => 104,
                'provider_id' => 6,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-05-11 13:38:58',
                'updated_at' => '2017-05-11 13:39:24',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            47 => 
            array (
                'id' => 105,
                'provider_id' => 6,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => NULL,
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-05-11 13:39:29',
                'updated_at' => '2017-05-11 13:39:29',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            48 => 
            array (
                'id' => 107,
                'provider_id' => 6,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-05-11 13:43:08',
                'updated_at' => '2017-05-11 13:43:15',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            49 => 
            array (
                'id' => 108,
                'provider_id' => 6,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => NULL,
                'invite_process' => 'RESERVATION',
                'invite_message' => '<listing_provider> has reserved some sessions for you. Here are the summary of the sessions reserved:<br><br>
<summary> <br><br>
To secure this place, please visit the link below to pay.',
                'invite_expiry' => '2017-07-21 00:00:00',
                'created_at' => '2017-07-21 11:49:51',
                'updated_at' => '2017-07-21 11:50:21',
                'enrol_from_calendar' => 33,
                'enrol_from_listing' => NULL,
            ),
            50 => 
            array (
                'id' => 111,
                'provider_id' => 6,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-07-25 11:17:06',
                'updated_at' => '2017-07-25 11:17:06',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            51 => 
            array (
                'id' => 112,
                'provider_id' => 6,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => '[24]',
                'enrol_to_sessions' => '[]',
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-07-25 11:21:44',
                'updated_at' => '2017-07-25 11:22:24',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            52 => 
            array (
                'id' => 115,
                'provider_id' => 6,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => '[24]',
                'enrol_to_sessions' => '[]',
                'enrol_method' => 'CREATE',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-08-03 12:19:54',
                'updated_at' => '2017-08-03 12:20:28',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            53 => 
            array (
                'id' => 118,
                'provider_id' => 6,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => NULL,
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-08-07 10:38:07',
                'updated_at' => '2017-08-07 10:38:07',
                'enrol_from_calendar' => 38,
                'enrol_from_listing' => NULL,
            ),
            54 => 
            array (
                'id' => 120,
                'provider_id' => 26,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => NULL,
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-08-08 13:45:09',
                'updated_at' => '2017-08-08 13:45:09',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            55 => 
            array (
                'id' => 122,
                'provider_id' => 27,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => NULL,
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-08-09 10:56:31',
                'updated_at' => '2017-08-09 10:56:31',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            56 => 
            array (
                'id' => 123,
                'provider_id' => 27,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-08-09 11:11:51',
                'updated_at' => '2017-08-09 11:11:51',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            57 => 
            array (
                'id' => 124,
                'provider_id' => 26,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-08-09 14:40:13',
                'updated_at' => '2017-08-09 14:40:13',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            58 => 
            array (
                'id' => 125,
                'provider_id' => 26,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => '[71]',
                'enrol_to_sessions' => '[]',
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-08-14 11:52:55',
                'updated_at' => '2017-08-14 11:53:54',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            59 => 
            array (
                'id' => 126,
                'provider_id' => 29,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'CREATE',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-08-24 12:18:29',
                'updated_at' => '2017-08-24 12:18:42',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            60 => 
            array (
                'id' => 127,
                'provider_id' => 29,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => NULL,
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-08-25 10:11:20',
                'updated_at' => '2017-08-25 10:11:20',
                'enrol_from_calendar' => 62,
                'enrol_from_listing' => NULL,
            ),
            61 => 
            array (
                'id' => 130,
                'provider_id' => 29,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'CREATE',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-08-25 11:05:17',
                'updated_at' => '2017-08-25 11:05:23',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            62 => 
            array (
                'id' => 131,
                'provider_id' => 29,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => NULL,
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-08-25 11:51:05',
                'updated_at' => '2017-08-25 11:51:05',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            63 => 
            array (
                'id' => 133,
                'provider_id' => 29,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-08-25 11:52:09',
                'updated_at' => '2017-08-25 11:52:17',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            64 => 
            array (
                'id' => 135,
                'provider_id' => 29,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-08-30 13:43:36',
                'updated_at' => '2017-08-30 13:43:44',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            65 => 
            array (
                'id' => 137,
                'provider_id' => 29,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-08-30 13:47:40',
                'updated_at' => '2017-08-30 13:47:46',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            66 => 
            array (
                'id' => 141,
                'provider_id' => 30,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => NULL,
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-09-05 09:54:13',
                'updated_at' => '2017-09-05 09:54:13',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            67 => 
            array (
                'id' => 142,
                'provider_id' => 30,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'CREATE',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-09-05 12:21:52',
                'updated_at' => '2017-09-05 12:22:04',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            68 => 
            array (
                'id' => 143,
                'provider_id' => 30,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'CREATE',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-09-05 13:44:29',
                'updated_at' => '2017-09-05 13:45:07',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            69 => 
            array (
                'id' => 144,
                'provider_id' => 30,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'CREATE',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-09-05 13:49:32',
                'updated_at' => '2017-09-05 13:49:44',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            70 => 
            array (
                'id' => 145,
                'provider_id' => 30,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'CREATE',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-09-05 14:18:32',
                'updated_at' => '2017-09-05 14:18:39',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            71 => 
            array (
                'id' => 146,
                'provider_id' => 30,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'CREATE',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-09-05 14:21:42',
                'updated_at' => '2017-09-05 14:21:49',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            72 => 
            array (
                'id' => 147,
                'provider_id' => 29,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => NULL,
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-09-06 10:23:23',
                'updated_at' => '2017-09-06 10:23:23',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            73 => 
            array (
                'id' => 148,
                'provider_id' => 29,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-09-06 11:24:18',
                'updated_at' => '2017-09-06 11:24:27',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => 39,
            ),
            74 => 
            array (
                'id' => 149,
                'provider_id' => 29,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-09-06 11:57:47',
                'updated_at' => '2017-09-06 11:58:26',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            75 => 
            array (
                'id' => 150,
                'provider_id' => 21,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => '[]',
                'enrol_to_sessions' => '[1454]',
                'enrol_method' => 'EXISTING',
                'invite_process' => 'WAITLIST',
                'invite_message' => 'You have been waitlisted by <listing_provider> for the following sessions:<br>
<summary><br>
You will be notified when sessions become available.',
                'invite_expiry' => '2017-09-20 00:00:00',
                'created_at' => '2017-09-06 11:58:26',
                'updated_at' => '2017-09-06 12:01:53',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            76 => 
            array (
                'id' => 155,
                'provider_id' => 29,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => '[98]',
                'enrol_to_sessions' => '[]',
                'enrol_method' => 'EXISTING',
                'invite_process' => 'MANUAL',
                'invite_message' => '<participant_name> has been manually added to events below. For more details please contact <listing_contact_name> on <listing_contact_phone_number>.<br><br><summary>',
                'invite_expiry' => '1970-01-01 10:00:00',
                'created_at' => '2017-09-07 14:10:10',
                'updated_at' => '2017-09-07 14:11:09',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => 40,
            ),
            77 => 
            array (
                'id' => 156,
                'provider_id' => 21,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-09-07 15:31:28',
                'updated_at' => '2017-09-07 15:31:34',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            78 => 
            array (
                'id' => 157,
                'provider_id' => 29,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-09-08 09:15:51',
                'updated_at' => '2017-09-08 09:15:59',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            79 => 
            array (
                'id' => 158,
                'provider_id' => 30,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => NULL,
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-09-11 12:29:19',
                'updated_at' => '2017-09-11 12:29:19',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            80 => 
            array (
                'id' => 165,
                'provider_id' => 33,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-09-13 12:29:15',
                'updated_at' => '2017-09-13 12:29:24',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            81 => 
            array (
                'id' => 166,
                'provider_id' => 33,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-09-13 13:35:47',
                'updated_at' => '2017-09-13 13:35:54',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            82 => 
            array (
                'id' => 168,
                'provider_id' => 33,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => NULL,
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-09-13 13:57:55',
                'updated_at' => '2017-09-13 13:57:55',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            83 => 
            array (
                'id' => 171,
                'provider_id' => 33,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-09-13 14:17:04',
                'updated_at' => '2017-09-13 14:17:12',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            84 => 
            array (
                'id' => 172,
                'provider_id' => 33,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => '[]',
                'enrol_to_sessions' => '[1723]',
                'enrol_method' => 'CREATE',
                'invite_process' => 'RESERVATION',
                'invite_message' => '',
                'invite_expiry' => NULL,
                'created_at' => '2017-09-14 09:03:21',
                'updated_at' => '2017-09-14 09:04:09',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            85 => 
            array (
                'id' => 173,
                'provider_id' => 33,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => '[107]',
                'enrol_to_sessions' => '[]',
                'enrol_method' => 'EXISTING',
                'invite_process' => 'RESERVATION',
                'invite_message' => '',
                'invite_expiry' => NULL,
                'created_at' => '2017-09-14 09:08:54',
                'updated_at' => '2017-09-14 09:09:30',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            86 => 
            array (
                'id' => 174,
                'provider_id' => 37,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'CREATE',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-09-14 10:10:42',
                'updated_at' => '2017-09-14 10:10:56',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => 49,
            ),
            87 => 
            array (
                'id' => 176,
                'provider_id' => 38,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => '[110]',
                'enrol_to_sessions' => '[1759]',
                'enrol_method' => 'CREATE',
                'invite_process' => 'NOTIFICATION',
                'invite_message' => 'Hi <participant_name>. This is a notification to let you know that the following sessions are available.<br><br><summary>',
                'invite_expiry' => '0000-00-00 00:00:00',
                'created_at' => '2017-09-14 10:44:55',
                'updated_at' => '2017-09-14 10:46:13',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => 50,
            ),
            88 => 
            array (
                'id' => 177,
                'provider_id' => 38,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => NULL,
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-09-14 10:48:20',
                'updated_at' => '2017-09-14 10:48:20',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            89 => 
            array (
                'id' => 178,
                'provider_id' => 38,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => '[111]',
                'enrol_to_sessions' => '[]',
                'enrol_method' => 'CREATE',
                'invite_process' => 'MANUAL',
                'invite_message' => '',
                'invite_expiry' => NULL,
                'created_at' => '2017-09-14 10:48:22',
                'updated_at' => '2017-09-14 10:51:08',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            90 => 
            array (
                'id' => 179,
                'provider_id' => 33,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => NULL,
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-09-14 13:06:05',
                'updated_at' => '2017-09-14 13:06:05',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            91 => 
            array (
                'id' => 180,
                'provider_id' => 33,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => '[116]',
                'enrol_to_sessions' => '[]',
                'enrol_method' => 'EXISTING',
                'invite_process' => 'RESERVATION',
                'invite_message' => '',
                'invite_expiry' => NULL,
                'created_at' => '2017-09-14 13:06:09',
                'updated_at' => '2017-09-14 13:06:35',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            92 => 
            array (
                'id' => 181,
                'provider_id' => 33,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => '[115]',
                'enrol_to_sessions' => '[]',
                'enrol_method' => 'EXISTING',
                'invite_process' => 'RESERVATION',
                'invite_message' => '',
                'invite_expiry' => NULL,
                'created_at' => '2017-09-14 13:49:31',
                'updated_at' => '2017-09-14 13:50:19',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            93 => 
            array (
                'id' => 182,
                'provider_id' => 33,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => '[116]',
                'enrol_to_sessions' => '[]',
                'enrol_method' => 'CREATE',
                'invite_process' => 'RESERVATION',
                'invite_message' => '',
                'invite_expiry' => NULL,
                'created_at' => '2017-09-14 13:51:37',
                'updated_at' => '2017-09-14 13:52:20',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            94 => 
            array (
                'id' => 183,
                'provider_id' => 33,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => NULL,
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-09-14 15:07:38',
                'updated_at' => '2017-09-14 15:07:38',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            95 => 
            array (
                'id' => 184,
                'provider_id' => 33,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => NULL,
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-09-15 11:33:50',
                'updated_at' => '2017-09-15 11:33:50',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => 52,
            ),
            96 => 
            array (
                'id' => 186,
                'provider_id' => 33,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'CREATE',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-09-18 14:37:11',
                'updated_at' => '2017-09-18 14:37:50',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            97 => 
            array (
                'id' => 189,
                'provider_id' => 40,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-09-19 09:39:00',
                'updated_at' => '2017-09-19 09:39:07',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            98 => 
            array (
                'id' => 192,
                'provider_id' => 40,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-09-19 10:02:07',
                'updated_at' => '2017-09-19 10:02:16',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            99 => 
            array (
                'id' => 193,
                'provider_id' => 40,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-09-19 10:08:18',
                'updated_at' => '2017-09-19 10:08:26',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            100 => 
            array (
                'id' => 197,
                'provider_id' => 33,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-09-19 12:10:03',
                'updated_at' => '2017-09-19 12:10:17',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            101 => 
            array (
                'id' => 198,
                'provider_id' => 40,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-09-19 12:10:56',
                'updated_at' => '2017-09-19 12:11:08',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            102 => 
            array (
                'id' => 199,
                'provider_id' => 33,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-09-19 12:12:10',
                'updated_at' => '2017-09-19 12:12:21',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            103 => 
            array (
                'id' => 200,
                'provider_id' => 33,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-09-19 12:14:17',
                'updated_at' => '2017-09-19 12:14:24',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            104 => 
            array (
                'id' => 201,
                'provider_id' => 33,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => NULL,
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-09-19 12:15:23',
                'updated_at' => '2017-09-19 12:15:23',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            105 => 
            array (
                'id' => 202,
                'provider_id' => 33,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-09-19 12:16:29',
                'updated_at' => '2017-09-19 12:16:38',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            106 => 
            array (
                'id' => 203,
                'provider_id' => 33,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'CREATE',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-09-19 12:26:13',
                'updated_at' => '2017-09-19 12:27:36',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            107 => 
            array (
                'id' => 205,
                'provider_id' => 40,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => NULL,
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-09-19 13:49:37',
                'updated_at' => '2017-09-19 13:49:37',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            108 => 
            array (
                'id' => 206,
                'provider_id' => 40,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => NULL,
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-09-19 13:49:40',
                'updated_at' => '2017-09-19 13:49:40',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            109 => 
            array (
                'id' => 207,
                'provider_id' => 40,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => '[]',
                'enrol_to_sessions' => '[2031]',
                'enrol_method' => 'EXISTING',
                'invite_process' => 'WAITLIST',
                'invite_message' => 'You have been waitlisted by <listing_provider> for the following sessions:<br>
<summary><br>
You will be notified when sessions become available.',
                'invite_expiry' => '0000-00-00 00:00:00',
                'created_at' => '2017-09-19 13:49:42',
                'updated_at' => '2017-09-19 13:50:23',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            110 => 
            array (
                'id' => 209,
                'provider_id' => 33,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-09-19 15:31:05',
                'updated_at' => '2017-09-19 15:31:28',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            111 => 
            array (
                'id' => 210,
                'provider_id' => 37,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-09-21 11:57:29',
                'updated_at' => '2017-09-21 11:57:29',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            112 => 
            array (
                'id' => 211,
                'provider_id' => 37,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-09-21 12:18:38',
                'updated_at' => '2017-09-21 12:18:38',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            113 => 
            array (
                'id' => 214,
                'provider_id' => 45,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-09-25 14:27:59',
                'updated_at' => '2017-09-25 14:28:08',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            114 => 
            array (
                'id' => 219,
                'provider_id' => 41,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-09-27 14:00:34',
                'updated_at' => '2017-09-27 14:00:42',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            115 => 
            array (
                'id' => 221,
                'provider_id' => 45,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => NULL,
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-09-27 15:15:25',
                'updated_at' => '2017-09-27 15:15:25',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            116 => 
            array (
                'id' => 223,
                'provider_id' => 41,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-09-27 17:23:46',
                'updated_at' => '2017-09-27 17:23:56',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            117 => 
            array (
                'id' => 225,
                'provider_id' => 41,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => '[145]',
                'enrol_to_sessions' => '[]',
                'enrol_method' => 'CREATE',
                'invite_process' => 'RESERVATION',
                'invite_message' => '<listing_provider> has reserved the following activity.<br><br>
<summary> <br><br>
These reservation will expire on <expiry_date> and activities may be offered to someone else on the waitlist. 
<br><br>
To secure your place, please visit links provided to confirm you are attending and pay.
<br><br>
',
                'invite_expiry' => '2017-09-30 00:00:00',
                'created_at' => '2017-09-28 07:22:35',
                'updated_at' => '2017-09-28 07:24:31',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            118 => 
            array (
                'id' => 230,
                'provider_id' => 41,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => '[124]',
                'enrol_to_sessions' => '[]',
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-09-28 09:39:05',
                'updated_at' => '2017-09-28 09:40:43',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            119 => 
            array (
                'id' => 233,
                'provider_id' => 41,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'CREATE',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-09-30 11:55:00',
                'updated_at' => '2017-09-30 11:55:08',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            120 => 
            array (
                'id' => 238,
                'provider_id' => 33,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => NULL,
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-10-10 09:38:44',
                'updated_at' => '2017-10-10 09:38:44',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            121 => 
            array (
                'id' => 246,
                'provider_id' => 33,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-10-13 14:40:05',
                'updated_at' => '2017-10-13 14:40:20',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            122 => 
            array (
                'id' => 249,
                'provider_id' => 33,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-10-16 08:36:26',
                'updated_at' => '2017-10-16 08:36:33',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            123 => 
            array (
                'id' => 250,
                'provider_id' => 33,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-10-16 08:40:25',
                'updated_at' => '2017-10-16 08:40:29',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            124 => 
            array (
                'id' => 252,
                'provider_id' => 33,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-10-16 08:43:02',
                'updated_at' => '2017-10-16 08:43:10',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            125 => 
            array (
                'id' => 255,
                'provider_id' => 33,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-10-16 09:37:43',
                'updated_at' => '2017-10-16 09:37:50',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            126 => 
            array (
                'id' => 256,
                'provider_id' => 45,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => NULL,
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-10-19 11:55:31',
                'updated_at' => '2017-10-19 11:55:31',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            127 => 
            array (
                'id' => 260,
                'provider_id' => 61,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-10-25 09:56:01',
                'updated_at' => '2017-10-25 09:56:13',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            128 => 
            array (
                'id' => 263,
                'provider_id' => 65,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => '[211]',
                'enrol_to_sessions' => '[]',
                'enrol_method' => 'CREATE',
                'invite_process' => 'MANUAL',
                'invite_message' => '',
                'invite_expiry' => NULL,
                'created_at' => '2017-10-27 11:38:33',
                'updated_at' => '2017-10-27 12:00:06',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            129 => 
            array (
                'id' => 268,
                'provider_id' => 61,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => NULL,
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-11-02 14:44:24',
                'updated_at' => '2017-11-02 14:44:24',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
            130 => 
            array (
                'id' => 270,
                'provider_id' => 75,
                'selected_sessions' => NULL,
                'selected_packages' => NULL,
                'enrol_to_packages' => NULL,
                'enrol_to_sessions' => NULL,
                'enrol_method' => 'EXISTING',
                'invite_process' => '',
                'invite_message' => NULL,
                'invite_expiry' => NULL,
                'created_at' => '2017-11-04 16:42:56',
                'updated_at' => '2017-11-04 16:43:00',
                'enrol_from_calendar' => NULL,
                'enrol_from_listing' => NULL,
            ),
        ));
        
        
    }
}