<?php

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 4,
                'email' => 'support@trueagency.com.au',
                'password' => '$2y$10$0l3zwdNZMz0zBkjP5d9Ys.w43GLFBSuYif7qykSYkv39tNs.43eIm',
                'firstname' => 'True',
                'lastname' => 'Agency',
                'business_name' => '',
                'business_slug' => '',
                'address_1' => '',
                'address_2' => NULL,
                'suburb' => '',
                'state' => '',
                'postcode' => '3181',
                'country' => '',
                'phone_number' => '',
                'status' => 'ACTIVE',
                'registration_status' => '',
                'type' => 'SUPER',
                'remember_token' => 'Jio9bXlQywtOxbTNrbXbCxSqw1YHvMhCHvIjpkoBovrLlqMmfZmv5Nm3foFj',
                'reset_password' => NULL,
                'last_seen' => '2017-05-04 13:33:32',
                'created_at' => '2017-04-24 18:33:28',
                'updated_at' => '2017-05-04 13:03:32',
                'verify_token' => 'DT3eVmFNfeZWj16ITKS3vD9ws9Bx1fhQybQiYoLp',
                'facebook_uid' => NULL,
                'google_uid' => NULL,
                'gst_registered' => 0,
                'stripe_user_id' => NULL,
            ),
            1 => 
            array (
                'id' => 24,
                'email' => 'kristie+admin@alliancesoftware.com.au',
                'password' => '$2y$10$KwrgiRxx7H8XOgvf09z2DudpZbCJfmCsw2jD5oet3cupS9gquyqH6',
                'firstname' => 'Testing',
                'lastname' => 'Provider',
                'business_name' => '',
                'business_slug' => '',
                'address_1' => '',
                'address_2' => NULL,
                'suburb' => '',
                'state' => '',
                'postcode' => '',
                'country' => '',
                'phone_number' => '',
                'status' => 'ACTIVE',
                'registration_status' => 'PROVIDER_VERIFIED',
                'type' => 'SUPER',
                'remember_token' => 'fqmnwCmKEcc5Y8VlqfYoQKNMj3QU1ywrc3iGy0Z8UaA6dgDF5TmWlu1XkiTm',
                'reset_password' => NULL,
                'last_seen' => '2017-11-03 15:51:40',
                'created_at' => '2017-07-31 11:39:28',
                'updated_at' => '2017-11-03 15:21:40',
                'verify_token' => NULL,
                'facebook_uid' => NULL,
                'google_uid' => NULL,
                'gst_registered' => 0,
                'stripe_user_id' => NULL,
            ),
            2 => 
            array (
                'id' => 25,
                'email' => 'admin@playz.com.au',
                'password' => '$2y$10$6gGxQ2HQYEiq8XKlEv5.xOWCrQdt1os8Qi2w8vtCvl.PYTrtF2WgS',
                'firstname' => 'Rachel',
                'lastname' => 'Morley',
                'business_name' => '',
                'business_slug' => '',
                'address_1' => '',
                'address_2' => NULL,
                'suburb' => '',
                'state' => '',
                'postcode' => '',
                'country' => '',
                'phone_number' => '',
                'status' => 'ACTIVE',
                'registration_status' => '',
                'type' => 'SUPER',
                'remember_token' => 'qBOevnO91FUnsNjlfGINfjSRR2ExYyIm4QsnefmRXlBPHBy2Io8vo2Xfaq5x',
                'reset_password' => NULL,
                'last_seen' => '2017-11-06 16:53:30',
                'created_at' => '2017-08-02 13:55:20',
                'updated_at' => '2017-11-06 16:23:30',
                'verify_token' => NULL,
                'facebook_uid' => NULL,
                'google_uid' => NULL,
                'gst_registered' => 0,
                'stripe_user_id' => NULL,
            ),
            3 => 
            array (
                'id' => 60,
                'email' => 'rachel+1@playz.com.au',
                'password' => '$2y$10$TUQ/DgL0V0vieIN1FUztXeVNttuZ1C9FR7EWtYZ/QJ1IT7qOPqc0i',
                'firstname' => 'Rachel+1',
                'lastname' => 'Morley',
                'business_name' => 'Magic Music Lessons',
                'business_slug' => 'magic-music-lessons',
                'address_1' => '3 Doris St',
                'address_2' => '',
                'suburb' => 'North Sydney',
                'state' => 'NSW',
                'postcode' => '2060',
                'country' => '',
                'phone_number' => '1213123123',
                'status' => 'ACTIVE',
                'registration_status' => 'PROVIDER_PUBLISHED',
                'type' => 'PROVIDER',
                'remember_token' => 'csHkwIJciPSKAjqL2IMikplI3AUCY5k2bFsGkoBSlH8KJX9ty7eBDwx8F1Dv',
                'reset_password' => NULL,
                'last_seen' => '2017-10-27 12:59:01',
                'created_at' => '2017-10-24 10:32:20',
                'updated_at' => '2017-10-27 12:29:01',
                'verify_token' => NULL,
                'facebook_uid' => NULL,
                'google_uid' => NULL,
                'gst_registered' => 0,
                'stripe_user_id' => 'acct_1BGHPOKPfNoeSx6v',
            ),
            4 => 
            array (
                'id' => 61,
                'email' => 'kristie+provider@alliancesoftware.com.au',
                'password' => '$2y$10$ZLbZ.52RtRB3ipZ4TKVu0uiGiI1y/cAwL8GZPemdiv7uu7Q.aAEqK',
                'firstname' => 'Kristie',
                'lastname' => 'Provider',
                'business_name' => 'Kristie\'s Awesome organisation',
                'business_slug' => 'kristies-awesome-organisation',
                'address_1' => '1/234 Maroondah Highway',
                'address_2' => '',
                'suburb' => 'Nunawading',
                'state' => 'VIC',
                'postcode' => '3131',
                'country' => '',
                'phone_number' => '99557000',
                'status' => 'ACTIVE',
                'registration_status' => 'COMPLETE',
                'type' => 'PROVIDER',
                'remember_token' => 'OgrLjQQL3zBviAixxZ8vcBdpKrjE3gBUSJT7jzvjkYzY7WRRmDxqhhVGWXXt',
                'reset_password' => NULL,
                'last_seen' => '2017-11-02 15:20:54',
                'created_at' => '2017-10-25 09:01:00',
                'updated_at' => '2017-11-02 14:50:54',
                'verify_token' => NULL,
                'facebook_uid' => NULL,
                'google_uid' => NULL,
                'gst_registered' => 0,
                'stripe_user_id' => 'acct_1BGbCSID5WUZFjzy',
            ),
            5 => 
            array (
                'id' => 62,
                'email' => 'kristie+customer@alliancesoftware.com.au',
                'password' => '$2y$10$TKqZQnk3FbH7jDSlRGOmSe8rJtHs.Pwhui5CkfNeE8gze0OvcZzOe',
                'firstname' => 'Kristie',
                'lastname' => 'Payne',
                'business_name' => '',
                'business_slug' => '',
                'address_1' => '',
                'address_2' => NULL,
                'suburb' => '',
                'state' => '',
                'postcode' => '3070',
                'country' => '',
                'phone_number' => '',
                'status' => 'ACTIVE',
                'registration_status' => '',
                'type' => 'MEMBER',
                'remember_token' => '7OaieSrb9NyqAdf3B7enRQcnOU5FxDtLC8solAQCjRTTwaQMz6UJjuokUX4X',
                'reset_password' => NULL,
                'last_seen' => '2017-11-03 15:46:56',
                'created_at' => '2017-10-25 09:10:40',
                'updated_at' => '2017-11-03 15:16:56',
                'verify_token' => NULL,
                'facebook_uid' => NULL,
                'google_uid' => NULL,
                'gst_registered' => 0,
                'stripe_user_id' => NULL,
            ),
            6 => 
            array (
                'id' => 63,
                'email' => 'kristie+customer@allianceosoftware.com.au',
                'password' => '',
                'firstname' => 'Ben',
                'lastname' => 'Payne',
                'business_name' => '',
                'business_slug' => '',
                'address_1' => '',
                'address_2' => NULL,
                'suburb' => '',
                'state' => '',
                'postcode' => '',
                'country' => '',
                'phone_number' => '',
                'status' => 'ACTIVE',
                'registration_status' => '',
                'type' => '',
                'remember_token' => NULL,
                'reset_password' => NULL,
                'last_seen' => NULL,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
                'verify_token' => NULL,
                'facebook_uid' => NULL,
                'google_uid' => NULL,
                'gst_registered' => 0,
                'stripe_user_id' => NULL,
            ),
            7 => 
            array (
                'id' => 64,
                'email' => 'rachel+2@playz.com.au',
                'password' => '$2y$10$2WgvbjvMx55/CVowxI4ghO6YqKm9.BduCd5xo5gi5pJ42pb188bf6',
                'firstname' => 'Sonny',
                'lastname' => 'Dayz',
                'business_name' => 'Sunnytime Kids\' Classes',
                'business_slug' => 'sunnytime-kids-classes',
                'address_1' => '14 Ash Grove',
                'address_2' => '',
                'suburb' => 'Malvern East',
                'state' => 'VIC',
                'postcode' => '3145',
                'country' => '',
                'phone_number' => '182763187263183',
                'status' => 'ACTIVE',
                'registration_status' => 'COMPLETE',
                'type' => 'PROVIDER',
                'remember_token' => 'lnvYPG2jMpwLptgpQhKKyHk5NmVdmuBVFirTsJDcrNWlTksbVy1CmgyoSuZj',
                'reset_password' => NULL,
                'last_seen' => '2017-11-03 12:19:28',
                'created_at' => '2017-10-25 11:54:52',
                'updated_at' => '2017-11-03 11:49:28',
                'verify_token' => NULL,
                'facebook_uid' => NULL,
                'google_uid' => NULL,
                'gst_registered' => 0,
                'stripe_user_id' => 'acct_1BGHPOKPfNoeSx6v',
            ),
            8 => 
            array (
                'id' => 65,
                'email' => 'rachel+3@playz.com.au',
                'password' => '$2y$10$wQoJdCLIFHLTuTCsWZNe9u2w8CozZobCL/2UIDZeS49vFtd3jKCK6',
                'firstname' => 'Penny',
                'lastname' => 'Pianissimo',
                'business_name' => 'Penny\'s Piano Lessons',
                'business_slug' => 'pennys-piano-lessons',
                'address_1' => '9 Murralah Place',
                'address_2' => '',
                'suburb' => 'Lane Cove',
                'state' => 'NSW',
                'postcode' => '2066',
                'country' => '',
                'phone_number' => '123123123132123',
                'status' => 'ACTIVE',
                'registration_status' => 'COMPLETE',
                'type' => 'PROVIDER',
                'remember_token' => 'qNyg1JXvRrtjMlxHuCkpQdZuxnlzJa6gNZPJyyqXQukswjdnxYNpeDRckR5J',
                'reset_password' => NULL,
                'last_seen' => '2017-11-04 16:40:36',
                'created_at' => '2017-10-26 09:58:56',
                'updated_at' => '2017-11-04 16:10:36',
                'verify_token' => NULL,
                'facebook_uid' => NULL,
                'google_uid' => NULL,
                'gst_registered' => 0,
                'stripe_user_id' => 'acct_1BH0yTB7JAFnh1aa',
            ),
            9 => 
            array (
                'id' => 66,
                'email' => 'r.rmorley71@outlook.com',
                'password' => '',
                'firstname' => 'Bart',
                'lastname' => 'Simpson',
                'business_name' => '',
                'business_slug' => '',
                'address_1' => '',
                'address_2' => NULL,
                'suburb' => '',
                'state' => '',
                'postcode' => '',
                'country' => '',
                'phone_number' => '',
                'status' => 'ACTIVE',
                'registration_status' => '',
                'type' => '',
                'remember_token' => NULL,
                'reset_password' => NULL,
                'last_seen' => NULL,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
                'verify_token' => NULL,
                'facebook_uid' => NULL,
                'google_uid' => NULL,
                'gst_registered' => 0,
                'stripe_user_id' => NULL,
            ),
            10 => 
            array (
                'id' => 67,
                'email' => 'rachel+4@playz.com.au',
                'password' => '$2y$10$pkcFQN1/.mozx9492sedoeaF7g6VcxLNWMW7pzRtc7lcNNaDUiPm2',
                'firstname' => 'Tim',
                'lastname' => 'Raquet',
                'business_name' => 'Tim\'s Tennis',
                'business_slug' => 'tims-tennis',
                'address_1' => '14 Ash GRove',
                'address_2' => '',
                'suburb' => 'Malvern East',
                'state' => 'VIC',
                'postcode' => '3145',
                'country' => '',
                'phone_number' => '19283129387',
                'status' => 'ACTIVE',
                'registration_status' => 'DASHBOARD',
                'type' => 'PROVIDER',
                'remember_token' => 'xa3CnMjO4mAjb3ItmnYfkbHMMSa27zYLrFyD12dKeKHbZ1DklPttG5Ea2gYD',
                'reset_password' => NULL,
                'last_seen' => '2017-10-31 09:39:49',
                'created_at' => '2017-10-31 09:09:48',
                'updated_at' => '2017-10-31 09:11:44',
                'verify_token' => NULL,
                'facebook_uid' => NULL,
                'google_uid' => NULL,
                'gst_registered' => 0,
                'stripe_user_id' => NULL,
            ),
            11 => 
            array (
                'id' => 68,
                'email' => 'kristie@alliancesoftware.com.au',
                'password' => '',
                'firstname' => 'Ben',
                'lastname' => 'Payne',
                'business_name' => '',
                'business_slug' => '',
                'address_1' => '',
                'address_2' => NULL,
                'suburb' => '',
                'state' => '',
                'postcode' => '',
                'country' => '',
                'phone_number' => '',
                'status' => 'ACTIVE',
                'registration_status' => '',
                'type' => '',
                'remember_token' => NULL,
                'reset_password' => NULL,
                'last_seen' => NULL,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
                'verify_token' => NULL,
                'facebook_uid' => NULL,
                'google_uid' => NULL,
                'gst_registered' => 0,
                'stripe_user_id' => NULL,
            ),
            12 => 
            array (
                'id' => 69,
                'email' => 'kristie+test1@alliancesoftware.com.au',
                'password' => '',
                'firstname' => 'Nathan',
                'lastname' => 'Smith',
                'business_name' => '',
                'business_slug' => '',
                'address_1' => '',
                'address_2' => NULL,
                'suburb' => '',
                'state' => '',
                'postcode' => '',
                'country' => '',
                'phone_number' => '',
                'status' => 'ACTIVE',
                'registration_status' => '',
                'type' => '',
                'remember_token' => NULL,
                'reset_password' => NULL,
                'last_seen' => NULL,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
                'verify_token' => NULL,
                'facebook_uid' => NULL,
                'google_uid' => NULL,
                'gst_registered' => 0,
                'stripe_user_id' => NULL,
            ),
            13 => 
            array (
                'id' => 70,
                'email' => 'r.morley71@outlook.com',
                'password' => '$2y$10$Wh9R75hsTIJEg035vLCJtudXMPehtQYoDXhIhiP73nVa7qGjUTRoe',
                'firstname' => 'Rachel',
                'lastname' => 'Morley',
                'business_name' => '',
                'business_slug' => '',
                'address_1' => 'line1',
                'address_2' => 'line2',
                'suburb' => '',
                'state' => '',
                'postcode' => '3145',
                'country' => '',
                'phone_number' => '',
                'status' => 'ACTIVE',
                'registration_status' => '',
                'type' => 'MEMBER',
                'remember_token' => 'f8azHwtFrVwjDLW2lfELTsMb8aNhawL593f7q1U79bxsJPXhP8q8xqTAIYo8',
                'reset_password' => NULL,
                'last_seen' => '2017-11-08 14:32:18',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '2017-11-08 14:02:18',
                'verify_token' => NULL,
                'facebook_uid' => NULL,
                'google_uid' => NULL,
                'gst_registered' => 0,
                'stripe_user_id' => NULL,
            ),
            14 => 
            array (
                'id' => 71,
                'email' => 'kristie+stripe@alliancesoftware.com.au',
                'password' => '$2y$10$yoRrR5VPLilLODiby5FR.ut1qQ..Npffepifq./og0kguzRYBZWDq',
                'firstname' => 'Kristie',
                'lastname' => 'ProviderStripe',
                'business_name' => 'Test',
                'business_slug' => 'test',
                'address_1' => '1/234 maroondah highway',
                'address_2' => '',
                'suburb' => 'Nunawading',
                'state' => 'VIC',
                'postcode' => '3130',
                'country' => '',
                'phone_number' => '99557000',
                'status' => 'ACTIVE',
                'registration_status' => 'COMPLETE',
                'type' => 'PROVIDER',
                'remember_token' => 'ejq3dOrIOdy0EeAz3EyIaNbeX3tvvdaxVzjTHoqwHMXTrmgVSu3YiXD6cka3',
                'reset_password' => NULL,
                'last_seen' => '2017-11-03 15:46:27',
                'created_at' => '2017-11-02 14:53:11',
                'updated_at' => '2017-11-03 15:16:27',
                'verify_token' => NULL,
                'facebook_uid' => NULL,
                'google_uid' => NULL,
                'gst_registered' => 0,
                'stripe_user_id' => 'acct_1BJaLpL3QzjrCr0O',
            ),
            15 => 
            array (
                'id' => 72,
                'email' => 'kristie+customer2@alliancesoftware.com.au',
                'password' => '$2y$10$BnO9KVCh5vace/GlzCPlROu253RReT12r0LusFaIRH4OUvP2Rpd8O',
                'firstname' => 'Kristie',
                'lastname' => 'Customer2',
                'business_name' => '',
                'business_slug' => '',
                'address_1' => '',
                'address_2' => NULL,
                'suburb' => '',
                'state' => '',
                'postcode' => '3130',
                'country' => '',
                'phone_number' => '',
                'status' => 'ACTIVE',
                'registration_status' => '',
                'type' => 'MEMBER',
                'remember_token' => 'WmtVESJgih25WrdXgBf0UualOWf5zjl6wmsQPMGMIYKAgfv5ZJUH2eNvnQK4',
                'reset_password' => NULL,
                'last_seen' => '2017-11-02 17:25:36',
                'created_at' => '2017-11-02 16:37:31',
                'updated_at' => '2017-11-02 16:55:36',
                'verify_token' => NULL,
                'facebook_uid' => NULL,
                'google_uid' => NULL,
                'gst_registered' => 0,
                'stripe_user_id' => NULL,
            ),
            16 => 
            array (
                'id' => 73,
                'email' => 'fwefw@tempr.email',
                'password' => '$2y$10$8B7Ux/Af/p/S7n0T8P64.uYHw8fcFAMLJs/VKoucieJeZ8nfDkg7O',
                'firstname' => 'af',
                'lastname' => 'af',
                'business_name' => '',
                'business_slug' => '',
                'address_1' => '',
                'address_2' => NULL,
                'suburb' => '',
                'state' => '',
                'postcode' => '1231',
                'country' => '',
                'phone_number' => '',
                'status' => 'ACTIVE',
                'registration_status' => '',
                'type' => 'MEMBER',
                'remember_token' => 'yFaC4STNcj7JMUX7BuRbSu82FrLpoXC5V9uJtxXme0oA8I5csFVjIoOlQ3gp',
                'reset_password' => NULL,
                'last_seen' => '2017-11-03 15:16:30',
                'created_at' => '2017-11-02 16:38:22',
                'updated_at' => '2017-11-03 14:46:30',
                'verify_token' => NULL,
                'facebook_uid' => NULL,
                'google_uid' => NULL,
                'gst_registered' => 0,
                'stripe_user_id' => NULL,
            ),
            17 => 
            array (
                'id' => 74,
                'email' => 'kristie+provider3@alliancesoftware.com.au',
                'password' => '$2y$10$vu.j7PmKP/kgXVh8lcLg5unYBwyxHzEe8fzMKzdzUy9q7KV435Yv2',
                'firstname' => 'Kristie',
                'lastname' => 'Provider3',
                'business_name' => 'Stripe Live Account',
                'business_slug' => 'stripe-live-account',
                'address_1' => '1/234 Maroondah Highway',
                'address_2' => '',
                'suburb' => 'Nunawading',
                'state' => 'VIC',
                'postcode' => '3131',
                'country' => '',
                'phone_number' => '99557000',
                'status' => 'ACTIVE',
                'registration_status' => 'COMPLETE',
                'type' => 'PROVIDER',
                'remember_token' => 'zCpDI5tyzM16igblaqbwnK0mRuOJRLcbvezBKarXx0DHiEKVBVMQUtl7oqwp',
                'reset_password' => NULL,
                'last_seen' => '2017-11-03 10:27:05',
                'created_at' => '2017-11-03 09:21:25',
                'updated_at' => '2017-11-03 09:57:05',
                'verify_token' => NULL,
                'facebook_uid' => NULL,
                'google_uid' => NULL,
                'gst_registered' => 0,
                'stripe_user_id' => NULL,
            ),
            18 => 
            array (
                'id' => 75,
                'email' => 'j_sharp70@bigpond.com',
                'password' => '$2y$10$uRdRYy25GKQFH31iIbHd1uT3klS8rfi63fYpOQmuTHwM3dcwzJ4AW',
                'firstname' => 'Jeff - Stripe',
                'lastname' => 'Sharp',
                'business_name' => 'Crafty Critters',
                'business_slug' => 'crafty-critters',
                'address_1' => '14 Ash Grove',
                'address_2' => '',
                'suburb' => 'Malvern East',
                'state' => 'VIC',
                'postcode' => '3145',
                'country' => '',
                'phone_number' => '0407 968 221',
                'status' => 'ACTIVE',
                'registration_status' => 'COMPLETE',
                'type' => 'PROVIDER',
                'remember_token' => 'UVU99EtD198cVkm7NEl1erEqJPEEENGx77TDwT1dqADsiTqUtv0EEocrw3oj',
                'reset_password' => NULL,
                'last_seen' => '2017-11-08 09:45:45',
                'created_at' => '2017-11-03 12:31:53',
                'updated_at' => '2017-11-08 09:15:45',
                'verify_token' => NULL,
                'facebook_uid' => NULL,
                'google_uid' => NULL,
                'gst_registered' => 0,
                'stripe_user_id' => 'acct_1BJufsDTAqbkYnKJ',
            ),
            19 => 
            array (
                'id' => 76,
                'email' => 'rachel+5@playz.com.au',
                'password' => '$2y$10$BQlAWY.Z.2Mo3UhGDKBwSOXqugj6IMLblRjh.vRNHMr/Hg4vD09jq',
                'firstname' => 'Fiona',
                'lastname' => 'Flortist',
                'business_name' => 'Fiona\'s Flut lessons',
                'business_slug' => 'fionas-flut-lessons',
                'address_1' => '14 Ash Grove',
                'address_2' => '',
                'suburb' => 'Malvern East',
                'state' => 'VIC',
                'postcode' => '3145',
                'country' => '',
                'phone_number' => '182736182736',
                'status' => 'ACTIVE',
                'registration_status' => 'DASHBOARD',
                'type' => 'PROVIDER',
                'remember_token' => 'r2TmU5JV78iiOc7aZDoeK7ttRWsHRQdPWFjyziGys4yu6NxQEPteSgHLf8VP',
                'reset_password' => NULL,
                'last_seen' => '2017-11-06 14:33:03',
                'created_at' => '2017-11-06 13:30:48',
                'updated_at' => '2017-11-06 14:03:03',
                'verify_token' => NULL,
                'facebook_uid' => NULL,
                'google_uid' => NULL,
                'gst_registered' => 0,
                'stripe_user_id' => NULL,
            ),
        ));
        
        
    }
}