<?php 
 return array (
  'CLIENT_ID' => 'rwpgp4ny7zhcfjju6zafaetv',
  'CLIENT_SECRET' => 'Fde32ZS5BV',
  'CODE' => 'xzsfr7a2b7euekcx53uf3msa',
  'ACCESS_TOKEN' => 'ynxj2pev7xv5qt7aphjkuz6q',
  'EXPIRES_IN' => 86400,
  'TOKEN_TYPE' => 'bearer',
  'REFRESH_TOKEN' => 'revybjfcfu2m5dp2u7sr2fr4',
  'SCOPE' => 'read write execute|rm379.infusionsoft.com',
  'REDIRECT_URI' => 'http://localhost/playz/public/infusionsoft/auth/redirect   ',
  'ERROR_EMAIL' => 'sunil@playz.com',
  'MEMBER' => 
  array (
    'id' => '_WPUserId',
    'email' => 'Email',
    'firstname' => 'FirstName',
    'lastname' => 'LastName',
    'address_1' => 'StreetAddress1',
    'address_2' => 'StreetAddress2',
    'suburb' => 'City',
    'state' => 'State',
    'postcode' => 'PostalCode',
    'country' => 'Country',
    'phone_number' => 'Phone1',
    'firstname1' => '_FirstName0',
    'lastname1' => '_Child1Surname',
    'dob1' => '_Child1DOB0',
    'firstname2' => '_Child2FirstName',
    'lastname2' => '_Child2Surname',
    'dob2' => '_Child2DOB',
    'firstname3' => '_Child3FirstName',
    'lastname3' => '_Child3Surname',
    'dob3' => '_Child3DOB',
    'firstname4' => '_Child4FirstName',
    'lastname4' => '_Child4Surname',
    'dob4' => '_Child4DOB',
    'firstname5' => '_Child5FirstName',
    'lastname5' => '_Child5Surname',
    'dob5' => '_Child5DOB',
    'activity_name' => '_NextMostRecentBookingActivityName',
    'activity_time' => '_NextMostRecentBookingDateTime',
  ),
  'PROVIDER' => 
  array (
    'id' => '_WPUserId',
    'email' => 'Email',
    'firstname' => 'FirstName',
    'lastname' => 'LastName',
    'business_name' => 'Company',
    'address_1' => 'StreetAddress1',
    'address_2' => 'StreetAddress2',
    'suburb' => 'City',
    'state' => 'State',
    'postcode' => 'PostalCode',
    'country' => 'Country',
    'phone_number' => 'Phone1',
    'website' => 'Website',
    'provider_profile_page' => '_ProviderProfilePage',
    'membership_level' => '_MembershipLevel',
    'activity_types_offered' => '_ActivityTypesOffered0',
    'Numberofpageviews' => '_Numberofpageviews',
    'Numberofcustomerinquiries' => '_Numberofcustomerinquiries',
    'Numberofordersreceived' => '_Numberofordersreceived',
  ),
  'ACTIVITY_TAGS' => 
  array (
    'Fun Linkz' => 193,
    'Parties Linkz' => 187,
    'Classes Linkz' => 181,
    'Holiday Linkz' => 175,
    'Fun Listings' => 195,
    'Parties Listings' => 189,
    'Classes Listings' => 183,
    'Holiday Listings' => 177,
    'Fun Workz' => 191,
    'Parties Workz' => 185,
    'Classes Workz' => 179,
    'Holiday Workz' => 173,
  ),
  'STAGE_TAGS' => 
  array (
    'Verify Your Account' => 197,
    'Your Business Details' => 103,
    'Your Activity Details' => 105,
    'Your Timetable Details' => 107,
    'Publish Your Details' => 109,

    '1' => 197,
    '2' => 103,
    '3' => 105,
    '4' => 107,
    '5' => 109,
  ),
);